/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class GSDK_PBMutableArray, NSString;

@interface ACPEvent : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasParamsArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * paramsArray; 
@property (assign,nonatomic) BOOL hasName; 
@property (nonatomic,retain) NSString * name; 
@property (assign,nonatomic) BOOL hasTimestampMillis; 
@property (assign,nonatomic) long long timestampMillis; 
@property (assign,nonatomic) BOOL hasPreviousTimestampMillis; 
@property (assign,nonatomic) long long previousTimestampMillis; 
@property (assign,nonatomic) BOOL hasCount; 
@property (assign,nonatomic) int count; 
+(id)descriptor;
-(id)setPreviousTimestampMillis:(long long)arg1 ;
-(long long)previousTimestampMillis;
-(GSDK_PBMutableArray *)paramsArray;
-(id)setTimestampMillis:(long long)arg1 ;
-(id)setName:(NSString *)arg1 ;
@end

