/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class ACPStringFilter, ACPNumberFilter, NSString;

@interface ACPFilter : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasStringFilter; 
@property (nonatomic,retain) ACPStringFilter * stringFilter; 
@property (assign,nonatomic) BOOL hasNumberFilter; 
@property (nonatomic,retain) ACPNumberFilter * numberFilter; 
@property (assign,nonatomic) BOOL hasComplement; 
@property (assign,nonatomic) BOOL complement; 
@property (assign,nonatomic) BOOL hasParamName; 
@property (nonatomic,retain) NSString * paramName; 
+(id)descriptor;
@end

