/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, GSDK_PBMutableArray;

@interface ACPMeasurementConfig : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasVersion; 
@property (assign,nonatomic) long long version; 
@property (assign,nonatomic) BOOL hasGmpAppId; 
@property (nonatomic,retain) NSString * gmpAppId; 
@property (assign,nonatomic) BOOL hasBuilderVersion; 
@property (assign,nonatomic) int builderVersion; 
@property (assign,nonatomic) BOOL hasSettingsArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * settingsArray; 
@property (assign,nonatomic) BOOL hasEventConfigArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * eventConfigArray; 
@property (assign,nonatomic) BOOL hasAudiencesArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * audiencesArray; 
+(id)descriptor;
-(long long)version;
-(BOOL)hasVersion;
-(GSDK_PBMutableArray *)eventConfigArray;
-(NSString *)gmpAppId;
-(GSDK_PBMutableArray *)settingsArray;
@end

