/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class GSDK_PBMutableArray, NSString;

@interface ACPMeasurementBundle : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasProtocolVersion; 
@property (assign,nonatomic) int protocolVersion; 
@property (assign,nonatomic) BOOL hasEventsArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * eventsArray; 
@property (assign,nonatomic) BOOL hasUserAttributesArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * userAttributesArray; 
@property (assign,nonatomic) BOOL hasUploadTimestampMillis; 
@property (assign,nonatomic) long long uploadTimestampMillis; 
@property (assign,nonatomic) BOOL hasStartTimestampMillis; 
@property (assign,nonatomic) long long startTimestampMillis; 
@property (assign,nonatomic) BOOL hasEndTimestampMillis; 
@property (assign,nonatomic) long long endTimestampMillis; 
@property (assign,nonatomic) BOOL hasPreviousBundleStartTimestampMillis; 
@property (assign,nonatomic) long long previousBundleStartTimestampMillis; 
@property (assign,nonatomic) BOOL hasPreviousBundleEndTimestampMillis; 
@property (assign,nonatomic) long long previousBundleEndTimestampMillis; 
@property (assign,nonatomic) BOOL hasPlatform; 
@property (nonatomic,retain) NSString * platform; 
@property (assign,nonatomic) BOOL hasOsVersion; 
@property (nonatomic,retain) NSString * osVersion; 
@property (assign,nonatomic) BOOL hasDeviceModel; 
@property (nonatomic,retain) NSString * deviceModel; 
@property (assign,nonatomic) BOOL hasUserDefaultLanguage; 
@property (nonatomic,retain) NSString * userDefaultLanguage; 
@property (assign,nonatomic) BOOL hasTimeZoneOffsetMinutes; 
@property (assign,nonatomic) int timeZoneOffsetMinutes; 
@property (assign,nonatomic) BOOL hasAppStore; 
@property (nonatomic,retain) NSString * appStore; 
@property (assign,nonatomic) BOOL hasAppId; 
@property (nonatomic,retain) NSString * appId; 
@property (assign,nonatomic) BOOL hasAppIdNumeric; 
@property (assign,nonatomic) long long appIdNumeric; 
@property (assign,nonatomic) BOOL hasAppVersion; 
@property (nonatomic,retain) NSString * appVersion; 
@property (assign,nonatomic) BOOL hasGmpVersion; 
@property (assign,nonatomic) long long gmpVersion; 
@property (assign,nonatomic) BOOL hasUploadingGmpVersion; 
@property (assign,nonatomic) long long uploadingGmpVersion; 
@property (assign,nonatomic) BOOL hasResettableDeviceId; 
@property (nonatomic,retain) NSString * resettableDeviceId; 
@property (assign,nonatomic) BOOL hasVendorDeviceId; 
@property (nonatomic,retain) NSString * vendorDeviceId; 
@property (assign,nonatomic) BOOL hasLimitedAdTracking; 
@property (assign,nonatomic) BOOL limitedAdTracking; 
@property (assign,nonatomic) BOOL hasAppInstanceId; 
@property (nonatomic,retain) NSString * appInstanceId; 
@property (assign,nonatomic) BOOL hasDevCertHash; 
@property (assign,nonatomic) long long devCertHash; 
@property (assign,nonatomic) BOOL hasBundleSequentialIndex; 
@property (assign,nonatomic) int bundleSequentialIndex; 
@property (assign,nonatomic) BOOL hasHealthMonitor; 
@property (nonatomic,retain) NSString * healthMonitor; 
@property (assign,nonatomic) BOOL hasGmpAppId; 
@property (nonatomic,retain) NSString * gmpAppId; 
@property (assign,nonatomic) BOOL hasServiceUpload; 
@property (assign,nonatomic) BOOL serviceUpload; 
@property (assign,nonatomic) BOOL hasAudienceEvaluationResultsArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * audienceEvaluationResultsArray; 
@property (assign,nonatomic) BOOL hasFirebaseInstanceId; 
@property (nonatomic,retain) NSString * firebaseInstanceId; 
@property (assign,nonatomic) BOOL hasAppVersionMajor; 
@property (assign,nonatomic) int appVersionMajor; 
@property (assign,nonatomic) BOOL hasAppVersionMinor; 
@property (assign,nonatomic) int appVersionMinor; 
@property (assign,nonatomic) BOOL hasAppVersionRelease; 
@property (assign,nonatomic) int appVersionRelease; 
@property (assign,nonatomic) BOOL hasSsaid; 
@property (nonatomic,retain) NSString * ssaid; 
@property (assign,nonatomic) BOOL hasConfigVersion; 
@property (assign,nonatomic) long long configVersion; 
+(id)descriptor;
-(id)setUploadTimestampMillis:(long long)arg1 ;
-(id)setUploadingGmpVersion:(long long)arg1 ;
-(NSString *)resettableDeviceId;
-(int)bundleSequentialIndex;
-(long long)endTimestampMillis;
-(NSString *)appId;
-(id)setConfigVersion:(long long)arg1 ;
-(NSString *)healthMonitor;
-(id)setHealthMonitor:(NSString *)arg1 ;
-(id)setBundleSequentialIndex:(int)arg1 ;
-(id)setPreviousBundleStartTimestampMillis:(long long)arg1 ;
-(id)setPreviousBundleEndTimestampMillis:(long long)arg1 ;
-(GSDK_PBMutableArray *)eventsArray;
-(id)setEndTimestampMillis:(long long)arg1 ;
-(id)setStartTimestampMillis:(long long)arg1 ;
-(GSDK_PBMutableArray *)userAttributesArray;
-(id)setUserAttributesArray:(GSDK_PBMutableArray *)arg1 ;
-(id)setUserDefaultLanguage:(NSString *)arg1 ;
-(id)setTimeZoneOffsetMinutes:(int)arg1 ;
-(id)setOsVersion:(NSString *)arg1 ;
-(id)setDeviceModel:(NSString *)arg1 ;
-(id)setResettableDeviceId:(NSString *)arg1 ;
-(id)setLimitedAdTracking:(BOOL)arg1 ;
-(id)setAppVersionMajor:(int)arg1 ;
-(id)setFirebaseInstanceId:(NSString *)arg1 ;
-(id)setGmpVersion:(long long)arg1 ;
-(id)setGmpAppId:(NSString *)arg1 ;
-(id)setAppVersion:(NSString *)arg1 ;
-(id)setAppInstanceId:(NSString *)arg1 ;
-(id)setAppId:(NSString *)arg1 ;
-(id)setProtocolVersion:(int)arg1 ;
-(id)setPlatform:(NSString *)arg1 ;
@end

