/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString;

@interface ACPNumberFilter : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasComparisonType; 
@property (assign,nonatomic) int comparisonType; 
@property (assign,nonatomic) BOOL hasMatchAsFloat; 
@property (assign,nonatomic) BOOL matchAsFloat; 
@property (assign,nonatomic) BOOL hasComparisonValue; 
@property (nonatomic,retain) NSString * comparisonValue; 
@property (assign,nonatomic) BOOL hasMinComparisonValue; 
@property (nonatomic,retain) NSString * minComparisonValue; 
@property (assign,nonatomic) BOOL hasMaxComparisonValue; 
@property (nonatomic,retain) NSString * maxComparisonValue; 
+(id)descriptor;
@end

