/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSMutableArray;

@interface ADJActivityState : NSObject <NSCoding, NSCopying> {

	BOOL _enabled;
	BOOL _askingAttribution;
	BOOL _updatePackages;
	BOOL _isPersisted;
	int _eventCount;
	int _sessionCount;
	int _subsessionCount;
	NSString* _uuid;
	NSString* _deviceToken;
	double _timeSpent;
	double _lastActivity;
	double _sessionLength;
	NSMutableArray* _transactionIds;
	double _lastInterval;

}

@property (assign,nonatomic) BOOL enabled;                                 //@synthesize enabled=_enabled - In the implementation block
@property (assign,nonatomic) BOOL askingAttribution;                       //@synthesize askingAttribution=_askingAttribution - In the implementation block
@property (nonatomic,copy) NSString * uuid;                                //@synthesize uuid=_uuid - In the implementation block
@property (nonatomic,copy) NSString * deviceToken;                         //@synthesize deviceToken=_deviceToken - In the implementation block
@property (assign,nonatomic) BOOL updatePackages;                          //@synthesize updatePackages=_updatePackages - In the implementation block
@property (assign,nonatomic) int eventCount;                               //@synthesize eventCount=_eventCount - In the implementation block
@property (assign,nonatomic) int sessionCount;                             //@synthesize sessionCount=_sessionCount - In the implementation block
@property (assign,nonatomic) int subsessionCount;                          //@synthesize subsessionCount=_subsessionCount - In the implementation block
@property (assign,nonatomic) double timeSpent;                             //@synthesize timeSpent=_timeSpent - In the implementation block
@property (assign,nonatomic) double lastActivity;                          //@synthesize lastActivity=_lastActivity - In the implementation block
@property (assign,nonatomic) double sessionLength;                         //@synthesize sessionLength=_sessionLength - In the implementation block
@property (nonatomic,retain) NSMutableArray * transactionIds;              //@synthesize transactionIds=_transactionIds - In the implementation block
@property (assign,nonatomic) BOOL isPersisted;                             //@synthesize isPersisted=_isPersisted - In the implementation block
@property (assign,nonatomic) double lastInterval;                          //@synthesize lastInterval=_lastInterval - In the implementation block
-(void)setDeviceToken:(NSString *)arg1 ;
-(NSString *)deviceToken;
-(BOOL)updatePackages;
-(void)setUpdatePackages:(BOOL)arg1 ;
-(void)setAskingAttribution:(BOOL)arg1 ;
-(void)setSessionCount:(int)arg1 ;
-(void)resetSessionAttributes:(double)arg1 ;
-(int)sessionCount;
-(int)subsessionCount;
-(void)setSubsessionCount:(int)arg1 ;
-(double)sessionLength;
-(void)setSessionLength:(double)arg1 ;
-(BOOL)askingAttribution;
-(void)setEventCount:(int)arg1 ;
-(double)timeSpent;
-(void)setTimeSpent:(double)arg1 ;
-(BOOL)findTransactionId:(id)arg1 ;
-(NSMutableArray *)transactionIds;
-(void)addTransactionId:(id)arg1 ;
-(void)assignUuid:(id)arg1 ;
-(void)setTransactionIds:(NSMutableArray *)arg1 ;
-(void)setIsPersisted:(BOOL)arg1 ;
-(BOOL)isPersisted;
-(BOOL)enabled;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(id)description;
-(void)setEnabled:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)uuid;
-(int)eventCount;
-(void)setUuid:(NSString *)arg1 ;
-(double)lastInterval;
-(void)setLastInterval:(double)arg1 ;
-(void)setLastActivity:(double)arg1 ;
-(double)lastActivity;
@end

