/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ADJAdjustFactory : NSObject
+(void)setPackageHandler:(id)arg1 ;
+(void)setAttributionHandler:(id)arg1 ;
+(void)setSdkClickHandler:(id)arg1 ;
+(double)sessionInterval;
+(double)subsessionInterval;
+(double)timerStart;
+(double)timerInterval;
+(id)packageHandlerForActivityHandler:(id)arg1 startsSending:(BOOL)arg2 ;
+(id)attributionHandlerForActivityHandler:(id)arg1 withAttributionPackage:(id)arg2 startsSending:(BOOL)arg3 hasAttributionChangedDelegate:(BOOL)arg4 ;
+(id)sdkClickHandlerWithStartsPaused:(BOOL)arg1 ;
+(double)maxDelayStart;
+(id)requestHandlerForPackageHandler:(id)arg1 ;
+(id)activityHandlerWithConfig:(id)arg1 sessionParametersActionsArray:(id)arg2 ;
+(id)packageHandlerBackoffStrategy;
+(id)sdkClickHandlerBackoffStrategy;
+(void)setSessionInterval:(double)arg1 ;
+(void)setSubsessionInterval:(double)arg1 ;
+(void)setTimerInterval:(double)arg1 ;
+(void)setTimerStart:(double)arg1 ;
+(void)setPackageHandlerBackoffStrategy:(id)arg1 ;
+(void)setSdkClickHandlerBackoffStrategy:(id)arg1 ;
+(void)setMaxDelayStart:(double)arg1 ;
+(BOOL)testing;
+(void)setActivityHandler:(id)arg1 ;
+(id)logger;
+(void)setLogger:(id)arg1 ;
+(void)setTesting:(BOOL)arg1 ;
+(void)setRequestHandler:(id)arg1 ;
+(void)teardown;
@end

