/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface ADJAttribution : NSObject <NSCoding, NSCopying> {

	NSString* _trackerToken;
	NSString* _trackerName;
	NSString* _network;
	NSString* _campaign;
	NSString* _adgroup;
	NSString* _creative;
	NSString* _clickLabel;

}

@property (nonatomic,copy) NSString * trackerToken;              //@synthesize trackerToken=_trackerToken - In the implementation block
@property (nonatomic,copy) NSString * trackerName;               //@synthesize trackerName=_trackerName - In the implementation block
@property (nonatomic,copy) NSString * network;                   //@synthesize network=_network - In the implementation block
@property (nonatomic,copy) NSString * campaign;                  //@synthesize campaign=_campaign - In the implementation block
@property (nonatomic,copy) NSString * adgroup;                   //@synthesize adgroup=_adgroup - In the implementation block
@property (nonatomic,copy) NSString * creative;                  //@synthesize creative=_creative - In the implementation block
@property (nonatomic,copy) NSString * clickLabel;                //@synthesize clickLabel=_clickLabel - In the implementation block
+(id)dataWithJsonDict:(id)arg1 ;
-(void)setTrackerName:(NSString *)arg1 ;
-(void)setCampaign:(NSString *)arg1 ;
-(void)setAdgroup:(NSString *)arg1 ;
-(void)setCreative:(NSString *)arg1 ;
-(id)initWithJsonDict:(id)arg1 ;
-(void)setTrackerToken:(NSString *)arg1 ;
-(void)setClickLabel:(NSString *)arg1 ;
-(NSString *)trackerToken;
-(NSString *)trackerName;
-(NSString *)campaign;
-(NSString *)adgroup;
-(NSString *)creative;
-(NSString *)clickLabel;
-(BOOL)isEqualToAttribution:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionary;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)network;
-(void)setNetwork:(NSString *)arg1 ;
@end

