/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ADJBackoffStrategy : NSObject {

	unsigned long long _minRetries;
	double _secondMultiplier;
	double _maxWait;
	double _minRange;
	double _maxRange;

}

@property (assign,nonatomic) unsigned long long minRetries;              //@synthesize minRetries=_minRetries - In the implementation block
@property (assign,nonatomic) double secondMultiplier;                    //@synthesize secondMultiplier=_secondMultiplier - In the implementation block
@property (assign,nonatomic) double maxWait;                             //@synthesize maxWait=_maxWait - In the implementation block
@property (assign,nonatomic) double minRange;                            //@synthesize minRange=_minRange - In the implementation block
@property (assign,nonatomic) double maxRange;                            //@synthesize maxRange=_maxRange - In the implementation block
+(id)backoffStrategyWithType:(long long)arg1 ;
-(unsigned long long)minRetries;
-(double)secondMultiplier;
-(double)minRange;
-(void)saveStrategy:(long long)arg1 secondMultiplier:(double)arg2 maxWait:(double)arg3 minRange:(double)arg4 maxRange:(double)arg5 ;
-(void)setMinRetries:(unsigned long long)arg1 ;
-(void)setSecondMultiplier:(double)arg1 ;
-(void)setMinRange:(double)arg1 ;
-(id)initWithType:(long long)arg1 ;
-(double)maxWait;
-(void)setMaxWait:(double)arg1 ;
-(double)maxRange;
-(void)setMaxRange:(double)arg1 ;
@end

