/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol AdjustDelegate, ADJLogger;
@class NSString, NSObject;

@interface ADJConfig : NSObject <NSCopying> {

	BOOL _eventBufferingEnabled;
	BOOL _sendInBackground;
	BOOL _hasResponseDelegate;
	BOOL _hasAttributionChangedDelegate;
	BOOL _allowSuppressLogLevel;
	int _logLevel;
	NSString* _sdkPrefix;
	NSString* _defaultTracker;
	NSString* _appToken;
	NSString* _environment;
	NSObject*<AdjustDelegate> _delegate;
	double _delayStart;
	NSString* _userAgent;
	id<ADJLogger> _logger;

}

@property (assign,nonatomic,__weak) id<ADJLogger> logger;                            //@synthesize logger=_logger - In the implementation block
@property (assign,nonatomic) BOOL allowSuppressLogLevel;                             //@synthesize allowSuppressLogLevel=_allowSuppressLogLevel - In the implementation block
@property (nonatomic,copy) NSString * sdkPrefix;                                     //@synthesize sdkPrefix=_sdkPrefix - In the implementation block
@property (nonatomic,copy) NSString * defaultTracker;                                //@synthesize defaultTracker=_defaultTracker - In the implementation block
@property (nonatomic,copy,readonly) NSString * appToken;                             //@synthesize appToken=_appToken - In the implementation block
@property (nonatomic,copy,readonly) NSString * environment;                          //@synthesize environment=_environment - In the implementation block
@property (assign,nonatomic) int logLevel;                                           //@synthesize logLevel=_logLevel - In the implementation block
@property (assign,nonatomic) BOOL eventBufferingEnabled;                             //@synthesize eventBufferingEnabled=_eventBufferingEnabled - In the implementation block
@property (assign,nonatomic,__weak) NSObject*<AdjustDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL sendInBackground;                                  //@synthesize sendInBackground=_sendInBackground - In the implementation block
@property (assign,nonatomic) double delayStart;                                      //@synthesize delayStart=_delayStart - In the implementation block
@property (nonatomic,copy) NSString * userAgent;                                     //@synthesize userAgent=_userAgent - In the implementation block
@property (nonatomic,readonly) BOOL hasResponseDelegate;                             //@synthesize hasResponseDelegate=_hasResponseDelegate - In the implementation block
@property (nonatomic,readonly) BOOL hasAttributionChangedDelegate;                   //@synthesize hasAttributionChangedDelegate=_hasAttributionChangedDelegate - In the implementation block
+(id)configWithAppToken:(id)arg1 environment:(id)arg2 allowSuppressLogLevel:(BOOL)arg3 ;
+(id)configWithAppToken:(id)arg1 environment:(id)arg2 ;
-(void)setSdkPrefix:(NSString *)arg1 ;
-(void)setEventBufferingEnabled:(BOOL)arg1 ;
-(void)setSendInBackground:(BOOL)arg1 ;
-(void)setDelayStart:(double)arg1 ;
-(double)delayStart;
-(NSString *)sdkPrefix;
-(BOOL)eventBufferingEnabled;
-(NSString *)defaultTracker;
-(BOOL)sendInBackground;
-(BOOL)hasAttributionChangedDelegate;
-(id)initWithAppToken:(id)arg1 environment:(id)arg2 ;
-(id)initWithAppToken:(id)arg1 environment:(id)arg2 allowSuppressLogLevel:(BOOL)arg3 ;
-(void)setAllowSuppressLogLevel:(BOOL)arg1 ;
-(void)setLogLevel:(int)arg1 environment:(id)arg2 ;
-(BOOL)checkAppToken:(id)arg1 ;
-(BOOL)allowSuppressLogLevel;
-(BOOL)hasResponseDelegate;
-(void)setDefaultTracker:(NSString *)arg1 ;
-(int)logLevel;
-(void)setLogLevel:(int)arg1 ;
-(void)setDelegate:(NSObject*<AdjustDelegate>)arg1 ;
-(NSObject*<AdjustDelegate>)delegate;
-(NSString *)environment;
-(BOOL)isValid;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setUserAgent:(NSString *)arg1 ;
-(NSString *)userAgent;
-(BOOL)checkEnvironment:(id)arg1 ;
-(id<ADJLogger>)logger;
-(void)setLogger:(id<ADJLogger>)arg1 ;
-(NSString *)appToken;
@end

