/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol ADJLogger;
@class NSString, NSNumber, NSData, NSMutableDictionary, NSDictionary;

@interface ADJEvent : NSObject <NSCopying> {

	BOOL _emptyReceipt;
	NSString* _eventToken;
	NSNumber* _revenue;
	NSString* _transactionId;
	NSString* _currency;
	NSData* _receipt;
	id<ADJLogger> _logger;
	NSMutableDictionary* _callbackMutableParameters;
	NSMutableDictionary* _partnerMutableParameters;

}

@property (assign,nonatomic,__weak) id<ADJLogger> logger;                                  //@synthesize logger=_logger - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * callbackMutableParameters;              //@synthesize callbackMutableParameters=_callbackMutableParameters - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * partnerMutableParameters;               //@synthesize partnerMutableParameters=_partnerMutableParameters - In the implementation block
@property (nonatomic,copy,readonly) NSString * eventToken;                                 //@synthesize eventToken=_eventToken - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * revenue;                                    //@synthesize revenue=_revenue - In the implementation block
@property (nonatomic,readonly) NSDictionary * callbackParameters; 
@property (nonatomic,readonly) NSDictionary * partnerParameters; 
@property (nonatomic,copy,readonly) NSString * transactionId;                              //@synthesize transactionId=_transactionId - In the implementation block
@property (nonatomic,copy,readonly) NSString * currency;                                   //@synthesize currency=_currency - In the implementation block
@property (nonatomic,copy,readonly) NSData * receipt;                                      //@synthesize receipt=_receipt - In the implementation block
@property (nonatomic,readonly) BOOL emptyReceipt;                                          //@synthesize emptyReceipt=_emptyReceipt - In the implementation block
+(id)eventWithEventToken:(id)arg1 ;
-(NSString *)eventToken;
-(void)setRevenue:(double)arg1 currency:(id)arg2 ;
-(void)addCallbackParameter:(id)arg1 value:(id)arg2 ;
-(void)addPartnerParameter:(id)arg1 value:(id)arg2 ;
-(void)setReceipt:(id)arg1 transactionId:(id)arg2 ;
-(NSDictionary *)callbackParameters;
-(NSDictionary *)partnerParameters;
-(id)initWithEventToken:(id)arg1 ;
-(BOOL)checkEventToken:(id)arg1 ;
-(NSMutableDictionary *)callbackMutableParameters;
-(void)setCallbackMutableParameters:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)partnerMutableParameters;
-(void)setPartnerMutableParameters:(NSMutableDictionary *)arg1 ;
-(BOOL)checkRevenue:(id)arg1 currency:(id)arg2 ;
-(BOOL)checkReceipt:(id)arg1 transactionId:(id)arg2 ;
-(NSNumber *)revenue;
-(NSData *)receipt;
-(BOOL)emptyReceipt;
-(BOOL)isValid;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)currency;
-(id<ADJLogger>)logger;
-(void)setLogger:(id<ADJLogger>)arg1 ;
-(void)setTransactionId:(NSString *)arg1 ;
-(NSString *)transactionId;
@end

