/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ADJInternalState : NSObject {

	BOOL _enabled;
	BOOL _offline;
	BOOL _background;
	BOOL _delayStart;
	BOOL _updatePackages;

}

@property (assign,nonatomic) BOOL enabled;                     //@synthesize enabled=_enabled - In the implementation block
@property (assign,nonatomic) BOOL offline;                     //@synthesize offline=_offline - In the implementation block
@property (assign,nonatomic) BOOL background;                  //@synthesize background=_background - In the implementation block
@property (assign,nonatomic) BOOL delayStart;                  //@synthesize delayStart=_delayStart - In the implementation block
@property (assign,nonatomic) BOOL updatePackages;              //@synthesize updatePackages=_updatePackages - In the implementation block
-(void)setDelayStart:(BOOL)arg1 ;
-(BOOL)delayStart;
-(BOOL)updatePackages;
-(BOOL)isDelayStart;
-(BOOL)isToStartNow;
-(BOOL)isToUpdatePackages;
-(void)setUpdatePackages:(BOOL)arg1 ;
-(BOOL)isOffline;
-(BOOL)offline;
-(void)setOffline:(BOOL)arg1 ;
-(BOOL)enabled;
-(id)init;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isEnabled;
-(BOOL)background;
-(void)setBackground:(BOOL)arg1 ;
-(BOOL)isBackground;
-(BOOL)isForeground;
-(BOOL)isDisabled;
-(BOOL)isOnline;
@end

