/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ADJKeychain : NSObject
+(id)getInstance;
+(id)valueForKeychainKey:(id)arg1 service:(id)arg2 ;
+(BOOL)setValue:(id)arg1 forKeychainKey:(id)arg2 inService:(id)arg3 ;
-(id)valueForKeychainKey:(id)arg1 service:(id)arg2 ;
-(BOOL)setValue:(id)arg1 forKeychainKey:(id)arg2 inService:(id)arg3 ;
-(int)setValueWithStatus:(id)arg1 forKeychainKey:(id)arg2 inService:(id)arg3 ;
-(BOOL)wasWritingSuccessful:(id)arg1 forKeychainKey:(id)arg2 inService:(id)arg3 ;
-(id)keychainItemForKey:(id)arg1 service:(id)arg2 ;
-(id)init;
@end

