/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/ADJLogger.h>

@protocol ADJLogger
@required
-(void)lockLogLevel;
-(void)verbose:(id)arg1;
-(void)debug:(id)arg1;
-(void)info:(id)arg1;
-(void)assert:(id)arg1;
-(void)setLogLevel:(int)arg1;
-(void)error:(id)arg1;
-(void)warn:(id)arg1;

@end


@interface ADJLogger : NSObject <ADJLogger> {

	BOOL _logLevelLocked;
	int _loglevel;

}

@property (assign,nonatomic) int loglevel;                     //@synthesize loglevel=_loglevel - In the implementation block
@property (assign,nonatomic) BOOL logLevelLocked;              //@synthesize logLevelLocked=_logLevelLocked - In the implementation block
+(int)LogLevelFromString:(id)arg1 ;
-(void)lockLogLevel;
-(void)verbose:(id)arg1 ;
-(void)debug:(id)arg1 ;
-(void)info:(id)arg1 ;
-(void)setLogLevelLocked:(BOOL)arg1 ;
-(BOOL)logLevelLocked;
-(int)loglevel;
-(void)logLevel:(id)arg1 format:(id)arg2 parameters:(char*)arg3 ;
-(void)assert:(id)arg1 ;
-(void)setLogLevel:(int)arg1 ;
-(id)init;
-(void)error:(id)arg1 ;
-(void)warn:(id)arg1 ;
-(void)setLoglevel:(int)arg1 ;
@end

