/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSString, NSDictionary, ADJAttribution, ADJDeviceInfo, ADJActivityState, ADJConfig;

@interface ADJPackageBuilder : NSObject {

	NSDate* _clickTime;
	NSDate* _purchaseTime;
	NSString* _deeplink;
	NSString* _deviceToken;
	NSDictionary* _iadDetails;
	NSDictionary* _deeplinkParameters;
	ADJAttribution* _attribution;
	double _createdAt;
	ADJDeviceInfo* _deviceInfo;
	ADJActivityState* _activityState;
	ADJConfig* _adjustConfig;

}

@property (assign,nonatomic) double createdAt;                               //@synthesize createdAt=_createdAt - In the implementation block
@property (assign,nonatomic,__weak) ADJDeviceInfo * deviceInfo;              //@synthesize deviceInfo=_deviceInfo - In the implementation block
@property (nonatomic,copy) ADJActivityState * activityState;                 //@synthesize activityState=_activityState - In the implementation block
@property (assign,nonatomic,__weak) ADJConfig * adjustConfig;                //@synthesize adjustConfig=_adjustConfig - In the implementation block
@property (nonatomic,copy) NSDate * clickTime;                               //@synthesize clickTime=_clickTime - In the implementation block
@property (nonatomic,copy) NSDate * purchaseTime;                            //@synthesize purchaseTime=_purchaseTime - In the implementation block
@property (nonatomic,copy) NSString * deeplink;                              //@synthesize deeplink=_deeplink - In the implementation block
@property (nonatomic,copy) NSString * deviceToken;                           //@synthesize deviceToken=_deviceToken - In the implementation block
@property (nonatomic,retain) NSDictionary * iadDetails;                      //@synthesize iadDetails=_iadDetails - In the implementation block
@property (nonatomic,retain) NSDictionary * deeplinkParameters;              //@synthesize deeplinkParameters=_deeplinkParameters - In the implementation block
@property (nonatomic,copy) ADJAttribution * attribution;                     //@synthesize attribution=_attribution - In the implementation block
+(void)parameters:(id)arg1 setDuration:(double)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setString:(id)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setDictionary:(id)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setInt:(int)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setNumber:(id)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setDate:(id)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setDate1970:(double)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setBool:(BOOL)arg2 forKey:(id)arg3 ;
+(void)parameters:(id)arg1 setDictionaryJson:(id)arg2 forKey:(id)arg3 ;
-(void)setDeviceToken:(NSString *)arg1 ;
-(NSString *)deviceToken;
-(void)setAdjustConfig:(ADJConfig *)arg1 ;
-(ADJConfig *)adjustConfig;
-(id)initWithDeviceInfo:(id)arg1 activityState:(id)arg2 config:(id)arg3 createdAt:(double)arg4 ;
-(void)setPurchaseTime:(NSDate *)arg1 ;
-(void)setClickTime:(NSDate *)arg1 ;
-(id)buildClickPackage:(id)arg1 ;
-(void)setIadDetails:(NSDictionary *)arg1 ;
-(id)buildAttributionPackage;
-(void)setActivityState:(ADJActivityState *)arg1 ;
-(id)buildSessionPackage:(id)arg1 isInDelay:(BOOL)arg2 ;
-(id)buildEventPackage:(id)arg1 sessionParameters:(id)arg2 isInDelay:(BOOL)arg3 ;
-(void)setDeeplinkParameters:(NSDictionary *)arg1 ;
-(id)defaultParameters;
-(id)defaultActivityPackage;
-(id)eventSuffix:(id)arg1 ;
-(id)idsParameters;
-(NSDictionary *)deeplinkParameters;
-(NSDate *)clickTime;
-(NSDate *)purchaseTime;
-(NSDictionary *)iadDetails;
-(void)injectDeviceInfoIds:(id)arg1 intoParameters:(id)arg2 ;
-(void)injectConfig:(id)arg1 intoParameters:(id)arg2 ;
-(void)injectCommonParameters:(id)arg1 ;
-(void)injectDeviceInfo:(id)arg1 intoParameters:(id)arg2 ;
-(void)injectActivityState:(id)arg1 intoParamters:(id)arg2 ;
-(void)setAttribution:(ADJAttribution *)arg1 ;
-(ADJAttribution *)attribution;
-(double)createdAt;
-(ADJActivityState *)activityState;
-(void)setDeviceInfo:(ADJDeviceInfo *)arg1 ;
-(ADJDeviceInfo *)deviceInfo;
-(NSString *)deeplink;
-(void)setDeeplink:(NSString *)arg1 ;
-(void)setCreatedAt:(double)arg1 ;
@end

