/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/ADJSdkClickHandler.h>

@protocol ADJSdkClickHandler
@required
-(void)sendSdkClick:(id)arg1;
-(void)pauseSending;
-(void)resumeSending;
-(id)initWithStartsSending:(BOOL)arg1;
-(void)teardown;

@end


@protocol OS_dispatch_queue, ADJLogger;
@class NSObject, ADJBackoffStrategy, NSMutableArray, NSURL;

@interface ADJSdkClickHandler : NSObject <ADJSdkClickHandler> {

	BOOL _paused;
	NSObject*<OS_dispatch_queue> _internalQueue;
	id<ADJLogger> _logger;
	ADJBackoffStrategy* _backoffStrategy;
	NSMutableArray* _packageQueue;
	NSURL* _baseUrl;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> internalQueue;              //@synthesize internalQueue=_internalQueue - In the implementation block
@property (assign,nonatomic,__weak) id<ADJLogger> logger;                             //@synthesize logger=_logger - In the implementation block
@property (nonatomic,retain) ADJBackoffStrategy * backoffStrategy;                    //@synthesize backoffStrategy=_backoffStrategy - In the implementation block
@property (assign,nonatomic) BOOL paused;                                             //@synthesize paused=_paused - In the implementation block
@property (nonatomic,retain) NSMutableArray * packageQueue;                           //@synthesize packageQueue=_packageQueue - In the implementation block
@property (nonatomic,retain) NSURL * baseUrl;                                         //@synthesize baseUrl=_baseUrl - In the implementation block
+(id)handlerWithStartsSending:(BOOL)arg1 ;
-(void)sendSdkClick:(id)arg1 ;
-(void)pauseSending;
-(void)resumeSending;
-(id)initWithStartsSending:(BOOL)arg1 ;
-(void)setBackoffStrategy:(ADJBackoffStrategy *)arg1 ;
-(ADJBackoffStrategy *)backoffStrategy;
-(NSMutableArray *)packageQueue;
-(void)setPackageQueue:(NSMutableArray *)arg1 ;
-(void)setBaseUrl:(NSURL *)arg1 ;
-(NSURL *)baseUrl;
-(void)initI:(id)arg1 ;
-(void)sendNextSdkClick;
-(void)sendSdkClickI:(id)arg1 sdkClickPackage:(id)arg2 ;
-(void)sendNextSdkClickI:(id)arg1 ;
-(void)setPaused:(BOOL)arg1 ;
-(BOOL)paused;
-(id<ADJLogger>)logger;
-(void)setLogger:(id<ADJLogger>)arg1 ;
-(NSObject*<OS_dispatch_queue>)internalQueue;
-(void)teardown;
-(void)setInternalQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

