/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ADJSystemProfile : NSObject
+(id)machineModel;
+(id)readSysctlbString:(const char*)arg1 errorLog:(id)arg2 ;
+(id)readCpuTypeSubtype:(int)arg1 readSubType:(BOOL)arg2 cpusubtype:(int)arg3 ;
+(id)cpuFamily;
+(int)cpuCount;
+(id)machineArch;
+(id)cpuBrand;
+(id)cpuFeatures;
+(id)cpuVendor;
+(id)appleLanguage;
+(long long)cpuSpeed;
+(long long)ramsize;
+(id)osVersion;
+(id)cpuType;
+(id)cpuSubtype;
+(BOOL)is64bit;
@end

