/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableDictionary;

@interface ADJSessionParameters : NSObject <NSCopying> {

	NSMutableDictionary* _callbackParameters;
	NSMutableDictionary* _partnerParameters;

}

@property (nonatomic,retain) NSMutableDictionary * callbackParameters;              //@synthesize callbackParameters=_callbackParameters - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * partnerParameters;               //@synthesize partnerParameters=_partnerParameters - In the implementation block
-(NSMutableDictionary *)callbackParameters;
-(NSMutableDictionary *)partnerParameters;
-(void)setCallbackParameters:(NSMutableDictionary *)arg1 ;
-(void)setPartnerParameters:(NSMutableDictionary *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

