/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source, ADJLogger;
@class NSObject, NSDate, NSString;

@interface ADJTimerOnce : NSObject {

	NSObject*<OS_dispatch_queue> _internalQueue;
	NSObject*<OS_dispatch_source> _source;
	/*^block*/id _block;
	unsigned long long _start;
	NSDate* _fireDate;
	id<ADJLogger> _logger;
	NSString* _name;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> internalQueue;              //@synthesize internalQueue=_internalQueue - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> source;                    //@synthesize source=_source - In the implementation block
@property (nonatomic,copy) id block;                                                  //@synthesize block=_block - In the implementation block
@property (nonatomic,readonly) unsigned long long start;                              //@synthesize start=_start - In the implementation block
@property (nonatomic,retain) NSDate * fireDate;                                       //@synthesize fireDate=_fireDate - In the implementation block
@property (assign,nonatomic,__weak) id<ADJLogger> logger;                             //@synthesize logger=_logger - In the implementation block
@property (nonatomic,copy) NSString * name;                                           //@synthesize name=_name - In the implementation block
+(id)timerWithBlock:(/*^block*/id)arg1 queue:(id)arg2 name:(id)arg3 ;
-(double)fireIn;
-(void)startIn:(double)arg1 ;
-(id)initBlock:(/*^block*/id)arg1 queue:(id)arg2 name:(id)arg3 ;
-(void)cancel;
-(void)dealloc;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)setSource:(NSObject*<OS_dispatch_source>)arg1 ;
-(NSObject*<OS_dispatch_source>)source;
-(void)setFireDate:(NSDate *)arg1 ;
-(unsigned long long)start;
-(NSDate *)fireDate;
-(void)cancel:(BOOL)arg1 ;
-(id<ADJLogger>)logger;
-(void)setLogger:(id<ADJLogger>)arg1 ;
-(id)block;
-(void)setBlock:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)internalQueue;
-(void)setInternalQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

