/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ADJLogger, ADJActivityHandler;
@class NSMutableArray;

@interface Adjust : NSObject {

	id<ADJLogger> _logger;
	id<ADJActivityHandler> _activityHandler;
	NSMutableArray* _sessionParametersActionsArray;

}

@property (assign,nonatomic,__weak) id<ADJLogger> logger;                                 //@synthesize logger=_logger - In the implementation block
@property (nonatomic,retain) id<ADJActivityHandler> activityHandler;                      //@synthesize activityHandler=_activityHandler - In the implementation block
@property (nonatomic,retain) NSMutableArray * sessionParametersActionsArray;              //@synthesize sessionParametersActionsArray=_sessionParametersActionsArray - In the implementation block
+(void)appDidLaunch:(id)arg1 ;
+(void)trackSubsessionStart;
+(void)trackEvent:(id)arg1 ;
+(void)setDeviceToken:(id)arg1 ;
+(id)idfa;
+(void)sendFirstPackages;
+(void)addSessionPartnerParameter:(id)arg1 value:(id)arg2 ;
+(void)addSessionCallbackParameter:(id)arg1 value:(id)arg2 ;
+(void)removeSessionPartnerParameter:(id)arg1 ;
+(void)removeSessionCallbackParameter:(id)arg1 ;
+(void)resetSessionPartnerParameters;
+(void)resetSessionCallbackParameters;
+(id)getInstance;
+(void)trackSubsessionEnd;
+(void)sendAdWordsRequest;
+(void)appWillOpenUrl:(id)arg1 ;
+(id)convertUniversalLink:(id)arg1 scheme:(id)arg2 ;
+(void)setEnabled:(BOOL)arg1 ;
+(BOOL)isEnabled;
+(void)setOfflineMode:(BOOL)arg1 ;
-(void)appDidLaunch:(id)arg1 ;
-(void)trackSubsessionStart;
-(void)trackEvent:(id)arg1 ;
-(void)setDeviceToken:(id)arg1 ;
-(id)idfa;
-(void)sendFirstPackages;
-(void)addSessionPartnerParameter:(id)arg1 value:(id)arg2 ;
-(void)addSessionCallbackParameter:(id)arg1 value:(id)arg2 ;
-(void)removeSessionPartnerParameter:(id)arg1 ;
-(void)removeSessionCallbackParameter:(id)arg1 ;
-(void)resetSessionPartnerParameters;
-(void)resetSessionCallbackParameters;
-(void)trackSubsessionEnd;
-(NSMutableArray *)sessionParametersActionsArray;
-(BOOL)checkActivityHandler;
-(void)setSessionParametersActionsArray:(NSMutableArray *)arg1 ;
-(void)teardown:(BOOL)arg1 ;
-(void)appWillOpenUrl:(id)arg1 ;
-(id)convertUniversalLink:(id)arg1 scheme:(id)arg2 ;
-(id)init;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isEnabled;
-(void)setActivityHandler:(id<ADJActivityHandler>)arg1 ;
-(id<ADJActivityHandler>)activityHandler;
-(id<ADJLogger>)logger;
-(void)setLogger:(id<ADJLogger>)arg1 ;
-(void)setOfflineMode:(BOOL)arg1 ;
@end

