/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/BFAppLinkReturnToRefererViewDelegate.h>

@protocol BFAppLinkReturnToRefererControllerDelegate;
@class UINavigationController, BFAppLinkReturnToRefererView, NSString;

@interface BFAppLinkReturnToRefererController : NSObject <BFAppLinkReturnToRefererViewDelegate> {

	UINavigationController* _navigationController;
	BFAppLinkReturnToRefererView* _view;
	id<BFAppLinkReturnToRefererControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<BFAppLinkReturnToRefererControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) BFAppLinkReturnToRefererView * view; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)returnToRefererViewDidTapInsideCloseButton:(id)arg1 ;
-(void)returnToRefererViewDidTapInsideLink:(id)arg1 link:(id)arg2 ;
-(id)initForDisplayAboveNavController:(id)arg1 ;
-(void)statusBarFrameDidChange:(id)arg1 ;
-(void)moveNavigationBar;
-(void)showViewForRefererAppLink:(id)arg1 ;
-(void)closeViewAnimated:(BOOL)arg1 explicitlyClosed:(BOOL)arg2 ;
-(void)openRefererAppLink:(id)arg1 ;
-(void)updateNavigationBarY:(double)arg1 ;
-(void)showViewForRefererURL:(id)arg1 ;
-(void)removeFromNavController;
-(void)closeViewAnimated:(BOOL)arg1 ;
-(void)setDelegate:(id<BFAppLinkReturnToRefererControllerDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<BFAppLinkReturnToRefererControllerDelegate>)delegate;
-(BFAppLinkReturnToRefererView *)view;
-(void)setView:(BFAppLinkReturnToRefererView *)arg1 ;
-(void)statusBarFrameWillChange:(id)arg1 ;
-(void)orientationDidChange:(id)arg1 ;
@end

