/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/AVCaptureVideoDataOutputSampleBufferDelegate.h>

@class AVCaptureDevice, AVCaptureSession, AVCaptureDeviceInput, AVCaptureVideoDataOutput, NSString;

@interface CameraCaptureController : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate> {

	AVCaptureDevice* _captureDevice;
	AVCaptureSession* _captureSession;
	AVCaptureDeviceInput* _captureInput;
	AVCaptureVideoDataOutput* _captureOutput;
	CMVideoSampling* _cmVideoSampling;
	void* _userData;
	unsigned long long _width;
	unsigned long long _height;

}

@property (nonatomic,retain) AVCaptureDevice * captureDevice;                       //@synthesize captureDevice=_captureDevice - In the implementation block
@property (nonatomic,retain) AVCaptureSession * captureSession;                     //@synthesize captureSession=_captureSession - In the implementation block
@property (nonatomic,retain) AVCaptureDeviceInput * captureInput;                   //@synthesize captureInput=_captureInput - In the implementation block
@property (nonatomic,retain) AVCaptureVideoDataOutput * captureOutput;              //@synthesize captureOutput=_captureOutput - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCaptureInput:(AVCaptureDeviceInput *)arg1 ;
-(void)setCaptureOutput:(AVCaptureVideoDataOutput *)arg1 ;
-(AVCaptureVideoDataOutput *)captureOutput;
-(AVCaptureDeviceInput *)captureInput;
-(id)pickFrameRateRange:(float)arg1 ;
-(id)pickPresetFromWidth:(int)arg1 height:(int)arg2 ;
-(BOOL)initCapture:(id)arg1 width:(int)arg2 height:(int)arg3 fps:(float)arg4 ;
-(void)stop;
-(void)start;
-(void)pause;
-(AVCaptureSession *)captureSession;
-(void)setCaptureSession:(AVCaptureSession *)arg1 ;
-(void)setCaptureDevice:(AVCaptureDevice *)arg1 ;
-(AVCaptureDevice *)captureDevice;
-(void)captureOutput:(id)arg1 didOutputSampleBuffer:(opaqueCMSampleBufferRef)arg2 fromConnection:(id)arg3 ;
@end

