/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSString;

@interface DeNAWPCommand : NSObject {

	NSDictionary* params;
	NSString* callerGameObjName;

}

@property (nonatomic,copy) NSDictionary * params; 
@property (nonatomic,copy) NSString * callerGameObjName; 
+(id)DEFAULT_ERROR;
+(id)DEFAULT_SUCCESS;
+(void)initialize;
-(BOOL)callMethod:(id)arg1 ;
-(id)getCreatedObj;
-(BOOL)hasParam:(id)arg1 ;
-(void)sendMessage:(id)arg1 withNSString:(id)arg2 ;
-(void)setParams:(NSDictionary *)arg1 ;
-(void)setCallerGameObjName:(NSString *)arg1 ;
-(id)post;
-(void)putCreatedObjWithId:(id)arg1 ;
-(void)removeCreatedObj;
-(BOOL)isTrue:(id)arg1 ;
-(void)sendMessage:(id)arg1 withDict:(id)arg2 ;
-(NSString *)callerGameObjName;
-(void)dealloc;
-(id)init;
-(NSDictionary *)params;
-(void)sendMessage:(id)arg1 ;
-(id)execute;
@end

