/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIAlertViewDelegate.h>

@class DeNAWPCommand, NSMutableDictionary, UIAlertView, NSString, UIColor;

@interface DeNAWPAlertViewController : UIViewController <UIAlertViewDelegate> {

	DeNAWPCommand* command;
	NSMutableDictionary* currentParams;
	UIAlertView* alertView;

}

@property (assign,nonatomic) UIAlertView * alertView; 
@property (nonatomic,retain) DeNAWPCommand * command; 
@property (nonatomic,retain) NSMutableDictionary * currentParams; 
@property (nonatomic,readonly) NSString * alertTitle; 
@property (nonatomic,readonly) NSString * alertMessage; 
@property (nonatomic,readonly) NSString * okLabel; 
@property (nonatomic,readonly) NSString * cancelLabel; 
@property (nonatomic,copy,readonly) UIColor * layoutBackgroundColor; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCurrentParams:(NSMutableDictionary *)arg1 ;
-(UIColor *)layoutBackgroundColor;
-(void)relayout;
-(NSString *)cancelLabel;
-(NSString *)okLabel;
-(NSMutableDictionary *)currentParams;
-(void)hide;
-(void)show;
-(void)dealloc;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2 ;
-(void)didPresentAlertView:(id)arg1 ;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(long long)arg2 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(NSString *)alertTitle;
-(NSString *)alertMessage;
-(void)showAlert;
-(void)destroy;
-(DeNAWPCommand *)command;
-(void)setCommand:(DeNAWPCommand *)arg1 ;
-(void)dismissAlert;
-(void)setAlertView:(UIAlertView *)arg1 ;
-(UIAlertView *)alertView;
@end

