/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <UIKit/UIWebViewDelegate.h>

@class DeNAWPCommand, NSMutableDictionary, UIView, NSURL, NSDictionary, NSString, UIColor;

@interface DeNAWPWebViewController : UIViewController <UIScrollViewDelegate, UIWebViewDelegate> {

	BOOL _hasReceivedError;
	DeNAWPCommand* _command;
	NSMutableDictionary* _currentParams;
	UIView* _parentView;
	NSURL* _initialRequestURL;
	NSDictionary* _initialHeaders;

}

@property (nonatomic,retain) NSURL * initialRequestURL;                           //@synthesize initialRequestURL=_initialRequestURL - In the implementation block
@property (nonatomic,retain) NSDictionary * initialHeaders;                       //@synthesize initialHeaders=_initialHeaders - In the implementation block
@property (assign,nonatomic) BOOL hasReceivedError;                               //@synthesize hasReceivedError=_hasReceivedError - In the implementation block
@property (nonatomic,copy,readonly) NSString * errorTitle; 
@property (nonatomic,copy,readonly) NSString * errorMessage; 
@property (nonatomic,copy,readonly) NSString * errorHtml; 
@property (nonatomic,retain) DeNAWPCommand * command;                             //@synthesize command=_command - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * currentParams;                 //@synthesize currentParams=_currentParams - In the implementation block
@property (assign,nonatomic) UIView * parentView;                                 //@synthesize parentView=_parentView - In the implementation block
@property (nonatomic,readonly) BOOL isModalWindow; 
@property (nonatomic,readonly) BOOL startVisible; 
@property (nonatomic,readonly) BOOL visible; 
@property (nonatomic,readonly) BOOL isUnitDip; 
@property (nonatomic,readonly) int gravity; 
@property (nonatomic,readonly) CGRect webViewRect; 
@property (nonatomic,readonly) CGSize size; 
@property (nonatomic,readonly) CGRect margins; 
@property (nonatomic,copy,readonly) NSURL * url; 
@property (nonatomic,copy,readonly) UIColor * layoutBackgroundColor; 
@property (nonatomic,copy,readonly) NSDictionary * headers; 
@property (nonatomic,copy,readonly) NSString * basicAuthURL; 
@property (nonatomic,copy,readonly) NSString * basicAuthId; 
@property (nonatomic,copy,readonly) NSString * basicAuthPass; 
@property (nonatomic,copy,readonly) NSString * basicAuthRealm; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCurrentParams:(NSMutableDictionary *)arg1 ;
-(UIColor *)layoutBackgroundColor;
-(void)relayout;
-(NSMutableDictionary *)currentParams;
-(void)setInitialRequestURL:(NSURL *)arg1 ;
-(void)setInitialHeaders:(NSDictionary *)arg1 ;
-(BOOL)isModalWindow;
-(CGSize)verticalOffset;
-(CGRect)webViewRect;
-(BOOL)supportsLayoutGuide;
-(double)statusBarheight;
-(NSURL *)initialRequestURL;
-(NSString *)basicAuthId;
-(NSString *)basicAuthPass;
-(void)setBasicAuthCredential;
-(void)addHeaders:(id)arg1 ;
-(void)setHasReceivedError:(BOOL)arg1 ;
-(NSString *)errorHtml;
-(BOOL)hasReceivedError;
-(BOOL)isUnitDip;
-(NSDictionary *)initialHeaders;
-(double)convertByDipOpt:(int)arg1 ;
-(long long)getPortNum;
-(NSString *)basicAuthRealm;
-(id)spinnerBackgroundColor;
-(UIView *)parentView;
-(void)setParentView:(UIView *)arg1 ;
-(void)loadUrl;
-(BOOL)startVisible;
-(void)setVisibility;
-(BOOL)canBack;
-(void)loadErrorPage;
-(void)hide;
-(void)show;
-(CGSize)size;
-(void)dealloc;
-(void)reload;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(NSURL *)url;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(BOOL)visible;
-(void)viewWillLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 ;
-(void)webViewDidStartLoad:(id)arg1 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(void)goBack;
-(int)gravity;
-(NSString *)basicAuthURL;
-(void)destroy;
-(DeNAWPCommand *)command;
-(void)setCommand:(DeNAWPCommand *)arg1 ;
-(id)spinnerColor;
-(NSDictionary *)headers;
-(CGRect)margins;
-(void)refreshView;
-(NSString *)errorTitle;
-(NSString *)errorMessage;
@end

