/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <Super Mario Run/DeNAWPDashbaordView.h>

@class UIView, DeNAWPWebViewController, NSMutableDictionary, UIButton, UILabel;

@interface DeNAWPTitledDashboardView : DeNAWPDashbaordView {

	BOOL isEnableHTMLTitle;
	UIView* layoutBar;
	DeNAWPWebViewController* parentVC;
	NSMutableDictionary* currentParams;
	double topOffset;
	double bottomOffset;
	UIButton* reloadButton;
	UILabel* titleLabel;
	UIButton* backButton;
	UIButton* backToGameButton;

}

@property (nonatomic,retain) UILabel * titleLabel; 
-(void)setCurrentParams:(id)arg1 ;
-(id)currentParams;
-(void)setLayoutBar:(id)arg1 ;
-(id)layoutBar;
-(void)setReloadButton:(id)arg1 ;
-(void)setBackToGameButton:(id)arg1 ;
-(void)backButtonPressed:(id)arg1 ;
-(id)backToGameButton;
-(void)backToAppButtonPressed:(id)arg1 ;
-(void)reloadButtonPressed:(id)arg1 ;
-(id)parentVC;
-(void)commonWebViewDidFinish;
-(void)setVisibleBackButton:(BOOL)arg1 ;
-(void)setVisibleReloadButton:(BOOL)arg1 ;
-(void)setParentVC:(id)arg1 ;
-(double)bottomOffset;
-(void)setBottomOffset:(double)arg1 ;
-(BOOL)enableHTMLTitle;
-(void)setupTitleLabel;
-(void)layoutHeader;
-(id)headerTitleLabelColor;
-(float)headerTitleLabelFontSize;
-(BOOL)isDisplayCustomTitle;
-(id)customHeaderTitle;
-(float)backButtonOffset;
-(float)reloadButtonOffset;
-(float)backToGameButtonOffset;
-(void)setHeaderTitleWithHTMLTitle;
-(id)defaultHeaderTitle;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(UILabel *)titleLabel;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(void)setTopOffset:(double)arg1 ;
-(double)topOffset;
-(id)backButton;
-(id)reloadButton;
-(void)setBackButton:(id)arg1 ;
@end

