/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Super Mario Run/Super Mario Run-Structs.h>
@interface FBSDKInternalUtility : NSObject
+(id)hexadecimalStringFromData:(id)arg1 ;
+(id)bundleForStrings;
+(BOOL)isMessengerAppInstalled;
+(BOOL)object:(id)arg1 isEqualToObject:(id)arg2 ;
+(void)checkRegisteredCanOpenURLScheme:(id)arg1 ;
+(id)JSONStringForObject:(id)arg1 error:(id*)arg2 invalidObjectHandler:(/*^block*/id)arg3 ;
+(BOOL)isFacebookAppInstalled;
+(void)array:(id)arg1 addObject:(id)arg2 ;
+(BOOL)isBrowserURL:(id)arg1 ;
+(void)dictionary:(id)arg1 setObject:(id)arg2 forKey:(id)arg3 ;
+(void)registerTransientObject:(id)arg1 ;
+(void)unregisterTransientObject:(id)arg1 ;
+(BOOL)isOSRunTimeVersionAtLeast:(SCD_Struct_FB33)arg1 ;
+(id)topMostViewController;
+(id)objectForJSONString:(id)arg1 error:(id*)arg2 ;
+(void)extractPermissionsFromResponse:(id)arg1 grantedPermissions:(id)arg2 declinedPermissions:(id)arg3 ;
+(BOOL)areAllPermissionsReadPermissions:(id)arg1 ;
+(BOOL)areAllPermissionsPublishPermissions:(id)arg1 ;
+(void)validateURLSchemes;
+(id)URLWithScheme:(id)arg1 host:(id)arg2 path:(id)arg3 queryParameters:(id)arg4 error:(id*)arg5 ;
+(id)facebookURLWithHostPrefix:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 error:(id*)arg4 ;
+(unsigned long long)currentTimeInMilliseconds;
+(void)deleteFacebookCookies;
+(id)appURLWithHost:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 error:(id*)arg4 ;
+(id)dictionaryFromFBURL:(id)arg1 ;
+(BOOL)isRegisteredURLScheme:(id)arg1 ;
+(BOOL)isRegisteredCanOpenURLScheme:(id)arg1 ;
+(id)queryStringWithDictionary:(id)arg1 error:(id*)arg2 invalidObjectHandler:(/*^block*/id)arg3 ;
+(id)facebookURLWithHostPrefix:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 defaultVersion:(id)arg4 error:(id*)arg5 ;
+(void)validateFacebookReservedURLSchemes;
+(long long)_compareOperatingSystemVersion:(SCD_Struct_FB33)arg1 toVersion:(SCD_Struct_FB33)arg2 ;
+(id)_convertObjectToJSONObject:(id)arg1 invalidObjectHandler:(/*^block*/id)arg2 stop:(BOOL*)arg3 ;
+(BOOL)isUIKitLinkTimeVersionAtLeast:(int)arg1 ;
+(BOOL)isUIKitRunTimeVersionAtLeast:(int)arg1 ;
+(void)validateAppID;
+(BOOL)isPublishPermission:(id)arg1 ;
+(BOOL)dictionary:(id)arg1 setJSONStringForObject:(id)arg2 forKey:(id)arg3 error:(id*)arg4 ;
+(id)validateRequiredClientAccessToken;
+(Class)resolveBoltsClassWithName:(id)arg1 ;
+(BOOL)isFacebookBundleIdentifier:(id)arg1 ;
+(BOOL)isSafariBundleIdentifier:(id)arg1 ;
+(BOOL)shouldManuallyAdjustOrientation;
+(id)convertRequestValue:(id)arg1 ;
+(SCD_Struct_FB33)operatingSystemVersion;
+(id)viewControllerForView:(id)arg1 ;
+(id)appURLScheme;
-(id)init;
@end

