/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <UIKit/UIView.h>

@class UIView, UIColor;

@interface FBSDKLikeBoxBorderView : UIView {

	double _borderCornerRadius;
	double _borderWidth;
	unsigned long long _caretPosition;
	UIView* _contentView;
	UIColor* _fillColor;
	UIColor* _foregroundColor;

}

@property (assign,nonatomic) double borderCornerRadius;                     //@synthesize borderCornerRadius=_borderCornerRadius - In the implementation block
@property (assign,nonatomic) double borderWidth;                            //@synthesize borderWidth=_borderWidth - In the implementation block
@property (assign,nonatomic) unsigned long long caretPosition;              //@synthesize caretPosition=_caretPosition - In the implementation block
@property (nonatomic,readonly) UIEdgeInsets contentInsets; 
@property (nonatomic,retain) UIView * contentView;                          //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic,retain) UIColor * fillColor;                           //@synthesize fillColor=_fillColor - In the implementation block
@property (nonatomic,retain) UIColor * foregroundColor;                     //@synthesize foregroundColor=_foregroundColor - In the implementation block
-(void)_initializeContent;
-(UIEdgeInsets)_borderInsets;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setBackgroundColor:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(UIEdgeInsets)contentInsets;
-(UIView *)contentView;
-(void)setContentView:(UIView *)arg1 ;
-(CGSize)intrinsicContentSize;
-(void)setBorderWidth:(double)arg1 ;
-(void)setFillColor:(UIColor *)arg1 ;
-(UIColor *)fillColor;
-(double)borderWidth;
-(UIColor *)foregroundColor;
-(void)setForegroundColor:(UIColor *)arg1 ;
-(void)setCaretPosition:(unsigned long long)arg1 ;
-(unsigned long long)caretPosition;
-(double)borderCornerRadius;
-(void)setBorderCornerRadius:(double)arg1 ;
@end

