/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSFileManager, NSURL;

@interface FBSDKAudioResourceLoader : NSObject {

	NSFileManager* _fileManager;
	NSURL* _fileURL;
	unsigned _systemSoundID;

}
+(id)name;
+(id)data;
+(unsigned long long)version;
+(id)sharedLoader;
-(BOOL)loadSound:(id*)arg1 ;
-(id)_fileURL:(id*)arg1 ;
-(void)dealloc;
-(id)init;
-(void)playSound;
@end

