/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKTypeUtility : NSObject
+(id)stringValue:(id)arg1 ;
+(id)objectValue:(id)arg1 ;
+(id)URLValue:(id)arg1 ;
+(BOOL)boolValue:(id)arg1 ;
+(unsigned long long)unsignedIntegerValue:(id)arg1 ;
+(id)dictionaryValue:(id)arg1 ;
+(id)arrayValue:(id)arg1 ;
+(long long)integerValue:(id)arg1 ;
+(double)timeIntervalValue:(id)arg1 ;
+(id)_objectValue:(id)arg1 ofClass:(Class)arg2 ;
-(id)init;
@end

