/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBSDKShareOpenGraphValueContaining <NSObject,NSSecureCoding>
@required
-(id)photoForKey:(id)arg1;
-(void)setPhoto:(id)arg1 forKey:(id)arg2;
-(id)URLForKey:(id)arg1;
-(id)objectForKeyedSubscript:(id)arg1;
-(void)enumerateKeysAndObjectsUsingBlock:(/*^block*/id)arg1;
-(id)objectForKey:(id)arg1;
-(void)removeObjectForKey:(id)arg1;
-(void)setObject:(id)arg1 forKey:(id)arg2;
-(id)stringForKey:(id)arg1;
-(id)objectEnumerator;
-(id)keyEnumerator;
-(void)setString:(id)arg1 forKey:(id)arg2;
-(void)setURL:(id)arg1 forKey:(id)arg2;
-(id)arrayForKey:(id)arg1;
-(id)numberForKey:(id)arg1;
-(void)setNumber:(id)arg1 forKey:(id)arg2;
-(void)setArray:(id)arg1 forKey:(id)arg2;
-(void)parseProperties:(id)arg1;

@end

