/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableSet, NSString;

@interface FBSDKViewImpressionTracker : NSObject {

	NSMutableSet* _trackedImpressions;
	NSString* _eventName;

}

@property (nonatomic,copy,readonly) NSString * eventName;              //@synthesize eventName=_eventName - In the implementation block
+(id)impressionTrackerWithEventName:(id)arg1 ;
-(void)logImpressionWithIdentifier:(id)arg1 parameters:(id)arg2 ;
-(id)initWithEventName:(id)arg1 ;
-(void)dealloc;
-(NSString *)eventName;
-(void)_applicationDidEnterBackgroundNotification:(id)arg1 ;
@end

