/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSMutableDictionary;

@interface FBSDKLikeActionControllerCache : NSObject <NSSecureCoding> {

	NSString* _accessTokenString;
	NSMutableDictionary* _items;

}

@property (nonatomic,copy,readonly) NSString * accessTokenString;              //@synthesize accessTokenString=_accessTokenString - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)initWithAccessTokenString:(id)arg1 ;
-(void)resetForAccessTokenString:(id)arg1 ;
-(NSString *)accessTokenString;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(id)objectForKeyedSubscript:(id)arg1 ;
-(void)setObject:(id)arg1 forKeyedSubscript:(id)arg2 ;
-(void)_prune;
@end

