/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSMutableDictionary, NSError;

@interface FBSDKLoginManagerLogger : NSObject {

	NSString* _identifier;
	NSMutableDictionary* _extras;
	NSString* _lastResult;
	NSError* _lastError;
	NSString* _authMethod;

}
+(id)loggerFromParameters:(id)arg1 ;
-(void)endLoginWithResult:(id)arg1 error:(id)arg2 ;
-(void)startSessionForLoginManager:(id)arg1 ;
-(void)startAuthMethod:(id)arg1 ;
-(void)willAttemptAppSwitchingBehavior;
-(id)parametersWithTimeStampAndClientState:(id)arg1 forAuthMethod:(id)arg2 ;
-(void)systemAuthDidShowDialog:(BOOL)arg1 isUnTOSedDevice:(BOOL)arg2 ;
-(id)_parametersForNewEvent;
-(void)logEvent:(id)arg1 params:(id)arg2 ;
-(void)logEvent:(id)arg1 result:(id)arg2 error:(id)arg3 ;
-(id)clientStateForAuthMethod:(id)arg1 andExistingState:(id)arg2 ;
-(id)init;
-(void)endSession;
@end

