/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKAppEventsUtility : NSObject
+(id)activityParametersDictionaryForEvent:(id)arg1 implicitEventsOnly:(BOOL)arg2 shouldAccessAdvertisingID:(BOOL)arg3 ;
+(void)ensureOnMainThread:(id)arg1 className:(id)arg2 ;
+(long long)unixTimeNow;
+(id)persistenceFilePath:(id)arg1 ;
+(id)anonymousID;
+(id)retrievePersistedAnonymousID;
+(void)persistAnonymousID:(id)arg1 ;
+(BOOL)matchString:(id)arg1 firstCharacterSet:(id)arg2 restOfStringCharacterSet:(id)arg3 ;
+(BOOL)regexValidateIdentifier:(id)arg1 ;
+(void)clearLibraryFiles;
+(BOOL)validateIdentifier:(id)arg1 ;
+(void)logAndNotify:(id)arg1 ;
+(id)tokenStringToUseFor:(id)arg1 ;
+(id)flushReasonToString:(unsigned long long)arg1 ;
+(void)logAndNotify:(id)arg1 allowLogAsDeveloperError:(BOOL)arg2 ;
+(unsigned long long)advertisingTrackingStatus;
+(id)advertiserID;
+(id)attributionID;
-(id)init;
@end

