/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol FBSDKLiking <NSObject>
@property (nonatomic,copy) NSString * objectID; 
@property (assign,nonatomic) unsigned long long objectType; 
@required
-(void)setObjectID:(id)arg1;
-(NSString *)objectID;
-(void)setObjectType:(unsigned long long)arg1;
-(unsigned long long)objectType;

@end

