/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKSettings : NSObject
+(void)setAppURLSchemeSuffix:(id)arg1 ;
+(void)setUserAgentSuffix:(id)arg1 ;
+(void)setLimitEventAndDataUsage:(BOOL)arg1 ;
+(id)appURLSchemeSuffix;
+(BOOL)isGraphErrorRecoveryDisabled;
+(id)graphAPIDebugParamValue;
+(void)setGraphErrorRecoveryDisabled:(BOOL)arg1 ;
+(id)accessTokenCache;
+(id)legacyUserDefaultTokenInformationKeyName;
+(id)_JPEGCompressionQualityNumber;
+(void)_setJPEGCompressionQualityNumber:(id)arg1 ;
+(void)updateGraphAPIDebugBehavior;
+(id)loggingBehavior;
+(void)setClientToken:(id)arg1 ;
+(id)facebookDomainPart;
+(void)setFacebookDomainPart:(id)arg1 ;
+(double)JPEGCompressionQuality;
+(void)setJPEGCompressionQuality:(double)arg1 ;
+(BOOL)limitEventAndDataUsage;
+(void)setLoggingBehavior:(id)arg1 ;
+(void)enableLoggingBehavior:(id)arg1 ;
+(void)disableLoggingBehavior:(id)arg1 ;
+(void)setLegacyUserDefaultTokenInformationKeyName:(id)arg1 ;
+(id)userAgentSuffix;
+(void)initialize;
+(id)displayName;
+(void)setDisplayName:(id)arg1 ;
+(void)setAppID:(id)arg1 ;
+(id)clientToken;
+(id)sdkVersion;
+(id)appID;
-(void)setAccessTokenCache:(id)arg1 ;
-(id)init;
@end

