/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIWebViewDelegate.h>

@protocol FBSDKWebDialogViewDelegate;
@class UIButton, UIActivityIndicatorView, UIWebView, NSString;

@interface FBSDKWebDialogView : UIView <UIWebViewDelegate> {

	UIButton* _closeButton;
	UIActivityIndicatorView* _loadingView;
	UIWebView* _webView;
	id<FBSDKWebDialogViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBSDKWebDialogViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_close:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setDelegate:(id<FBSDKWebDialogViewDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id<FBSDKWebDialogViewDelegate>)delegate;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(void)stopLoading;
-(void)loadURL:(id)arg1 ;
@end

