/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FBSDKLikeDialogDelegate.h>
#import <libobjc.A.dylib/NSDiscardableContent.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class FBSDKAccessToken, NSMapTable, NSString, NSDate;

@interface FBSDKLikeActionController : NSObject <FBSDKLikeDialogDelegate, NSDiscardableContent, NSSecureCoding> {

	FBSDKAccessToken* _accessToken;
	unsigned long long _contentAccessCount;
	BOOL _contentDiscarded;
	NSMapTable* _dialogToAnalyticsParametersMap;
	NSMapTable* _dialogToUpdateBlockMap;
	NSString* _likeCountStringWithLike;
	NSString* _likeCountStringWithoutLike;
	BOOL _objectIsLikedIsPending;
	BOOL _objectIsLikedOnServer;
	BOOL _objectIsPage;
	unsigned long long _refreshState;
	NSString* _socialSentenceWithLike;
	NSString* _socialSentenceWithoutLike;
	NSString* _unlikeToken;
	NSString* _verifiedObjectID;
	BOOL _objectIsLiked;
	NSDate* _lastUpdateTime;
	NSString* _objectID;
	unsigned long long _objectType;

}

@property (nonatomic,copy,readonly) NSDate * lastUpdateTime;                 //@synthesize lastUpdateTime=_lastUpdateTime - In the implementation block
@property (nonatomic,copy,readonly) NSString * likeCountString; 
@property (nonatomic,copy,readonly) NSString * objectID;                     //@synthesize objectID=_objectID - In the implementation block
@property (nonatomic,readonly) unsigned long long objectType;                //@synthesize objectType=_objectType - In the implementation block
@property (nonatomic,readonly) BOOL objectIsLiked;                           //@synthesize objectIsLiked=_objectIsLiked - In the implementation block
@property (nonatomic,copy,readonly) NSString * socialSentence; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_cacheFileURL;
+(void)_accessTokenDidChangeNotification:(id)arg1 ;
+(id)likeActionControllerForObjectID:(id)arg1 objectType:(unsigned long long)arg2 ;
+(BOOL)supportsSecureCoding;
+(void)initialize;
+(void)_applicationWillResignActiveNotification:(id)arg1 ;
+(BOOL)isDisabled;
-(void)likeDialog:(id)arg1 didFailWithError:(id)arg2 ;
-(void)likeDialog:(id)arg1 didCompleteWithResults:(id)arg2 ;
-(id)initWithObjectID:(id)arg1 objectType:(unsigned long long)arg2 accessToken:(id)arg3 ;
-(void)_refreshWithMode:(unsigned long long)arg1 ;
-(void)_setExecuting:(BOOL)arg1 forKey:(id)arg2 ;
-(BOOL)_useOGLike;
-(void)_updateWithObjectIsLiked:(long long)arg1 likeCountStringWithLike:(id)arg2 likeCountStringWithoutLike:(id)arg3 socialSentenceWithLike:(id)arg4 socialSentenceWithoutLike:(id)arg5 unlikeToken:(id)arg6 soundEnabled:(BOOL)arg7 animated:(BOOL)arg8 deferred:(BOOL)arg9 ;
-(void)_publishLikeWithUpdateBlock:(/*^block*/id)arg1 analyticsParameters:(id)arg2 fromViewController:(id)arg3 ;
-(void)_presentLikeDialogWithUpdateBlock:(/*^block*/id)arg1 analyticsParameters:(id)arg2 fromViewController:(id)arg3 ;
-(void)_publishUnlikeWithUpdateBlock:(/*^block*/id)arg1 analyticsParameters:(id)arg2 fromViewController:(id)arg3 ;
-(BOOL)objectIsLiked;
-(void)_publishIfNeededWithUpdateBlock:(/*^block*/id)arg1 analyticsParameters:(id)arg2 fromViewController:(id)arg3 ;
-(void)_ensureVerifiedObjectID:(/*^block*/id)arg1 ;
-(NSString *)likeCountString;
-(NSString *)socialSentence;
-(void)toggleLikeWithSoundEnabled:(BOOL)arg1 analyticsParameters:(id)arg2 fromViewController:(id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(BOOL)beginContentAccess;
-(void)endContentAccess;
-(void)discardContentIfPossible;
-(BOOL)isContentDiscarded;
-(void)_configure;
-(NSDate *)lastUpdateTime;
-(void)refresh;
-(NSString *)objectID;
-(unsigned long long)objectType;
@end

