/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FBSDKButton.h>
#import <Super Mario Run/FBSDKButtonImpressionTracking.h>
#import <Super Mario Run/FBSDKLiking.h>

@class FBSDKLikeActionController, NSString;

@interface FBSDKLikeButton : FBSDKButton <FBSDKButtonImpressionTracking, FBSDKLiking> {

	BOOL _isExplicitlyDisabled;
	FBSDKLikeActionController* _likeActionController;
	NSString* _objectID;
	unsigned long long _objectType;
	BOOL _soundEnabled;

}

@property (nonatomic,retain) FBSDKLikeActionController * likeActionController; 
@property (assign,getter=isSoundEnabled,nonatomic) BOOL soundEnabled;                       //@synthesize soundEnabled=_soundEnabled - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) NSString * objectID; 
@property (assign,nonatomic) unsigned long long objectType; 
+(void)initialize;
-(id)analyticsParameters;
-(id)impressionTrackingEventName;
-(id)impressionTrackingIdentifier;
-(void)configureButton;
-(BOOL)isImplicitlyDisabled;
-(void)_ensureLikeActionController:(BOOL)arg1 ;
-(void)_setLikeActionController:(id)arg1 ;
-(void)_resetLikeActionController;
-(BOOL)isSoundEnabled;
-(void)setSoundEnabled:(BOOL)arg1 ;
-(void)_likeActionControllerDidDisableNotification:(id)arg1 ;
-(void)_likeActionControllerDidResetNotification:(id)arg1 ;
-(void)_likeActionControllerDidUpdateNotification:(id)arg1 ;
-(void)setLikeActionController:(FBSDKLikeActionController *)arg1 ;
-(FBSDKLikeActionController *)likeActionController;
-(void)_like:(id)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)_setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setObjectID:(NSString *)arg1 ;
-(void)_handleTap:(id)arg1 ;
-(NSString *)objectID;
-(void)setObjectType:(unsigned long long)arg1 ;
-(unsigned long long)objectType;
@end

