/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FBSDKWebDialogDelegate.h>

@protocol FBSDKAppGroupAddDialogDelegate;
@class FBSDKWebDialog, FBSDKAppGroupContent, NSString;

@interface FBSDKAppGroupAddDialog : NSObject <FBSDKWebDialogDelegate> {

	FBSDKWebDialog* _webDialog;
	id<FBSDKAppGroupAddDialogDelegate> _delegate;
	FBSDKAppGroupContent* _content;

}

@property (assign,nonatomic,__weak) id<FBSDKAppGroupAddDialogDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) FBSDKAppGroupContent * content;                                    //@synthesize content=_content - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)showWithContent:(id)arg1 delegate:(id)arg2 ;
-(BOOL)canShow;
-(void)_handleCompletionWithDialogResults:(id)arg1 error:(id)arg2 ;
-(void)webDialog:(id)arg1 didCompleteWithResults:(id)arg2 ;
-(void)webDialog:(id)arg1 didFailWithError:(id)arg2 ;
-(void)webDialogDidCancel:(id)arg1 ;
-(BOOL)show;
-(void)setDelegate:(id<FBSDKAppGroupAddDialogDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<FBSDKAppGroupAddDialogDelegate>)delegate;
-(FBSDKAppGroupContent *)content;
-(BOOL)validateWithError:(id*)arg1 ;
-(void)setContent:(FBSDKAppGroupContent *)arg1 ;
@end

