/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKLoginError : NSObject
+(id)errorFromReturnURLParameters:(id)arg1 ;
+(id)errorFromServerError:(id)arg1 ;
+(id)errorForSystemPasswordChange:(id)arg1 ;
+(id)errorForSystemAccountStoreError:(id)arg1 ;
+(id)errorForFailedLoginWithCode:(long long)arg1 innerError:(id)arg2 ;
+(id)errorWithSystemAccountStoreDeniedError:(id)arg1 isCancellation:(BOOL*)arg2 ;
+(id)errorForFailedLoginWithCode:(long long)arg1 ;
+(id)errorDomain;
-(id)init;
@end

