/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <UIKit/UIButton.h>

@interface FBSDKButton : UIButton {

	BOOL _skipIntrinsicContentSizing;
	BOOL _isExplicitlyDisabled;

}
-(void)checkImplicitlyDisabled;
-(void)configureWithIcon:(id)arg1 title:(id)arg2 backgroundColor:(id)arg3 highlightedColor:(id)arg4 ;
-(void)logTapEventWithEventName:(id)arg1 parameters:(id)arg2 ;
-(void)configureButton;
-(BOOL)isImplicitlyDisabled;
-(void)configureWithIcon:(id)arg1 title:(id)arg2 backgroundColor:(id)arg3 highlightedColor:(id)arg4 selectedTitle:(id)arg5 selectedIcon:(id)arg6 selectedColor:(id)arg7 selectedHighlightedColor:(id)arg8 ;
-(CGSize)sizeThatFits:(CGSize)arg1 title:(id)arg2 ;
-(double)_heightForContentRect:(CGRect)arg1 ;
-(double)_marginForHeight:(double)arg1 ;
-(double)_paddingForHeight:(double)arg1 ;
-(id)defaultIcon;
-(void)_configureWithIcon:(id)arg1 title:(id)arg2 backgroundColor:(id)arg3 highlightedColor:(id)arg4 selectedTitle:(id)arg5 selectedIcon:(id)arg6 selectedColor:(id)arg7 selectedHighlightedColor:(id)arg8 ;
-(double)_heightForFont:(id)arg1 ;
-(double)_textPaddingCorrectionForHeight:(double)arg1 ;
-(id)_backgroundImageWithColor:(id)arg1 cornerRadius:(double)arg2 scale:(double)arg3 ;
-(double)_fontSizeForHeight:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setEnabled:(BOOL)arg1 ;
-(void)awakeFromNib;
-(void)sizeToFit;
-(CGSize)intrinsicContentSize;
-(id)defaultFont;
-(void)_applicationDidBecomeActiveNotification:(id)arg1 ;
-(CGRect)titleRectForContentRect:(CGRect)arg1 ;
-(CGRect)imageRectForContentRect:(CGRect)arg1 ;
-(id)defaultBackgroundColor;
-(id)defaultHighlightedColor;
-(id)defaultSelectedColor;
-(id)defaultDisabledColor;
@end

