/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKLoginManagerSystemAccountState : NSObject {

	BOOL _didShowDialog;
	BOOL _reauthorize;
	BOOL _unTOSedDevice;

}

@property (assign,nonatomic) BOOL didShowDialog;                                     //@synthesize didShowDialog=_didShowDialog - In the implementation block
@property (assign,getter=isReauthorize,nonatomic) BOOL reauthorize;                  //@synthesize reauthorize=_reauthorize - In the implementation block
@property (assign,getter=isUnTOSedDevice,nonatomic) BOOL unTOSedDevice;              //@synthesize unTOSedDevice=_unTOSedDevice - In the implementation block
-(void)setDidShowDialog:(BOOL)arg1 ;
-(void)setReauthorize:(BOOL)arg1 ;
-(void)setUnTOSedDevice:(BOOL)arg1 ;
-(BOOL)isReauthorize;
-(BOOL)isUnTOSedDevice;
-(BOOL)didShowDialog;
@end

