/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <Super Mario Run/FBSDKCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSURL, NSString;

@interface FBSDKAppInviteContent : NSObject <FBSDKCopying, NSSecureCoding> {

	NSURL* _appInvitePreviewImageURL;
	NSURL* _appLinkURL;
	NSString* _promotionCode;
	NSString* _promotionText;
	unsigned long long _destination;

}

@property (nonatomic,copy) NSURL * appInvitePreviewImageURL;              //@synthesize appInvitePreviewImageURL=_appInvitePreviewImageURL - In the implementation block
@property (nonatomic,copy) NSURL * appLinkURL;                            //@synthesize appLinkURL=_appLinkURL - In the implementation block
@property (nonatomic,copy) NSURL * previewImageURL; 
@property (nonatomic,copy) NSString * promotionCode;                      //@synthesize promotionCode=_promotionCode - In the implementation block
@property (nonatomic,copy) NSString * promotionText;                      //@synthesize promotionText=_promotionText - In the implementation block
@property (assign) unsigned long long destination;                        //@synthesize destination=_destination - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)supportsSecureCoding;
-(void)setAppLinkURL:(NSURL *)arg1 ;
-(void)setAppInvitePreviewImageURL:(NSURL *)arg1 ;
-(NSURL *)appLinkURL;
-(NSURL *)appInvitePreviewImageURL;
-(NSString *)promotionText;
-(NSString *)promotionCode;
-(BOOL)isEqualToAppInviteContent:(id)arg1 ;
-(void)setPreviewImageURL:(NSURL *)arg1 ;
-(void)setPromotionCode:(NSString *)arg1 ;
-(void)setPromotionText:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned long long)destination;
-(void)setDestination:(unsigned long long)arg1 ;
-(NSURL *)previewImageURL;
@end

