/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FBSDKAppGroupAddDialogDelegate.h>
#import <Super Mario Run/FBSDKAppGroupJoinDialogDelegate.h>
#import <Super Mario Run/FBSDKGameRequestDialogDelegate.h>
#import <Super Mario Run/FBSDKSharingDelegate.h>
#import <Super Mario Run/FBSDKAppInviteDialogDelegate.h>

@class NSString;

@interface FBUnitySDKDelegate : NSObject <FBSDKAppGroupAddDialogDelegate, FBSDKAppGroupJoinDialogDelegate, FBSDKGameRequestDialogDelegate, FBSDKSharingDelegate, FBSDKAppInviteDialogDelegate> {

	int _requestID;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)instanceWithRequestID:(int)arg1 ;
+(void)initialize;
-(void)appGroupAddDialog:(id)arg1 didCompleteWithResults:(id)arg2 ;
-(void)appGroupAddDialog:(id)arg1 didFailWithError:(id)arg2 ;
-(void)appGroupAddDialogDidCancel:(id)arg1 ;
-(void)appGroupJoinDialog:(id)arg1 didCompleteWithResults:(id)arg2 ;
-(void)appGroupJoinDialog:(id)arg1 didFailWithError:(id)arg2 ;
-(void)appGroupJoinDialogDidCancel:(id)arg1 ;
-(void)gameRequestDialog:(id)arg1 didCompleteWithResults:(id)arg2 ;
-(void)gameRequestDialog:(id)arg1 didFailWithError:(id)arg2 ;
-(void)gameRequestDialogDidCancel:(id)arg1 ;
-(void)sharer:(id)arg1 didCompleteWithResults:(id)arg2 ;
-(void)sharer:(id)arg1 didFailWithError:(id)arg2 ;
-(void)sharerDidCancel:(id)arg1 ;
-(void)appInviteDialog:(id)arg1 didCompleteWithResults:(id)arg2 ;
-(void)appInviteDialog:(id)arg1 didFailWithError:(id)arg2 ;
-(void)complete;
@end

