/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString;

@interface FIR_CLEARCUTIosClientInfo : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasClientId; 
@property (nonatomic,retain) NSString * clientId; 
@property (assign,nonatomic) BOOL hasLoggingId; 
@property (nonatomic,retain) NSString * loggingId; 
@property (assign,nonatomic) BOOL hasOsMajorVersion; 
@property (nonatomic,retain) NSString * osMajorVersion; 
@property (assign,nonatomic) BOOL hasOsFullVersion; 
@property (nonatomic,retain) NSString * osFullVersion; 
@property (assign,nonatomic) BOOL hasApplicationBuild; 
@property (nonatomic,retain) NSString * applicationBuild; 
@property (assign,nonatomic) BOOL hasCountry; 
@property (nonatomic,retain) NSString * country; 
@property (assign,nonatomic) BOOL hasModel; 
@property (nonatomic,retain) NSString * model; 
@property (assign,nonatomic) BOOL hasLanguageCode; 
@property (nonatomic,retain) NSString * languageCode; 
+(id)descriptor;
-(id)setOsFullVersion:(NSString *)arg1 ;
-(id)setApplicationBuild:(NSString *)arg1 ;
@end

