/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, NSData;

@interface FIR_CLEARCUTAndroidClientInfo : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasAndroidId; 
@property (assign,nonatomic) long long androidId; 
@property (assign,nonatomic) BOOL hasLoggingId; 
@property (nonatomic,retain) NSString * loggingId; 
@property (assign,nonatomic) BOOL hasDeviceId; 
@property (assign,nonatomic) long long deviceId; 
@property (assign,nonatomic) BOOL hasSdkVersion; 
@property (assign,nonatomic) int sdkVersion; 
@property (assign,nonatomic) BOOL hasModel; 
@property (nonatomic,retain) NSString * model; 
@property (assign,nonatomic) BOOL hasProduct; 
@property (nonatomic,retain) NSString * product; 
@property (assign,nonatomic) BOOL hasHardware; 
@property (nonatomic,retain) NSString * hardware; 
@property (assign,nonatomic) BOOL hasDevice; 
@property (nonatomic,retain) NSString * device; 
@property (assign,nonatomic) BOOL hasOsBuild; 
@property (nonatomic,retain) NSString * osBuild; 
@property (assign,nonatomic) BOOL hasApplicationBuild; 
@property (nonatomic,retain) NSString * applicationBuild; 
@property (assign,nonatomic) BOOL hasMccMnc; 
@property (nonatomic,retain) NSString * mccMnc; 
@property (assign,nonatomic) BOOL hasLocale; 
@property (nonatomic,retain) NSString * locale; 
@property (assign,nonatomic) BOOL hasCountry; 
@property (nonatomic,retain) NSString * country; 
@property (assign,nonatomic) BOOL hasManufacturer; 
@property (nonatomic,retain) NSString * manufacturer; 
@property (assign,nonatomic) BOOL hasBrand; 
@property (nonatomic,retain) NSString * brand; 
@property (assign,nonatomic) BOOL hasBoard; 
@property (nonatomic,retain) NSString * board; 
@property (assign,nonatomic) BOOL hasRadioVersion; 
@property (nonatomic,retain) NSString * radioVersion; 
@property (assign,nonatomic) BOOL hasFingerprint; 
@property (nonatomic,retain) NSString * fingerprint; 
@property (assign,nonatomic) BOOL hasGmsCoreVersionCode; 
@property (assign,nonatomic) int gmsCoreVersionCode; 
@property (assign,nonatomic) BOOL hasIsSidewinderDevice; 
@property (assign,nonatomic) BOOL isSidewinderDevice; 
@property (assign,nonatomic) BOOL hasChimeraConfigInfo; 
@property (nonatomic,retain) NSData * chimeraConfigInfo; 
+(id)descriptor;
@end

