/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, GSDK_PBMutableArray, NSData, FIR_CLEARCUTAppUsage1pLogEvent, FIR_CLEARCUTActiveExperiments, FIR_CLEARCUTExperimentIds, FIR_CLEARCUTNetworkConnectionInfo;

@interface FIR_CLEARCUTLogEvent : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasEventTimeMs; 
@property (assign,nonatomic) long long eventTimeMs; 
@property (assign,nonatomic) BOOL hasEventUptimeMs; 
@property (assign,nonatomic) long long eventUptimeMs; 
@property (assign,nonatomic) BOOL hasSequencePosition; 
@property (assign,nonatomic) long long sequencePosition; 
@property (assign,nonatomic) BOOL hasTag; 
@property (nonatomic,retain) NSString * tag; 
@property (assign,nonatomic) BOOL hasEventCode; 
@property (assign,nonatomic) int eventCode; 
@property (assign,nonatomic) BOOL hasEventFlowId; 
@property (assign,nonatomic) int eventFlowId; 
@property (assign,nonatomic) BOOL hasIsUserInitiated; 
@property (assign,nonatomic) BOOL isUserInitiated; 
@property (assign,nonatomic) BOOL hasValueArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * valueArray; 
@property (assign,nonatomic) BOOL hasStore; 
@property (nonatomic,retain) NSData * store; 
@property (assign,nonatomic) BOOL hasAppUsage1P; 
@property (nonatomic,retain) FIR_CLEARCUTAppUsage1pLogEvent * appUsage1P; 
@property (assign,nonatomic) BOOL hasSourceExtension; 
@property (nonatomic,retain) NSData * sourceExtension; 
@property (assign,nonatomic) BOOL hasSourceExtensionJs; 
@property (nonatomic,retain) NSString * sourceExtensionJs; 
@property (assign,nonatomic) BOOL hasSourceExtensionJson; 
@property (nonatomic,retain) NSString * sourceExtensionJson; 
@property (assign,nonatomic) BOOL hasExp; 
@property (nonatomic,retain) FIR_CLEARCUTActiveExperiments * exp; 
@property (assign,nonatomic) BOOL hasTestId; 
@property (nonatomic,retain) NSString * testId; 
@property (assign,nonatomic) BOOL hasTimezoneOffsetSeconds; 
@property (assign,nonatomic) long long timezoneOffsetSeconds; 
@property (assign,nonatomic) BOOL hasExperimentIds; 
@property (nonatomic,retain) FIR_CLEARCUTExperimentIds * experimentIds; 
@property (assign,nonatomic) BOOL hasClientVe; 
@property (nonatomic,retain) NSData * clientVe; 
@property (assign,nonatomic) BOOL hasClientVeJs; 
@property (nonatomic,retain) NSString * clientVeJs; 
@property (assign,nonatomic) BOOL hasInternalEvent; 
@property (assign,nonatomic) int internalEvent; 
@property (assign,nonatomic) BOOL hasTestCodeArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * testCodeArray; 
@property (assign,nonatomic) BOOL hasBootCount; 
@property (assign,nonatomic) long long bootCount; 
@property (assign,nonatomic) BOOL hasNetworkConnectionInfo; 
@property (nonatomic,retain) FIR_CLEARCUTNetworkConnectionInfo * networkConnectionInfo; 
+(id)descriptor;
-(id)setEventUptimeMs:(long long)arg1 ;
-(BOOL)hasEventUptimeMs;
-(id)setEventTimeMs:(long long)arg1 ;
-(BOOL)hasEventTimeMs;
-(id)setSourceExtension:(NSData *)arg1 ;
@end

