/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class FIR_CLEARCUTClientInfo, NSString, GSDK_PBMutableArray, FIR_CLEARCUTDeviceStatus, FIR_CLEARCUTExternalTimestamp;

@interface FIR_CLEARCUTLogRequest : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasRequestTimeMs; 
@property (assign,nonatomic) long long requestTimeMs; 
@property (assign,nonatomic) BOOL hasRequestUptimeMs; 
@property (assign,nonatomic) long long requestUptimeMs; 
@property (assign,nonatomic) BOOL hasClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTClientInfo * clientInfo; 
@property (assign,nonatomic) BOOL hasLogSource; 
@property (assign,nonatomic) int logSource; 
@property (assign,nonatomic) BOOL hasLogSourceName; 
@property (nonatomic,retain) NSString * logSourceName; 
@property (assign,nonatomic) BOOL hasZwiebackCookie; 
@property (nonatomic,retain) NSString * zwiebackCookie; 
@property (assign,nonatomic) BOOL hasLogEventArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * logEventArray; 
@property (assign,nonatomic) BOOL hasSerializedLogEventsArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * serializedLogEventsArray; 
@property (assign,nonatomic) BOOL hasQosTier; 
@property (assign,nonatomic) int qosTier; 
@property (assign,nonatomic) BOOL hasScheduler; 
@property (assign,nonatomic) int scheduler; 
@property (assign,nonatomic) BOOL hasDeviceStatus; 
@property (nonatomic,retain) FIR_CLEARCUTDeviceStatus * deviceStatus; 
@property (assign,nonatomic) BOOL hasExternalTimestamp; 
@property (nonatomic,retain) FIR_CLEARCUTExternalTimestamp * externalTimestamp; 
+(id)descriptor;
-(id)setRequestUptimeMs:(long long)arg1 ;
-(id)setRequestTimeMs:(long long)arg1 ;
-(id)setZwiebackCookie:(NSString *)arg1 ;
-(id)setClientInfo:(FIR_CLEARCUTClientInfo *)arg1 ;
-(GSDK_PBMutableArray *)serializedLogEventsArray;
-(id)setLogSource:(int)arg1 ;
@end

