/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, FIR_CLEARCUTAndroidClientInfo, FIR_CLEARCUTDesktopClientInfo, FIR_CLEARCUTIosClientInfo, FIR_CLEARCUTPlayCeClientInfo, FIR_CLEARCUTVrClientInfo, FIR_CLEARCUTPancettaClientInfo, FIR_CLEARCUTBrowserInfo, FIR_CLEARCUTJsClientInfo;

@interface FIR_CLEARCUTClientInfo : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasClientType; 
@property (assign,nonatomic) int clientType; 
@property (assign,nonatomic) BOOL hasRemoteHost; 
@property (nonatomic,retain) NSString * remoteHost; 
@property (assign,nonatomic) BOOL hasRemoteHost6; 
@property (nonatomic,retain) NSString * remoteHost6; 
@property (assign,nonatomic) BOOL hasAndroidClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTAndroidClientInfo * androidClientInfo; 
@property (assign,nonatomic) BOOL hasDesktopClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTDesktopClientInfo * desktopClientInfo; 
@property (assign,nonatomic) BOOL hasIosClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTIosClientInfo * iosClientInfo; 
@property (assign,nonatomic) BOOL hasPlayCeClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTPlayCeClientInfo * playCeClientInfo; 
@property (assign,nonatomic) BOOL hasVrClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTVrClientInfo * vrClientInfo; 
@property (assign,nonatomic) BOOL hasPancettaClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTPancettaClientInfo * pancettaClientInfo; 
@property (assign,nonatomic) BOOL hasBrowserInfo; 
@property (nonatomic,retain) FIR_CLEARCUTBrowserInfo * browserInfo; 
@property (assign,nonatomic) BOOL hasJsClientInfo; 
@property (nonatomic,retain) FIR_CLEARCUTJsClientInfo * jsClientInfo; 
+(id)descriptor;
-(id)setIosClientInfo:(FIR_CLEARCUTIosClientInfo *)arg1 ;
-(id)setClientType:(int)arg1 ;
@end

