/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FIRNetworkLoggerDelegate.h>
#import <Super Mario Run/FIRNetworkReachabilityDelegate.h>

@class FIROptions, NSString, FIRAAlarm, FIRAAudience, FIRADatabase, FIRAIdentity, FIRNetwork, FIRAPersistedConfig, FIRARemoteConfig, FIRAScheduler, FIRASessionReporter, NSArray;

@interface FIRAMeasurement : NSObject <FIRNetworkLoggerDelegate, FIRNetworkReachabilityDelegate> {

	FIROptions* _options;
	NSString* _databaseName;
	long long _initializeComponentsOnce;
	FIRAAlarm* _alarm;
	FIRAAudience* _audience;
	FIRADatabase* _database;
	FIRAIdentity* _identity;
	FIRNetwork* _network;
	FIRAPersistedConfig* _persistedConfig;
	FIRARemoteConfig* _remoteConfig;
	FIRAScheduler* _scheduler;
	FIRASessionReporter* _sessionReporter;
	NSArray* _uploadingBundleIDs;
	NSString* _previousGMPAppID;
	AQ _backgroundUpdateTask;
	double _initTimestamp;
	BOOL _isEnabled;
	BOOL _isNetworkRequestPending;
	BOOL _wasEnabledDuringInitialization;

}

@property (nonatomic,readonly) BOOL isNetworkRequestPending;                     //@synthesize isNetworkRequestPending=_isNetworkRequestPending - In the implementation block
@property (nonatomic,readonly) BOOL wasEnabledDuringInitialization;              //@synthesize wasEnabledDuringInitialization=_wasEnabledDuringInitialization - In the implementation block
@property (assign,nonatomic) BOOL isEnabled;                                     //@synthesize isEnabled=_isEnabled - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)deepLinkFromUserActivity:(id)arg1 ;
+(id)remoteConfig;
+(void)handleAppDidFinishLaunching:(id)arg1 ;
+(void)initializeSharedInstanceWithOptions:(id)arg1 ;
+(id)sharedInstance;
+(void)load;
+(id)monitor;
-(void)handleOpenURL:(id)arg1 ;
-(void)handleOpenURL:(id)arg1 clickTimestamp:(id)arg2 ;
-(void)handleDebugModeWithURL:(id)arg1 ;
-(void)handleDeepLink:(id)arg1 clickTimestamp:(id)arg2 ;
-(BOOL)isValidCampaignURLParamDictionary:(id)arg1 ;
-(id)initWithDatabaseName:(id)arg1 persistedConfigName:(id)arg2 network:(id)arg3 scheduler:(id)arg4 alarm:(id)arg5 options:(id)arg6 ;
-(BOOL)shouldEnableMeasurement:(id)arg1 ;
-(void)swapBackgroundTaskWithNewTaskID:(unsigned long long)arg1 ;
-(void)setIsEnabledOnWorkerQueue:(BOOL)arg1 ;
-(BOOL)startMeasurementOnWorkerQueue;
-(void)reportFirstOpenOnWorkerQueue;
-(void)reportAppUpdateOnWorkerQueue;
-(void)reportOSUpdateOnWorkerQueue;
-(void)handleAppDidBecomeActiveEvent:(id)arg1 ;
-(void)handleAppWillResignActiveEvent:(id)arg1 ;
-(void)handleAppWillEnterForegroundNotification:(id)arg1 ;
-(void)updateSchedule;
-(long long)timestampMillisRoundedUpToNextHour:(long long)arg1 ;
-(void)setUserAttributeOnWorkerQueue:(id)arg1 ;
-(BOOL)isAppUpdateWithAnalytics;
-(void)logEventOnWorkerQueue:(id)arg1 ;
-(void)maybeReportStoredCampaignEventWithClickTimestamp:(id)arg1 ;
-(id)fileAttributesForPath:(id)arg1 ;
-(BOOL)hasDataToUpload;
-(double)nextUploadingTime;
-(BOOL)isNetworkReadyForRequest;
-(BOOL)bundleRawEvents;
-(void)fetchRemoteConfig;
-(id)filteredBundlesWithCompatibleAppID:(id)arg1 resettableDeviceID:(id)arg2 vendorDeviceID:(id)arg3 bundlesToUpload:(id)arg4 ;
-(void)setUploadInProgressWithBundleIDs:(id)arg1 ;
-(void)networkUploadCompletionHandlerWithResponse:(id)arg1 error:(id)arg2 ;
-(BOOL)removeBundlesFromDatabaseWithIDs:(id)arg1 ;
-(void)maybeAddDebugAndRealtimeParameters:(id)arg1 ;
-(id)createRawEventMetadataWithUserAttributes:(id)arg1 ;
-(void)removeUserAttributeOnWorkerQueue:(id)arg1 ;
-(void)networkRemoteConfigFetchCompletionHandler:(id)arg1 data:(id)arg2 error:(id)arg3 ;
-(void)uploadDataOrRegisterAlarm;
-(void)firNetwork_logWithLevel:(long long)arg1 message:(id)arg2 contexts:(id)arg3 ;
-(void)firNetwork_logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3 ;
-(void)firNetwork_logWithLevel:(long long)arg1 message:(id)arg2 ;
-(void)reachabilityDidChange;
-(void)userAttributeWithName:(id)arg1 callback:(/*^block*/id)arg2 ;
-(double)firstOpenTimestamp;
-(BOOL)isNetworkRequestPending;
-(BOOL)wasEnabledDuringInitialization;
-(void)setMinimumSessionInterval:(double)arg1 ;
-(void)setSessionTimeoutInterval:(double)arg1 ;
-(void)setUserAttribute:(id)arg1 ;
-(void)removeUserAttribute:(id)arg1 ;
-(void)userPropertiesIncludingInternal:(BOOL)arg1 callback:(/*^block*/id)arg2 ;
-(void)dealloc;
-(BOOL)isEnabled;
-(void)setIsEnabled:(BOOL)arg1 ;
-(void)logEvent:(id)arg1 ;
-(id)initWithOptions:(id)arg1 ;
-(void)uploadData;
@end

