/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDecimalNumber;

@interface FIRAAudienceComparisonValues : NSObject {

	BOOL _isValid;
	NSDecimalNumber* _comparisonValue;
	NSDecimalNumber* _maxComparisonValue;
	NSDecimalNumber* _minComparisonValue;

}

@property (nonatomic,retain) NSDecimalNumber * comparisonValue;                 //@synthesize comparisonValue=_comparisonValue - In the implementation block
@property (nonatomic,retain) NSDecimalNumber * maxComparisonValue;              //@synthesize maxComparisonValue=_maxComparisonValue - In the implementation block
@property (nonatomic,retain) NSDecimalNumber * minComparisonValue;              //@synthesize minComparisonValue=_minComparisonValue - In the implementation block
@property (assign,nonatomic) BOOL isValid;                                      //@synthesize isValid=_isValid - In the implementation block
-(void)setComparisonValue:(NSDecimalNumber *)arg1 ;
-(NSDecimalNumber *)maxComparisonValue;
-(void)setMaxComparisonValue:(NSDecimalNumber *)arg1 ;
-(NSDecimalNumber *)minComparisonValue;
-(void)setMinComparisonValue:(NSDecimalNumber *)arg1 ;
-(BOOL)isValid;
-(void)setIsValid:(BOOL)arg1 ;
-(NSDecimalNumber *)comparisonValue;
@end

