/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, FIRAValue, ACPUserAttribute;

@interface FIRAUserAttribute : NSObject {

	NSString* _name;
	FIRAValue* _value;
	double _lastSetTimestamp;

}

@property (nonatomic,readonly) NSString * name;                                    //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) FIRAValue * value;                                  //@synthesize value=_value - In the implementation block
@property (nonatomic,readonly) double lastSetTimestamp;                            //@synthesize lastSetTimestamp=_lastSetTimestamp - In the implementation block
@property (nonatomic,readonly) BOOL isPublic; 
@property (nonatomic,readonly) ACPUserAttribute * protoUserAttribute; 
-(BOOL)isPublic;
-(ACPUserAttribute *)protoUserAttribute;
-(id)initWithName:(id)arg1 value:(id)arg2 lastSetTimestamp:(double)arg3 ;
-(double)lastSetTimestamp;
-(NSString *)name;
-(FIRAValue *)value;
@end

