/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FIRAValue : NSObject <NSCopying> {

	id _value;
	long long _valueType;

}

@property (nonatomic,readonly) long long valueType;                 //@synthesize valueType=_valueType - In the implementation block
@property (nonatomic,readonly) BOOL isDouble; 
@property (nonatomic,readonly) double doubleValue; 
@property (nonatomic,readonly) BOOL isInt64; 
@property (nonatomic,readonly) long long int64Value; 
@property (nonatomic,readonly) BOOL isString; 
@property (nonatomic,readonly) NSString * stringValue; 
+(id)valueFromObject:(id)arg1 ;
-(BOOL)isInt64;
-(id)initWithInt64:(long long)arg1 ;
-(BOOL)isDouble;
-(id)initWithValueType:(long long)arg1 value:(id)arg2 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(double)doubleValue;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithString:(id)arg1 ;
-(NSString *)stringValue;
-(BOOL)isString;
-(long long)valueType;
-(id)initWithDouble:(double)arg1 ;
-(long long)int64Value;
@end

