/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRASqliteStore, FIRAPersistedConfig;

@interface FIRADatabase : NSObject {

	FIRASqliteStore* _sqliteStore;
	FIRAPersistedConfig* _persistedConfig;

}
+(id)databasePathWithName:(id)arg1 ;
+(BOOL)deleteDatabaseFileWithName:(id)arg1 error:(id*)arg2 ;
-(id)eventFiltersForEventName:(id)arg1 error:(id*)arg2 ;
-(id)filterResultForAudienceID:(int)arg1 error:(id*)arg2 ;
-(BOOL)updateFilterResults:(id)arg1 error:(id*)arg2 ;
-(id)propertyFiltersForPropertyName:(id)arg1 error:(id*)arg2 ;
-(BOOL)deleteAllEventFilters:(id*)arg1 ;
-(BOOL)deleteAllPropertyFilters:(id*)arg1 ;
-(BOOL)updateEventFilters:(id)arg1 error:(id*)arg2 ;
-(BOOL)updatePropertyFilters:(id)arg1 error:(id*)arg2 ;
-(id)userAttributesIncludingInternal:(BOOL)arg1 error:(id*)arg2 ;
-(id)allFilterResults:(id*)arg1 ;
-(id)allAudienceIDs:(id*)arg1 ;
-(BOOL)deleteFilterResults:(id)arg1 error:(id*)arg2 ;
-(BOOL)ensureAllTables;
-(BOOL)initializeAppMetadata;
-(id)queryAppMetadata:(id*)arg1 ;
-(id)dictionaryFromAppMetadata:(id)arg1 ;
-(BOOL)upsertDataType:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 tableLimit:(long long)arg5 error:(id*)arg6 createDictionaryBlock:(/*^block*/id)arg7 ;
-(id)appMetadataFromDictionary:(id)arg1 ;
-(id)dataTypesFromTableWithName:(id)arg1 columnName:(id)arg2 columnValue:(id)arg3 error:(id*)arg4 createDataTypeBlock:(/*^block*/id)arg5 ;
-(BOOL)updateDataType:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 error:(id*)arg5 createDictionaryBlock:(/*^block*/id)arg6 ;
-(id)dailyCountsFromDictionary:(id)arg1 ;
-(id)dictionaryFromDailyCounts:(id)arg1 ;
-(id)queryRawEventsMetadataWithFingerprint:(long long)arg1 error:(id*)arg2 ;
-(id)dictionaryFromMeasurementBundleMetadata:(id)arg1 ;
-(id)measurementBundleFromDictionary:(id)arg1 ;
-(id)dictionaryFromRawEvent:(id)arg1 isRealtime:(BOOL)arg2 ;
-(BOOL)insertDataType:(id)arg1 inTableWithName:(id)arg2 error:(id*)arg3 createDictionaryBlock:(/*^block*/id)arg4 ;
-(id)rawEventDataFromDictionary:(id)arg1 error:(id*)arg2 ;
-(BOOL)deleteUnusedRawEventsMetadata:(id*)arg1 ;
-(id)eventFromDictionary:(id)arg1 error:(id*)arg2 ;
-(id)maybeDeleteStaleData:(id*)arg1 ;
-(id)bundleRowIDPairsWithRecords:(id)arg1 countLimit:(long long)arg2 sizeLimit:(long long)arg3 ;
-(BOOL)deleteStaleRawEventsDataOlderThanMaxAge:(double)arg1 error:(id*)arg2 ;
-(BOOL)deleteStaleBundlesOlderThanMaxAge:(double)arg1 error:(id*)arg2 ;
-(id)eventAggregatesFromDictionary:(id)arg1 ;
-(id)allDataTypesFromTableWithName:(id)arg1 tableLimit:(long long)arg2 error:(id*)arg3 createDataTypeBlock:(/*^block*/id)arg4 ;
-(id)dictionaryFromEventAggregates:(id)arg1 ;
-(id)userAttributeFromDictionary:(id)arg1 ;
-(id)dictionaryFromUserAttribute:(id)arg1 ;
-(id)filterResultFromDictionary:(id)arg1 ;
-(id)eventFilterFromDictionary:(id)arg1 ;
-(id)propertyFilterFromDictionary:(id)arg1 ;
-(id)dictionaryFromEventFilter:(id)arg1 ;
-(id)dictionaryFromPropertyFilter:(id)arg1 ;
-(id)dictionaryFromFilterResult:(id)arg1 ;
-(id)elementaryTableDefinitions;
-(id)addOnTableDefinitions;
-(id)constructCreateStatementForTableWithName:(id)arg1 columnInfo:(id)arg2 ;
-(id)constructAlterStatementForTableWithName:(id)arg1 columnInfo:(id)arg2 ;
-(id)columnNamesFromColumnInfo:(id)arg1 ;
-(id)initWithDatabaseName:(id)arg1 persistedConfig:(id)arg2 ;
-(BOOL)updateAppMetadata:(id)arg1 error:(id*)arg2 ;
-(id)dailyCounts:(id*)arg1 ;
-(BOOL)updateDailyCounts:(id)arg1 error:(id*)arg2 ;
-(BOOL)insertIfNotExistsRawEventMetadata:(id)arg1 error:(id*)arg2 ;
-(BOOL)deleteRawEventMetadataWithMetadataFingerprint:(long long)arg1 error:(id*)arg2 ;
-(id)isRawEventsTableEmpty:(id*)arg1 ;
-(BOOL)insertRawEvent:(id)arg1 metadataFingerprint:(long long)arg2 isRealtime:(BOOL)arg3 error:(id*)arg4 ;
-(id)queryLatestRawEventTime:(id*)arg1 ;
-(id)rawEventsWithMetadataFingerprint:(long long)arg1 error:(id*)arg2 eventFilter:(/*^block*/id)arg3 ;
-(id)containsRawEventWithMetadataFingerprint:(long long)arg1 error:(id*)arg2 ;
-(BOOL)deleteRawEventsWithMaxRowID:(long long)arg1 error:(id*)arg2 ;
-(id)deleteRawEventsOverAbsoluteLimit:(id*)arg1 ;
-(id)nextMetadataFingerprintToProcess:(id*)arg1 ;
-(id)containsRealtimeRawEventsWithError:(id*)arg1 ;
-(id)isQueuedBundleTableEmpty:(id*)arg1 ;
-(BOOL)insertBundle:(id)arg1 isRealtime:(BOOL)arg2 error:(id*)arg3 ;
-(id)queryBundlesWithCountLimit:(long long)arg1 sizeLimit:(long long)arg2 error:(id*)arg3 ;
-(BOOL)deleteBundlesWithRowIDs:(id)arg1 error:(id*)arg2 ;
-(id)queryLatestBundleTime:(id*)arg1 ;
-(id)containsRealtimeBundlesWithError:(id*)arg1 ;
-(id)publicEventCount:(id*)arg1 ;
-(id)allEventAggregates:(id*)arg1 ;
-(id)eventAggregatesWithName:(id)arg1 error:(id*)arg2 ;
-(BOOL)updateEventAggregates:(id)arg1 error:(id*)arg2 ;
-(id)publicUserAttributeCount:(id*)arg1 ;
-(id)containsUserAttributeWithName:(id)arg1 error:(id*)arg2 ;
-(id)userAttributeWithName:(id)arg1 error:(id*)arg2 ;
-(id)allLifetimeValueUserAttributes:(id*)arg1 ;
-(BOOL)updateUserAttribute:(id)arg1 error:(id*)arg2 ;
-(BOOL)deleteUserAttributeWithName:(id)arg1 error:(id*)arg2 ;
-(BOOL)deleteEventFilters:(id)arg1 error:(id*)arg2 ;
-(BOOL)deletePropertyFilters:(id)arg1 error:(id*)arg2 ;
-(BOOL)updateRemoteConfig:(id)arg1 error:(id*)arg2 ;
-(BOOL)updateRemoteConfigSuccessfulTimestamp:(double)arg1 error:(id*)arg2 ;
-(id)queryACPMeasurementConfigWithError:(id*)arg1 ;
-(id)lastRemoteConfigUpdateTimestamp:(id*)arg1 ;
-(BOOL)performTransaction:(/*^block*/id)arg1 ;
@end

