/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class FIRAASLLogger, FIRAMonitoringSampledData, NSObject, NSUserDefaults;

@interface FIRAMonitor : NSObject {

	long long _logLevel;
	FIRAASLLogger* _logger;
	FIRAMonitoringSampledData* _monitoringSampledData;
	NSObject*<OS_dispatch_queue> _monitorQueue;
	long long _libraryVersion;
	NSUserDefaults* _userDefaults;
	BOOL _isDebugModeEnabled;
	BOOL _encodeContexts;

}

@property (assign,nonatomic) BOOL isDebugModeEnabled;              //@synthesize isDebugModeEnabled=_isDebugModeEnabled - In the implementation block
@property (assign,nonatomic) BOOL encodeContexts;                  //@synthesize encodeContexts=_encodeContexts - In the implementation block
+(BOOL)isMonitorableLevel:(long long)arg1 ;
+(id)stringWithLogMessage:(id)arg1 logLevel:(long long)arg2 contexts:(id)arg3 encodeContexts:(BOOL)arg4 monitorLoggingTag:(id)arg5 ;
+(id)encodedStringWithContextArray:(id)arg1 insertSpaces:(BOOL)arg2 ;
+(id)encodedStringWithContextObject:(id)arg1 ;
+(id)logLevelDescriptionFromLogLevel:(long long)arg1 ;
+(id)lastFIRASymbolFromException:(id)arg1 ;
+(BOOL)isSilentLevel:(long long)arg1 ;
+(id)monitoringDataKeyWithMessage:(id)arg1 logLevel:(long long)arg2 libraryVersion:(long long)arg3 ;
-(void)logWithLevel:(long long)arg1 message:(id)arg2 ;
-(void)logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3 ;
-(void)logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3 context:(id)arg4 ;
-(void)logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3 context:(id)arg4 context:(id)arg5 ;
-(id)initWithLogLevel:(long long)arg1 logger:(id)arg2 libraryVersion:(long long)arg3 ;
-(void)loadMonitoringDataFromUserDefaults;
-(void)setIsDebugModeEnabled:(BOOL)arg1 ;
-(void)logWithLevel:(long long)arg1 message:(id)arg2 contexts:(id)arg3 ;
-(BOOL)isLoggableLevel:(long long)arg1 ;
-(void)logToConsole:(id)arg1 logLevel:(long long)arg2 ;
-(void)insertOrUpdateMonitoringDataWithMessage:(id)arg1 encodedContext:(id)arg2 logLevel:(long long)arg3 ;
-(id)monitoringDataForDispatchWithSamplePeriod:(double)arg1 lastSampledTimestamp:(double)arg2 ;
-(void)saveMonitoringDataToUserDefaults;
-(id)initWithLibraryVersion:(long long)arg1 ;
-(void)clearMonitoringData;
-(BOOL)encodeContexts;
-(void)setEncodeContexts:(BOOL)arg1 ;
-(void)setLogLevel:(long long)arg1 ;
-(BOOL)isDebugModeEnabled;
@end

