/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface FIRAMonitoringSampledData : NSObject {

	NSMutableArray* _sampledData;

}
+(BOOL)isValidUserDefaultsArrayEntry:(id)arg1 ;
+(id)sampledDataEntryWithKey:(id)arg1 timestamp:(id)arg2 context:(id)arg3 population:(id)arg4 ;
+(id)monitoringURLParamWithKey:(id)arg1 population:(id)arg2 context:(id)arg3 ;
-(id)monitoringDataForDispatchWithSamplePeriod:(double)arg1 lastSampledTimestamp:(double)arg2 ;
-(void)insertOrUpdateSampledDataWithKey:(id)arg1 encodedContext:(id)arg2 ;
-(id)sampledData;
-(id)initWithArray:(id)arg1 ;
@end

