/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FIRAnalytics : NSObject
+(void)handleOpenURL:(id)arg1 ;
+(void)createAppDelegateProxy;
+(void)maybeEnableTagManager;
+(void)dispatchAsyncOnSerialQueue:(/*^block*/id)arg1 ;
+(void)observeNotificationsForAnalyticsConfiguration:(id)arg1 ;
+(void)handleSetEnabled:(id)arg1 ;
+(void)handleSetMinimumSessionInterval:(id)arg1 ;
+(void)handleSetSessionTimeoutInterval:(id)arg1 ;
+(void)setIsAnalyticsEnabled:(BOOL)arg1 ;
+(void)logEventWithOrigin:(id)arg1 name:(id)arg2 parameters:(id)arg3 ;
+(void)logEventWithOrigin:(id)arg1 isPublicEvent:(BOOL)arg2 name:(id)arg3 parameters:(id)arg4 ;
+(void)logEventOnSerialQueueWithOrigin:(id)arg1 isPublicEvent:(BOOL)arg2 name:(id)arg3 parameters:(id)arg4 timestamp:(double)arg5 ignoreEnabled:(BOOL)arg6 ignoreInterceptor:(BOOL)arg7 ;
+(void)notifyEventListenersOnSerialQueue:(id)arg1 ;
+(void)setInternalUserProperty:(id)arg1 forName:(id)arg2 ;
+(void)removeUserAttributeForName:(id)arg1 ;
+(void)removeInternalUserAttributeForName:(id)arg1 ;
+(BOOL)isCurrentQueueSerialQueue;
+(void)startWithConfiguration:(id)arg1 options:(id)arg2 ;
+(void)logEventWithName:(id)arg1 parameters:(id)arg2 ;
+(void)logInternalEventWithOrigin:(id)arg1 name:(id)arg2 parameters:(id)arg3 ;
+(void)logEventWithOrigin:(id)arg1 isPublicEvent:(BOOL)arg2 name:(id)arg3 parameters:(id)arg4 timestamp:(double)arg5 ignoreEnabled:(BOOL)arg6 ignoreInterceptor:(BOOL)arg7 ;
+(void)setOpenURLListener:(/*^block*/id)arg1 ;
+(void)setUserPropertyString:(id)arg1 forName:(id)arg2 ;
+(void)setUserAttributeNumber:(id)arg1 forName:(id)arg2 ;
+(void)userPropertiesIncludingInternal:(BOOL)arg1 queue:(id)arg2 callback:(/*^block*/id)arg3 ;
+(void)setLogEventInterceptor:(/*^block*/id)arg1 ;
+(id)addLogEventListener:(/*^block*/id)arg1 ;
+(void)removeLogEventListener:(id)arg1 ;
+(void)notifyEventListeners:(id)arg1 ;
+(void)handleUserActivity:(id)arg1 ;
+(void)setUserID:(id)arg1 ;
+(void)handleEventsForBackgroundURLSession:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
@end

