/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSString, FIRAPersistedConfig, FIROptions, NSNumber;

@interface FIRAIdentity : NSObject {

	NSDate* _lastAppInstanceIDUpdateTimestamp;
	NSString* _hashedIDFA;
	NSString* _resettableDeviceID;
	NSString* _appInstanceID;
	BOOL _limitedAdTracking;
	NSString* _identifierForVendorString;
	FIRAPersistedConfig* _persistedConfig;
	FIROptions* _FIROptions;
	NSString* _appID;
	NSString* _appVersion;
	NSNumber* _appVersionMajor;
	NSNumber* _appVersionMinor;
	NSNumber* _appVersionRelease;
	long long _devCertHash;

}

@property (nonatomic,readonly) NSString * appID;                             //@synthesize appID=_appID - In the implementation block
@property (nonatomic,readonly) NSString * appVersion;                        //@synthesize appVersion=_appVersion - In the implementation block
@property (nonatomic,readonly) NSNumber * appVersionMajor;                   //@synthesize appVersionMajor=_appVersionMajor - In the implementation block
@property (nonatomic,readonly) NSNumber * appVersionMinor;                   //@synthesize appVersionMinor=_appVersionMinor - In the implementation block
@property (nonatomic,readonly) NSNumber * appVersionRelease;                 //@synthesize appVersionRelease=_appVersionRelease - In the implementation block
@property (nonatomic,readonly) NSString * appInstanceID; 
@property (nonatomic,readonly) NSString * resettableDeviceID; 
@property (nonatomic,readonly) BOOL hasLimitedAdTracking; 
@property (nonatomic,readonly) BOOL limitedAdTracking; 
@property (nonatomic,readonly) NSString * appIDFromGMP; 
@property (nonatomic,readonly) BOOL isFromAppStore; 
@property (nonatomic,readonly) long long libraryVersionFromGMP; 
@property (nonatomic,readonly) NSString * identifierForVendor; 
@property (nonatomic,readonly) long long devCertHash;                        //@synthesize devCertHash=_devCertHash - In the implementation block
@property (nonatomic,readonly) NSString * firebaseInstanceID; 
+(id)numericFieldsFromAppVersionNumeric:(id)arg1 ;
+(long long)formattedLibraryVersionFromFIROptions:(id)arg1 ;
+(void)notCalled;
-(BOOL)isFromAppStore;
-(id)hashedIDFA;
-(NSString *)appInstanceID;
-(id)randomAppInstanceID;
-(void)updateIdentifiers;
-(BOOL)hasLimitedAdTracking;
-(NSString *)resettableDeviceID;
-(BOOL)limitedAdTracking;
-(id)initWithPersistedConfig:(id)arg1 options:(id)arg2 ;
-(NSString *)appIDFromGMP;
-(long long)libraryVersionFromGMP;
-(NSString *)firebaseInstanceID;
-(NSNumber *)appVersionMajor;
-(NSNumber *)appVersionMinor;
-(NSNumber *)appVersionRelease;
-(long long)devCertHash;
-(NSString *)identifierForVendor;
-(NSString *)appVersion;
-(NSString *)appID;
@end

