/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Super Mario Run/Super Mario Run-Structs.h>
@class NSMutableDictionary, NSString;

@interface FIRASqliteStore : NSObject {

	sqlite3Ref _sqliteHandle;
	NSMutableDictionary* _statementCache;
	const char* _queueLabel;
	NSString* _databasePath;

}

@property (nonatomic,readonly) sqlite3Ref sqliteHandle; 
@property (nonatomic,readonly) NSString * databasePath;              //@synthesize databasePath=_databasePath - In the implementation block
-(BOOL)openAndValidateDatabase:(id*)arg1 ;
-(BOOL)closeAndDeleteDatabase;
-(sqlite3Ref)sqliteHandle;
-(id)tableExists:(id)arg1 error:(id*)arg2 ;
-(id)validateTableWithName:(id)arg1 requiredColumnNames:(id)arg2 addOnColumns:(id)arg3 error:(id*)arg4 ;
-(id)columnsForTableWithName:(id)arg1 error:(id*)arg2 ;
-(sqlite3_stmtRef)statementForQuery:(id)arg1 error:(id*)arg2 ;
-(void)cleanUpStatement:(sqlite3_stmtRef)arg1 forQuery:(id)arg2 ;
-(sqlite3_stmtRef)prepareSQL:(id)arg1 error:(id*)arg2 ;
-(BOOL)bindValues:(id)arg1 toStatement:(sqlite3_stmtRef)arg2 error:(id*)arg3 ;
-(id)rowCountForTableWithName:(id)arg1 columnName:(id)arg2 columnValue:(id)arg3 error:(id*)arg4 ;
-(id)numberForQuery:(id)arg1 parameterValues:(id)arg2 error:(id*)arg3 ;
-(sqlite3_stmtRef)upsertStatementForRecord:(id)arg1 inTableWithName:(id)arg2 error:(id*)arg3 ;
-(BOOL)executeSQLStatement:(sqlite3_stmtRef)arg1 error:(id*)arg2 ;
-(sqlite3_stmtRef)updateStatementForRecord:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 error:(id*)arg5 ;
-(void)setDatabaseError:(id*)arg1 operation:(id)arg2 ;
-(sqlite3_stmtRef)statementForQuery:(id)arg1 parameterValues:(id)arg2 error:(id*)arg3 ;
-(id)recordsForQuery:(id)arg1 parameterValues:(id)arg2 error:(id*)arg3 withFilter:(/*^block*/id)arg4 ;
-(id)valueAtColumn:(int)arg1 forStatement:(sqlite3_stmtRef)arg2 ;
-(BOOL)validateDatabaseWithError:(id*)arg1 ;
-(void)finalizeAndClearStatements;
-(id)errorDescriptionForDatabaseOperation:(id)arg1 ;
-(id)monitorContextForDatabaseOperation:(id)arg1 ;
-(BOOL)ensureTableWithName:(id)arg1 createSQL:(id)arg2 requiredColumnNames:(id)arg3 addOnColumns:(id)arg4 error:(id*)arg5 ;
-(id)rowCountForTableWithName:(id)arg1 error:(id*)arg2 ;
-(BOOL)upsertRecord:(id)arg1 inTableWithName:(id)arg2 error:(id*)arg3 ;
-(BOOL)updateRecord:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 error:(id*)arg5 ;
-(BOOL)deleteRecordFromTableWithName:(id)arg1 columnName:(id)arg2 columnValue:(id)arg3 error:(id*)arg4 ;
-(id)deleteRecordsFromTableWithName:(id)arg1 condition:(id)arg2 parameterValues:(id)arg3 error:(id*)arg4 ;
-(BOOL)deleteAllRecordsFromTableWithName:(id)arg1 error:(id*)arg2 ;
-(id)recordsForQuery:(id)arg1 parameterValues:(id)arg2 error:(id*)arg3 ;
-(void)dealloc;
-(void)closeDatabase;
-(id)initWithDatabasePath:(id)arg1 ;
-(id)lastErrorMessage;
-(NSString *)databasePath;
-(BOOL)rollbackTransaction;
-(BOOL)beginTransaction;
-(BOOL)performTransaction:(/*^block*/id)arg1 ;
-(BOOL)executeSQL:(id)arg1 error:(id*)arg2 ;
-(BOOL)endTransaction;
@end

