/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRAEvent;

@interface FIRARawEventData : NSObject {

	FIRAEvent* _rawEvent;
	long long _rowID;
	long long _metadataFingerprint;

}

@property (nonatomic,readonly) FIRAEvent * rawEvent;                       //@synthesize rawEvent=_rawEvent - In the implementation block
@property (nonatomic,readonly) long long rowID;                            //@synthesize rowID=_rowID - In the implementation block
@property (nonatomic,readonly) long long metadataFingerprint;              //@synthesize metadataFingerprint=_metadataFingerprint - In the implementation block
-(id)initWithRawEvent:(id)arg1 rowID:(long long)arg2 metadataFingerprint:(long long)arg3 ;
-(long long)metadataFingerprint;
-(FIRAEvent *)rawEvent;
-(long long)rowID;
@end

