/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <Super Mario Run/FIRALogging.h>

@class NSString;

@interface FIRAASLLogger : NSObject <FIRALogging> {

	asl_object_sRef _ASLClient;
	int _maxASLLevel;

}

@property (assign,nonatomic) int maxASLLevel;                       //@synthesize maxASLLevel=_maxASLLevel - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(int)ASLLevelFromLogLevel:(long long)arg1 maxASLLevel:(int)arg2 ;
-(void)setMaxASLLevel:(int)arg1 ;
-(id)initWithMaxASLLevel:(int)arg1 ;
-(void)logMessage:(id)arg1 withLogLevel:(long long)arg2 ;
-(int)maxASLLevel;
-(void)dealloc;
-(id)init;
@end

