/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FIRADataTypeValidator : NSObject
+(BOOL)isValidString:(id)arg1 minLength:(long long)arg2 maxLength:(long long)arg3 type:(long long)arg4 failureCode:(long long*)arg5 ;
+(BOOL)isValidInternalName:(id)arg1 maxLength:(long long)arg2 type:(long long)arg3 failureCode:(long long*)arg4 ;
+(BOOL)isValidPublicName:(id)arg1 maxLength:(long long)arg2 type:(long long)arg3 failureCode:(long long*)arg4 ;
+(BOOL)isValidValue:(id)arg1 minLength:(long long)arg2 maxLength:(long long)arg3 type:(long long)arg4 failureCode:(long long*)arg5 ;
+(BOOL)isValidPublicEventName:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidPublicEventParameterName:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidPublicEventParameterValue:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidInternalEventOrigin:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidForwardedEventOrigin:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidInternalEventName:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidInternalEventParameterName:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidInternalEventParameterValue:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidPublicUserAttributeName:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidPublicUserAttributeValue:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidInternalUserAttributeName:(id)arg1 failureCode:(long long*)arg2 ;
+(BOOL)isValidInternalUserAttributeValue:(id)arg1 failureCode:(long long*)arg2 ;
+(void)initialize;
@end

