/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FIRClearcutWriter : NSObject {

	int _fd;
	unsigned long long _numBytes;

}

@property (assign,nonatomic) int fd;                                   //@synthesize fd=_fd - In the implementation block
@property (assign,nonatomic) unsigned long long numBytes;              //@synthesize numBytes=_numBytes - In the implementation block
-(BOOL)writeLogEvent:(id)arg1 ;
-(void)setNumBytes:(unsigned long long)arg1 ;
-(unsigned long long)numBytes;
-(void)dealloc;
-(void)close;
-(id)initWithPath:(id)arg1 ;
-(int)fd;
-(void)setFd:(int)arg1 ;
@end

