/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FIRClearcutRequest : NSObject {

	int _logSource;
	NSString* _account;
	NSString* _path;

}

@property (nonatomic,readonly) int logSource;                        //@synthesize logSource=_logSource - In the implementation block
@property (nonatomic,copy,readonly) NSString * account;              //@synthesize account=_account - In the implementation block
@property (nonatomic,copy,readonly) NSString * path;                 //@synthesize path=_path - In the implementation block
-(id)initWithLogSource:(int)arg1 account:(id)arg2 path:(id)arg3 ;
-(int)logSource;
-(NSString *)path;
-(NSString *)account;
@end

