/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRAnalyticsConfiguration;

@interface FIRConfiguration : NSObject {

	FIRAnalyticsConfiguration* _analyticsConfiguration;
	long long _logLevel;

}

@property (nonatomic,retain) FIRAnalyticsConfiguration * analyticsConfiguration;              //@synthesize analyticsConfiguration=_analyticsConfiguration - In the implementation block
@property (assign,nonatomic) long long logLevel;                                              //@synthesize logLevel=_logLevel - In the implementation block
+(id)sharedInstance;
-(FIRAnalyticsConfiguration *)analyticsConfiguration;
-(void)setAnalyticsConfiguration:(FIRAnalyticsConfiguration *)arg1 ;
-(long long)logLevel;
-(void)setLogLevel:(long long)arg1 ;
-(id)init;
@end

