/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSString;

@interface FIRClearcutAccountData : NSObject {

	NSMutableDictionary* _logSourceToWriter;
	NSString* _accountLogDirectory;

}

@property (nonatomic,copy,readonly) NSMutableDictionary * logSourceToWriter;              //@synthesize logSourceToWriter=_logSourceToWriter - In the implementation block
@property (nonatomic,copy) NSString * accountLogDirectory;                                //@synthesize accountLogDirectory=_accountLogDirectory - In the implementation block
-(NSMutableDictionary *)logSourceToWriter;
-(NSString *)accountLogDirectory;
-(id)filenameWithCurrentTimeInDirectory:(id)arg1 ;
-(id)initWithAccountLogDirectory:(id)arg1 ;
-(id)writerForLogSource:(int)arg1 ;
-(void)removeWriterForLogSource:(int)arg1 ;
-(void)flushWriters;
-(void)setAccountLogDirectory:(NSString *)arg1 ;
@end

