/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, FIRInstanceIDAuthService, FIRInstanceIDKeyPair, NSDictionary, NSURLSession, NSURLSessionDataTask;

@interface FIRInstanceIDRegistrationClient : NSObject {

	NSString* _authorizedEntity;
	NSString* _scope;
	FIRInstanceIDAuthService* _authService;
	FIRInstanceIDKeyPair* _keyPair;
	NSDictionary* _options;
	NSURLSession* _session;
	NSURLSessionDataTask* _task;

}

@property (nonatomic,copy) NSString * authorizedEntity;                           //@synthesize authorizedEntity=_authorizedEntity - In the implementation block
@property (nonatomic,copy) NSString * scope;                                      //@synthesize scope=_scope - In the implementation block
@property (nonatomic,retain) FIRInstanceIDAuthService * authService;              //@synthesize authService=_authService - In the implementation block
@property (nonatomic,retain) FIRInstanceIDKeyPair * keyPair;                      //@synthesize keyPair=_keyPair - In the implementation block
@property (nonatomic,retain) NSDictionary * options;                              //@synthesize options=_options - In the implementation block
@property (nonatomic,retain) NSURLSession * session;                              //@synthesize session=_session - In the implementation block
@property (nonatomic,retain) NSURLSessionDataTask * task;                         //@synthesize task=_task - In the implementation block
+(id)newSession;
+(id)registrationClientKeyWithAuthorizedEntity:(id)arg1 scope:(id)arg2 ;
+(id)requestWithAuthHeader:(id)arg1 ;
+(id)requestContentSuffixFromOptions:(id)arg1 ;
+(id)responseHeadersForResponse:(id)arg1 ;
+(id)deleteRequestContentWithDeviceID:(id)arg1 scope:(id)arg2 ;
+(/*^block*/id)updateDeleteHandler:(/*^block*/id)arg1 ;
+(void)deleteGCMTokenOnAppResetWithDeviceID:(id)arg1 secretToken:(id)arg2 handler:(/*^block*/id)arg3 ;
+(void)setRegistrationTestBlock:(/*^block*/id)arg1 ;
+(unsigned long long)nextRequestID;
-(FIRInstanceIDAuthService *)authService;
-(void)stopFetching;
-(NSString *)authorizedEntity;
-(id)HTTPAuthHeaderForAuthorizedEntity:(id)arg1 ;
-(void)addPublicKeyContentToRequestBody:(id)arg1 ;
-(id)parseFetchTokenResponse:(id)arg1 ;
-(void)fetchTokenWithHandler:(/*^block*/id)arg1 ;
-(void)parseToken:(id)arg1 authToken:(id)arg2 withRequestID:(unsigned long long)arg3 handler:(/*^block*/id)arg4 ;
-(FIRInstanceIDKeyPair *)keyPair;
-(id)initWithAuthService:(id)arg1 authorizedEntity:(id)arg2 scope:(id)arg3 keyPair:(id)arg4 ;
-(void)setOptionsForFetchingNewToken:(id)arg1 ;
-(void)deleteTokenWithHandler:(/*^block*/id)arg1 ;
-(void)setAuthorizedEntity:(NSString *)arg1 ;
-(void)setAuthService:(FIRInstanceIDAuthService *)arg1 ;
-(void)setKeyPair:(FIRInstanceIDKeyPair *)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(void)setScope:(NSString *)arg1 ;
-(NSString *)scope;
-(NSURLSessionDataTask *)task;
-(void)setOptions:(NSDictionary *)arg1 ;
-(NSDictionary *)options;
-(void)setTask:(NSURLSessionDataTask *)arg1 ;
-(NSURLSession *)session;
-(long long)requestID;
-(void)setSession:(NSURLSession *)arg1 ;
-(BOOL)inProgress;
@end

