/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FIRInstanceIDCheckinCache;
@class FIRInstanceIDCheckinPreferences, NSURLSession;

@interface FIRInstanceIDCheckinService : NSObject {

	FIRInstanceIDCheckinPreferences* _checkinPreferences;
	id<FIRInstanceIDCheckinCache> _checkinCache;
	NSURLSession* _session;

}

@property (nonatomic,retain) FIRInstanceIDCheckinPreferences * checkinPreferences;              //@synthesize checkinPreferences=_checkinPreferences - In the implementation block
@property (nonatomic,__weak,readonly) id<FIRInstanceIDCheckinCache> checkinCache;               //@synthesize checkinCache=_checkinCache - In the implementation block
@property (nonatomic,retain) NSURLSession * session;                                            //@synthesize session=_session - In the implementation block
+(void)setCheckinTestBlock:(/*^block*/id)arg1 ;
-(id)initWithCheckinCache:(id)arg1 ;
-(FIRInstanceIDCheckinPreferences *)checkinPreferences;
-(void)checkinWithCompletion:(/*^block*/id)arg1 ;
-(void)stopFetching;
-(id)checkinParameters;
-(BOOL)hasCachedDeviceID:(id)arg1 secret:(id)arg2 ;
-(void)setCheckinPreferences:(FIRInstanceIDCheckinPreferences *)arg1 ;
-(id<FIRInstanceIDCheckinCache>)checkinCache;
-(void)dealloc;
-(id)init;
-(NSURLSession *)session;
-(void)setSession:(NSURLSession *)arg1 ;
@end

