/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FIRInstanceIDCheckinCache.h>

@class FIRInstanceIDCheckinStore, FIRInstanceIDBackupExcludedPlist, FIRInstanceIDTokenStore, NSString;

@interface FIRInstanceIDStore : NSObject <FIRInstanceIDCheckinCache> {

	FIRInstanceIDCheckinStore* _checkinStore;
	FIRInstanceIDBackupExcludedPlist* _tokenPlist;
	FIRInstanceIDTokenStore* _tokenStore;

}

@property (nonatomic,retain) FIRInstanceIDCheckinStore * checkinStore;                   //@synthesize checkinStore=_checkinStore - In the implementation block
@property (nonatomic,retain) FIRInstanceIDBackupExcludedPlist * tokenPlist;              //@synthesize tokenPlist=_tokenPlist - In the implementation block
@property (nonatomic,retain) FIRInstanceIDTokenStore * tokenStore;                       //@synthesize tokenStore=_tokenStore - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)hasApplicationSupportSubDirectory:(id)arg1 ;
+(BOOL)createApplicationSupportSubDirectory:(id)arg1 ;
+(id)pathForApplicationSupportSubDirectory:(id)arg1 ;
+(void)deleteGCMTokensOnAppReset:(id)arg1 ;
+(id)apnsTokenCacheKeyForServerType:(BOOL)arg1 ;
+(id)entityWithIndex:(int)arg1 inTokenCacheKey:(id)arg2 ;
+(BOOL)removeApplicationSupportSubDirectory:(id)arg1 error:(id*)arg2 ;
+(id)tokenPlistFileName;
+(id)authorizedEntityInTokenCacheKey:(id)arg1 ;
+(id)scopeInTokenCacheKey:(id)arg1 ;
+(id)cacheKeyForAuthorizedEntity:(id)arg1 scope:(id)arg2 ;
+(id)defaultStore;
-(id)tokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 ;
-(BOOL)saveToken:(id)arg1 withAuthorizedEntity:(id)arg2 scope:(id)arg3 ;
-(BOOL)saveCheckinPreferences:(id)arg1 error:(id*)arg2 ;
-(id)cachedCheckinPreferences;
-(id)initWithTokenPlist:(id)arg1 checkinStore:(id)arg2 tokenStore:(id)arg3 ;
-(void)resetNewApp;
-(void)saveLibraryVersion;
-(BOOL)hasSavedLibraryVersion;
-(FIRInstanceIDCheckinStore *)checkinStore;
-(FIRInstanceIDBackupExcludedPlist *)tokenPlist;
-(FIRInstanceIDTokenStore *)tokenStore;
-(id)currentAppVersion;
-(id)appVersionKey;
-(BOOL)removeCheckinPreferences:(id*)arg1 ;
-(id)currentSavedLibraryVersion;
-(id)cachedAPNSTokenForServerType:(BOOL)arg1 ;
-(void)saveAPNSToken:(id)arg1 isSandbox:(BOOL)arg2 ;
-(void)removeCachedTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 ;
-(BOOL)removeAllCachedTokensWithError:(id*)arg1 ;
-(BOOL)removeAllGCMTokensWithError:(id*)arg1 ;
-(void)removeCachedAPNSTokenForServeryType:(BOOL)arg1 ;
-(void)saveAppVersion;
-(id)currentSavedAppVersion;
-(BOOL)hasSavedAppVersion;
-(void)setCheckinStore:(FIRInstanceIDCheckinStore *)arg1 ;
-(void)setTokenPlist:(FIRInstanceIDBackupExcludedPlist *)arg1 ;
-(void)setTokenStore:(FIRInstanceIDTokenStore *)arg1 ;
-(long long)cacheTimeForTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 ;
-(id)init;
@end

