/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRInstanceIDStore, FIRInstanceIDCheckinService, NSMutableDictionary;

@interface FIRInstanceIDAuthService : NSObject {

	BOOL _allowMissingAPNSToken;
	BOOL _isCheckinInProgress;
	int _checkinRetryCount;
	FIRInstanceIDStore* _store;
	FIRInstanceIDCheckinService* _checkinService;
	NSMutableDictionary* _IIDAuthTokenBySenderID;
	long long _lastCheckinTimestampSeconds;
	long long _nextScheduledCheckinIntervalSeconds;

}

@property (assign,nonatomic) BOOL allowMissingAPNSToken;                                //@synthesize allowMissingAPNSToken=_allowMissingAPNSToken - In the implementation block
@property (nonatomic,retain) FIRInstanceIDStore * store;                                //@synthesize store=_store - In the implementation block
@property (nonatomic,retain) FIRInstanceIDCheckinService * checkinService;              //@synthesize checkinService=_checkinService - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * IIDAuthTokenBySenderID;              //@synthesize IIDAuthTokenBySenderID=_IIDAuthTokenBySenderID - In the implementation block
@property (assign) BOOL isCheckinInProgress;                                            //@synthesize isCheckinInProgress=_isCheckinInProgress - In the implementation block
@property (assign) long long lastCheckinTimestampSeconds;                               //@synthesize lastCheckinTimestampSeconds=_lastCheckinTimestampSeconds - In the implementation block
@property (assign) long long nextScheduledCheckinIntervalSeconds;                       //@synthesize nextScheduledCheckinIntervalSeconds=_nextScheduledCheckinIntervalSeconds - In the implementation block
@property (assign) int checkinRetryCount;                                               //@synthesize checkinRetryCount=_checkinRetryCount - In the implementation block
-(void)fetchCheckinInfoWithHandler:(/*^block*/id)arg1 ;
-(void)scheduleCheckin:(BOOL)arg1 ;
-(void)setAllowMissingAPNSToken:(BOOL)arg1 ;
-(BOOL)hasValidCheckinInfo;
-(id)initWithCheckinService:(id)arg1 store:(id)arg2 ;
-(FIRInstanceIDCheckinService *)checkinService;
-(id)checkinPreferences;
-(long long)calculateNextCheckinRetryIntervalInSeconds;
-(long long)nextScheduledCheckinIntervalSeconds;
-(void)setNextScheduledCheckinIntervalSeconds:(long long)arg1 ;
-(void)doCheckin:(BOOL)arg1 ;
-(int)checkinRetryCount;
-(void)setCheckinRetryCount:(int)arg1 ;
-(void)setLastCheckinTimestampSeconds:(long long)arg1 ;
-(NSMutableDictionary *)IIDAuthTokenBySenderID;
-(id)cachedIIDAuthTokenForAuthorizedEntity:(id)arg1 ;
-(id)checkinAuthToken;
-(void)stopCheckinRequest;
-(void)saveIIDAuthToken:(id)arg1 forAuthorizedEntity:(id)arg2 ;
-(BOOL)allowMissingAPNSToken;
-(void)setCheckinService:(FIRInstanceIDCheckinService *)arg1 ;
-(void)setIIDAuthTokenBySenderID:(NSMutableDictionary *)arg1 ;
-(BOOL)isCheckinInProgress;
-(void)setIsCheckinInProgress:(BOOL)arg1 ;
-(long long)lastCheckinTimestampSeconds;
-(id)initWithStore:(id)arg1 ;
-(FIRInstanceIDStore *)store;
-(void)setStore:(FIRInstanceIDStore *)arg1 ;
@end

