/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRInstanceIDBackupExcludedPlist, FIRInstanceIDAuthKeychain;

@interface FIRInstanceIDCheckinStore : NSObject {

	FIRInstanceIDBackupExcludedPlist* _plist;
	FIRInstanceIDAuthKeychain* _keychain;

}

@property (nonatomic,retain) FIRInstanceIDBackupExcludedPlist * plist;              //@synthesize plist=_plist - In the implementation block
@property (nonatomic,retain) FIRInstanceIDAuthKeychain * keychain;                  //@synthesize keychain=_keychain - In the implementation block
-(id)initWithCheckinPlist:(id)arg1 keychain:(id)arg2 ;
-(id)initWithCheckinPlistFileName:(id)arg1 applicationSupportSubDirectory:(id)arg2 ;
-(BOOL)hasCheckinPlist;
-(BOOL)saveCheckinPreferences:(id)arg1 error:(id*)arg2 ;
-(BOOL)removeCheckinPreferencesWithError:(id*)arg1 ;
-(id)cachedCheckinPreferences;
-(FIRInstanceIDAuthKeychain *)keychain;
-(void)setKeychain:(FIRInstanceIDAuthKeychain *)arg1 ;
-(void)setPlist:(FIRInstanceIDBackupExcludedPlist *)arg1 ;
-(FIRInstanceIDBackupExcludedPlist *)plist;
@end

