/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FIRInstanceIDCachedToken : NSObject {

	BOOL _shouldRefreshTokens;
	BOOL _shouldInvalidateAllTokens;
	NSString* _token;
	long long _status;

}

@property (assign,nonatomic) BOOL shouldRefreshTokens;                    //@synthesize shouldRefreshTokens=_shouldRefreshTokens - In the implementation block
@property (assign,nonatomic) BOOL shouldInvalidateAllTokens;              //@synthesize shouldInvalidateAllTokens=_shouldInvalidateAllTokens - In the implementation block
@property (nonatomic,retain) NSString * token;                            //@synthesize token=_token - In the implementation block
@property (assign,nonatomic) long long status;                            //@synthesize status=_status - In the implementation block
-(BOOL)shouldInvalidateAllTokens;
-(id)initWithToken:(id)arg1 status:(long long)arg2 ;
-(BOOL)shouldRefreshTokens;
-(void)setShouldRefreshTokens:(BOOL)arg1 ;
-(void)setShouldInvalidateAllTokens:(BOOL)arg1 ;
-(BOOL)isValid;
-(long long)status;
-(void)setStatus:(long long)arg1 ;
-(NSString *)token;
-(void)setToken:(NSString *)arg1 ;
@end

