/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Super Mario Run/Super Mario Run-Structs.h>
@class NSData;

@interface FIRInstanceIDKeyPair : NSObject {

	SecKeyRef _privateKey;
	SecKeyRef _publicKey;
	NSData* _publicKeyData;
	NSData* _privateKeyData;

}

@property (nonatomic,retain) NSData * publicKeyData;               //@synthesize publicKeyData=_publicKeyData - In the implementation block
@property (nonatomic,retain) NSData * privateKeyData;              //@synthesize privateKeyData=_privateKeyData - In the implementation block
+(id)keyDataWithTag:(id)arg1 ;
+(SecKeyRef)cachedKeyRefWithTag:(id)arg1 ;
+(id)queryDictWithTag:(id)arg1 addReturnAttr:(BOOL)arg2 withTypeData:(BOOL)arg3 ;
+(id)generateRSA2048KeyPairWithPrivateTag:(id)arg1 publicTag:(id)arg2 error:(id*)arg3 ;
+(BOOL)deleteKeyPairWithPrivateTag:(id)arg1 publicTag:(id)arg2 error:(id*)arg3 ;
+(id)keyPairForPrivateKeyTag:(id)arg1 publicKeyTag:(id)arg2 error:(id*)arg3 ;
+(id)appIdentityWithKeyPair:(id)arg1 ;
-(id)initWithPrivateKey:(SecKeyRef)arg1 publicKey:(SecKeyRef)arg2 publicKeyData:(id)arg3 privateKeyData:(id)arg4 ;
-(void)setPublicKeyData:(NSData *)arg1 ;
-(NSData *)privateKeyData;
-(void)setPrivateKeyData:(NSData *)arg1 ;
-(NSData *)publicKeyData;
-(void)dealloc;
-(id)init;
-(BOOL)isValid;
-(SecKeyRef)privateKey;
-(SecKeyRef)publicKey;
@end

