/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSString;

@interface FIRInstanceIDBackupExcludedPlist : NSObject {

	BOOL _fileInApplicationSupport;
	NSDictionary* _cachedPlistContents;
	NSString* _fileName;
	NSString* _applicationSupportSubDirectory;

}

@property (nonatomic,retain) NSDictionary * cachedPlistContents;                   //@synthesize cachedPlistContents=_cachedPlistContents - In the implementation block
@property (nonatomic,copy) NSString * fileName;                                    //@synthesize fileName=_fileName - In the implementation block
@property (nonatomic,copy) NSString * applicationSupportSubDirectory;              //@synthesize applicationSupportSubDirectory=_applicationSupportSubDirectory - In the implementation block
@property (assign,nonatomic) BOOL fileInApplicationSupport;                        //@synthesize fileInApplicationSupport=_fileInApplicationSupport - In the implementation block
-(BOOL)moveToApplicationSupportSubDirectory:(id)arg1 ;
-(unsigned long long)plistDirectory;
-(id)plistPathInDirectory:(unsigned long long)arg1 ;
-(void)setCachedPlistContents:(NSDictionary *)arg1 ;
-(NSDictionary *)cachedPlistContents;
-(NSString *)applicationSupportSubDirectory;
-(void)setFileInApplicationSupport:(BOOL)arg1 ;
-(BOOL)doesFileExistInDirectory:(unsigned long long)arg1 ;
-(BOOL)fileInApplicationSupport;
-(id)pathWithName:(id)arg1 inDirectory:(unsigned long long)arg2 ;
-(id)initWithFileName:(id)arg1 applicationSupportSubDirectory:(id)arg2 ;
-(BOOL)writeDictionary:(id)arg1 error:(id*)arg2 ;
-(id)contentAsDictionary;
-(void)moveToApplicationSupportSubDirectory;
-(BOOL)doesFileExist;
-(void)setApplicationSupportSubDirectory:(NSString *)arg1 ;
-(BOOL)deleteFile:(id*)arg1 ;
-(NSString *)fileName;
-(void)setFileName:(NSString *)arg1 ;
@end

