/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FIRMessagingSecureSocketDelegate.h>

@protocol FIRMessagingConnectionDelegate;
@class NSString, FIRMessagingRmqManager, FIRMessagingDataMessageManager, FIRMessagingSecureSocket, NSMutableArray, NSMutableDictionary, NSRunLoop;

@interface FIRMessagingConnection : NSObject <FIRMessagingSecureSocketDelegate> {

	int _lastStreamIdAcked;
	int _inStreamId;
	int _outStreamId;
	long long _lastHeartbeatPingTimestamp;
	unsigned long long _state;
	NSString* _host;
	unsigned long long _port;
	id<FIRMessagingConnectionDelegate> _delegate;
	FIRMessagingRmqManager* _rmq2Manager;
	FIRMessagingDataMessageManager* _dataMessageManager;
	NSString* _authId;
	NSString* _token;
	FIRMessagingSecureSocket* _socket;
	long long _lastLoginServerTimestamp;
	NSMutableArray* _unackedS2dIds;
	NSMutableDictionary* _ackedS2dMap;
	NSMutableArray* _d2sInfos;
	NSMutableArray* _sendOnConnectMessages;
	NSRunLoop* _runLoop;

}

@property (assign,nonatomic,__weak) FIRMessagingRmqManager * rmq2Manager;                             //@synthesize rmq2Manager=_rmq2Manager - In the implementation block
@property (assign,nonatomic,__weak) FIRMessagingDataMessageManager * dataMessageManager;              //@synthesize dataMessageManager=_dataMessageManager - In the implementation block
@property (assign,nonatomic) unsigned long long state;                                                //@synthesize state=_state - In the implementation block
@property (nonatomic,copy) NSString * host;                                                           //@synthesize host=_host - In the implementation block
@property (assign,nonatomic) unsigned long long port;                                                 //@synthesize port=_port - In the implementation block
@property (nonatomic,retain) NSString * authId;                                                       //@synthesize authId=_authId - In the implementation block
@property (nonatomic,retain) NSString * token;                                                        //@synthesize token=_token - In the implementation block
@property (nonatomic,retain) FIRMessagingSecureSocket * socket;                                       //@synthesize socket=_socket - In the implementation block
@property (assign,nonatomic) long long lastLoginServerTimestamp;                                      //@synthesize lastLoginServerTimestamp=_lastLoginServerTimestamp - In the implementation block
@property (assign,nonatomic) int lastStreamIdAcked;                                                   //@synthesize lastStreamIdAcked=_lastStreamIdAcked - In the implementation block
@property (assign,nonatomic) int inStreamId;                                                          //@synthesize inStreamId=_inStreamId - In the implementation block
@property (assign,nonatomic) int outStreamId;                                                         //@synthesize outStreamId=_outStreamId - In the implementation block
@property (nonatomic,retain) NSMutableArray * unackedS2dIds;                                          //@synthesize unackedS2dIds=_unackedS2dIds - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * ackedS2dMap;                                       //@synthesize ackedS2dMap=_ackedS2dMap - In the implementation block
@property (nonatomic,retain) NSMutableArray * d2sInfos;                                               //@synthesize d2sInfos=_d2sInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * sendOnConnectMessages;                                  //@synthesize sendOnConnectMessages=_sendOnConnectMessages - In the implementation block
@property (nonatomic,retain) NSRunLoop * runLoop;                                                     //@synthesize runLoop=_runLoop - In the implementation block
@property (assign,nonatomic) long long lastHeartbeatPingTimestamp;                                    //@synthesize lastHeartbeatPingTimestamp=_lastHeartbeatPingTimestamp - In the implementation block
@property (assign,nonatomic,__weak) id<FIRMessagingConnectionDelegate> delegate;                      //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)loginRequestWithToken:(id)arg1 authID:(id)arg2 ;
+(id)createStreamAck;
+(int)currentNetworkType;
-(FIRMessagingRmqManager *)rmq2Manager;
-(void)setDataMessageManager:(FIRMessagingDataMessageManager *)arg1 ;
-(FIRMessagingDataMessageManager *)dataMessageManager;
-(void)setRmq2Manager:(FIRMessagingRmqManager *)arg1 ;
-(int)inStreamId;
-(int)outStreamId;
-(void)setupConnectionSocket;
-(void)connectToSocket:(id)arg1 ;
-(NSMutableArray *)sendOnConnectMessages;
-(void)sendClose;
-(void)setLastStreamIdAcked:(int)arg1 ;
-(void)setInStreamId:(int)arg1 ;
-(void)setOutStreamId:(int)arg1 ;
-(void)resetUnconfirmedAcks;
-(NSString *)authId;
-(void)sendLoginRequest:(id)arg1 token:(id)arg2 ;
-(void)cancelConnectionTimeoutTask;
-(void)sendHeartbeatPing;
-(void)willProcessProto:(id)arg1 ;
-(void)didReceiveLoginResponse:(id)arg1 ;
-(void)didReceiveDataMessageStanza:(id)arg1 ;
-(void)didReceiveHeartbeatPing:(id)arg1 ;
-(void)didReceiveHeartbeatAck:(id)arg1 ;
-(void)didReceiveClose:(id)arg1 ;
-(void)handleIqStanza:(id)arg1 ;
-(void)didReceiveUnhandledProto:(id)arg1 ;
-(void)logMessage:(id)arg1 messageType:(int)arg2 isOut:(BOOL)arg3 ;
-(void)willSendProto:(id)arg1 ;
-(void)sendProto:(id)arg1 ;
-(NSMutableArray *)d2sInfos;
-(NSMutableArray *)unackedS2dIds;
-(void)scheduleConnectionTimeoutTask;
-(void)didReceiveStreamAck:(id)arg1 ;
-(void)didReceiveSelectiveAck:(id)arg1 ;
-(void)setLastLoginServerTimestamp:(long long)arg1 ;
-(void)sendHeartbeatAck;
-(void)confirmAckedD2sIdsWithStreamId:(int)arg1 ;
-(void)confirmAckedS2dIdsWithStreamId:(int)arg1 ;
-(int)lastStreamIdAcked;
-(void)sendStreamAck;
-(NSMutableDictionary *)ackedS2dMap;
-(void)secureSocket:(id)arg1 didReceiveData:(id)arg2 withTag:(char)arg3 ;
-(void)secureSocket:(id)arg1 didSendProtoWithTag:(char)arg2 rmqId:(id)arg3 ;
-(void)secureSocketDidConnect:(id)arg1 ;
-(void)didDisconnectWithSecureSocket:(id)arg1 ;
-(id)initWithAuthID:(id)arg1 token:(id)arg2 host:(id)arg3 port:(unsigned long long)arg4 runLoop:(id)arg5 rmq2Manager:(id)arg6 gcmManager:(id)arg7 ;
-(void)signIn;
-(void)sendOnConnectOrDrop:(id)arg1 ;
-(void)didReceiveAckForRmqIds:(id)arg1 ;
-(long long)lastHeartbeatPingTimestamp;
-(void)setLastHeartbeatPingTimestamp:(long long)arg1 ;
-(void)setAuthId:(NSString *)arg1 ;
-(long long)lastLoginServerTimestamp;
-(void)setUnackedS2dIds:(NSMutableArray *)arg1 ;
-(void)setAckedS2dMap:(NSMutableDictionary *)arg1 ;
-(void)setD2sInfos:(NSMutableArray *)arg1 ;
-(void)setSendOnConnectMessages:(NSMutableArray *)arg1 ;
-(void)setPort:(unsigned long long)arg1 ;
-(NSRunLoop *)runLoop;
-(void)setDelegate:(id<FIRMessagingConnectionDelegate>)arg1 ;
-(NSString *)description;
-(id<FIRMessagingConnectionDelegate>)delegate;
-(unsigned long long)state;
-(void)setState:(unsigned long long)arg1 ;
-(NSString *)host;
-(void)disconnect;
-(unsigned long long)port;
-(NSString *)token;
-(void)setToken:(NSString *)arg1 ;
-(void)setHost:(NSString *)arg1 ;
-(void)signOut;
-(void)setSocket:(FIRMessagingSecureSocket *)arg1 ;
-(FIRMessagingSecureSocket *)socket;
-(double)connectionTimeoutInterval;
-(void)connectionTimedOut;
-(void)setRunLoop:(NSRunLoop *)arg1 ;
-(void)teardown;
@end

