/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSUserDefaults, NSMutableDictionary;

@interface FIRMessagingPubSubCache : NSObject {

	int _subscribeTopicsSyncCount;
	int _unsubscribeTopicsSyncCount;
	NSUserDefaults* _userDefaults;
	NSMutableDictionary* _subscribedTopics;
	NSMutableDictionary* _allTopics;
	long long _lastSyncTimestampMillis;
	long long _nextScheduledSyncTimestampMillis;

}

@property (nonatomic,retain) NSUserDefaults * userDefaults;                           //@synthesize userDefaults=_userDefaults - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * subscribedTopics;                  //@synthesize subscribedTopics=_subscribedTopics - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * allTopics;                         //@synthesize allTopics=_allTopics - In the implementation block
@property (assign,nonatomic) long long lastSyncTimestampMillis;                       //@synthesize lastSyncTimestampMillis=_lastSyncTimestampMillis - In the implementation block
@property (assign,nonatomic) long long nextScheduledSyncTimestampMillis;              //@synthesize nextScheduledSyncTimestampMillis=_nextScheduledSyncTimestampMillis - In the implementation block
@property (assign) int subscribeTopicsSyncCount;                                      //@synthesize subscribeTopicsSyncCount=_subscribeTopicsSyncCount - In the implementation block
@property (assign) int unsubscribeTopicsSyncCount;                                    //@synthesize unsubscribeTopicsSyncCount=_unsubscribeTopicsSyncCount - In the implementation block
+(id)cacheKeyForTopic:(id)arg1 token:(id)arg2 options:(id)arg3 ;
-(void)addTopic:(id)arg1 ;
-(void)removeTopic:(id)arg1 ;
-(void)scheduleSync:(BOOL)arg1 ;
-(BOOL)verifyCacheEntryState:(char)arg1 forTopic:(id)arg2 token:(id)arg3 options:(id)arg4 ;
-(void)updateCacheForTopic:(id)arg1 token:(id)arg2 options:(id)arg3 to:(char)arg4 ;
-(BOOL)isCacheEntryValidWithTime:(long long)arg1 ;
-(NSMutableDictionary *)allTopics;
-(void)updateSet:(id)arg1 withTopic:(id)arg2 cacheKey:(id)arg3 shouldRemove:(BOOL)arg4 ;
-(NSMutableDictionary *)subscribedTopics;
-(long long)calculateNextSyncTimestampMillis;
-(long long)nextScheduledSyncTimestampMillis;
-(void)setNextScheduledSyncTimestampMillis:(long long)arg1 ;
-(void)synchronizeTopics:(BOOL)arg1 ;
-(int)subscribeTopicsSyncCount;
-(int)unsubscribeTopicsSyncCount;
-(id)topicsToSubscribeTo;
-(id)topicsToUnsubscribeFrom;
-(void)setSubscribeTopicsSyncCount:(int)arg1 ;
-(void)didSubscribeToTopic:(id)arg1 ;
-(void)setUnsubscribeTopicsSyncCount:(int)arg1 ;
-(void)didUnsubscribeFromTopic:(id)arg1 ;
-(long long)cacheRefreshInterval;
-(long long)lastSyncTimestampMillis;
-(void)setSubscribedTopics:(NSMutableDictionary *)arg1 ;
-(void)setAllTopics:(NSMutableDictionary *)arg1 ;
-(void)setLastSyncTimestampMillis:(long long)arg1 ;
-(id)init;
-(void)setUserDefaults:(NSUserDefaults *)arg1 ;
-(NSUserDefaults *)userDefaults;
@end

