/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FIRMessagingRmqScanner.h>

@class FIRMessagingRmq2PersistentStore, NSMutableDictionary, NSString;

@interface FIRMessagingRmqManager : NSObject <FIRMessagingRmqScanner> {

	FIRMessagingRmq2PersistentStore* _rmq2Store;
	NSMutableDictionary* _outstandingMessages;
	long long _rmqId;

}

@property (nonatomic,retain) FIRMessagingRmq2PersistentStore * rmq2Store;              //@synthesize rmq2Store=_rmq2Store - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * outstandingMessages;                //@synthesize outstandingMessages=_outstandingMessages - In the implementation block
@property (assign,nonatomic) long long rmqId;                                          //@synthesize rmqId=_rmqId - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)removeDatabaseWithName:(id)arg1 ;
-(id)initWithDatabaseName:(id)arg1 ;
-(void)loadRmqId;
-(BOOL)saveS2dMessageWithRmqId:(id)arg1 ;
-(id)unackedS2dRmqIds;
-(void)removeS2dIds:(id)arg1 ;
-(BOOL)saveRmqMessage:(id)arg1 error:(id*)arg2 ;
-(void)scanWithRmqMessageHandler:(/*^block*/id)arg1 dataMessageHandler:(/*^block*/id)arg2 ;
-(int)removeRmqMessagesWithRmqIds:(id)arg1 ;
-(long long)rmqId;
-(void)setRmqId:(long long)arg1 ;
-(long long)queryHighestRmqId;
-(id)querySyncMessageWithRmqID:(id)arg1 ;
-(BOOL)deleteSyncMessageWithRmqID:(id)arg1 ;
-(int)deleteExpiredOrFinishedSyncMessages:(id*)arg1 ;
-(BOOL)saveSyncMessageWithRmqID:(id)arg1 expirationTime:(long long)arg2 apnsReceived:(BOOL)arg3 mcsReceived:(BOOL)arg4 error:(id*)arg5 ;
-(BOOL)updateSyncMessageViaAPNSWithRmqID:(id)arg1 error:(id*)arg2 ;
-(BOOL)updateSyncMessageViaMCSWithRmqID:(id)arg1 error:(id*)arg2 ;
-(void)loadInitialOutgoingPersistentId;
-(NSMutableDictionary *)outstandingMessages;
-(long long)querylastRmqId;
-(long long)nextRmqId;
-(BOOL)saveMessage:(id)arg1 withRmqId:(long long)arg2 tag:(char)arg3 error:(id*)arg4 ;
-(FIRMessagingRmq2PersistentStore *)rmq2Store;
-(void)ackReceivedForRmqId:(id)arg1 ;
-(void)saveLastOutgoingRmqId:(long long)arg1 ;
-(int)removeRmqMessagesWithRmqId:(id)arg1 ;
-(void)setRmq2Store:(FIRMessagingRmq2PersistentStore *)arg1 ;
-(void)setOutstandingMessages:(NSMutableDictionary *)arg1 ;
@end

