/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRMessagingPubSubCache, FIRMessagingClient;

@interface FIRMessagingPubSub : NSObject {

	FIRMessagingPubSubCache* _cache;
	FIRMessagingClient* _client;

}

@property (nonatomic,retain) FIRMessagingPubSubCache * cache;              //@synthesize cache=_cache - In the implementation block
@property (nonatomic,retain) FIRMessagingClient * client;                  //@synthesize client=_client - In the implementation block
+(BOOL)hasTopicsPrefix:(id)arg1 ;
+(BOOL)isValidTopicWithPrefix:(id)arg1 ;
+(id)addPrefixToTopic:(id)arg1 ;
+(id)topicRegex;
-(void)addTopic:(id)arg1 ;
-(void)removeTopic:(id)arg1 ;
-(void)scheduleSync:(BOOL)arg1 ;
-(BOOL)verifyPubSubOptions:(id)arg1 ;
-(void)subscribeWithToken:(id)arg1 topic:(id)arg2 options:(id)arg3 handler:(/*^block*/id)arg4 ;
-(void)unsubscribeWithToken:(id)arg1 topic:(id)arg2 options:(id)arg3 handler:(/*^block*/id)arg4 ;
-(id)init;
-(FIRMessagingPubSubCache *)cache;
-(void)setCache:(FIRMessagingPubSubCache *)arg1 ;
-(void)setClient:(FIRMessagingClient *)arg1 ;
-(id)initWithClient:(id)arg1 ;
-(FIRMessagingClient *)client;
@end

