/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Super Mario Run/Super Mario Run-Structs.h>
@class NSData;

@interface FIRMessagingCodedInputStream : NSObject {

	NSData* _buffer;
	SCD_Struct_FI30* _state;

}

@property (nonatomic,retain) NSData * buffer;                          //@synthesize buffer=_buffer - In the implementation block
@property (assign,nonatomic) SCD_Struct_FI30* state;                   //@synthesize state=_state - In the implementation block
@property (nonatomic,readonly) unsigned long long offset; 
-(BOOL)readTag:(char*)arg1 ;
-(BOOL)readLength:(int*)arg1 ;
-(id)readDataWithLength:(unsigned)arg1 ;
-(SCD_Struct_FI30*)state;
-(void)setState:(SCD_Struct_FI30*)arg1 ;
-(id)initWithData:(id)arg1 ;
-(unsigned long long)offset;
-(void)setBuffer:(NSData *)arg1 ;
-(NSData *)buffer;
@end

