/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface FIRMessagingPacketQueue : NSObject {

	NSMutableArray* _packetsContainer;

}

@property (nonatomic,retain) NSMutableArray * packetsContainer;              //@synthesize packetsContainer=_packetsContainer - In the implementation block
@property (nonatomic,readonly) unsigned long long count; 
@property (nonatomic,readonly) BOOL isEmpty; 
-(NSMutableArray *)packetsContainer;
-(void)pushHead:(id)arg1 ;
-(void)setPacketsContainer:(NSMutableArray *)arg1 ;
-(unsigned long long)count;
-(id)init;
-(BOOL)isEmpty;
-(id)pop;
-(void)push:(id)arg1 ;
@end

