/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRMessagingRmqManager;

@interface FIRMessagingSyncMessageManager : NSObject {

	FIRMessagingRmqManager* _rmqManager;

}

@property (nonatomic,retain) FIRMessagingRmqManager * rmqManager;              //@synthesize rmqManager=_rmqManager - In the implementation block
+(long long)expirationTimeForSyncMessage:(id)arg1 ;
-(id)initWithRmqManager:(id)arg1 ;
-(void)removeExpiredSyncMessages;
-(BOOL)didReceiveAPNSSyncMessage:(id)arg1 ;
-(BOOL)didReceiveMCSSyncMessage:(id)arg1 ;
-(FIRMessagingRmqManager *)rmqManager;
-(BOOL)didReceiveSyncMessage:(id)arg1 viaAPNS:(BOOL)arg2 viaMCS:(BOOL)arg3 ;
-(void)setRmqManager:(FIRMessagingRmqManager *)arg1 ;
-(id)init;
@end

