/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FIRMessagingAuthKeychain : NSObject {

	NSString* _generic;

}

@property (nonatomic,retain) NSString * generic;              //@synthesize generic=_generic - In the implementation block
+(id)keychainQueryForService:(id)arg1 account:(id)arg2 generic:(id)arg3 ;
+(void*)keychainItemAccessibility;
-(id)keychainQueryForService:(id)arg1 account:(id)arg2 ;
-(id)passwordForService:(id)arg1 account:(id)arg2 error:(id*)arg3 ;
-(BOOL)setPassword:(id)arg1 forService:(id)arg2 accessibility:(void*)arg3 account:(id)arg4 error:(id*)arg5 ;
-(BOOL)removePasswordForService:(id)arg1 account:(id)arg2 error:(id*)arg3 ;
-(id)initWithIdentifier:(id)arg1 ;
-(NSString *)generic;
-(void)setGeneric:(NSString *)arg1 ;
@end

