/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FIRMessagingDataMessageManagerDelegate;
@class FIRMessagingClient, FIRMessagingRmqManager, FIRMessagingSyncMessageManager, FIRMessagingDelayedMessageQueue, NSString;

@interface FIRMessagingDataMessageManager : NSObject {

	char _upstreamForceReconnect;
	int _ttl;
	int _maxAppDataSize;
	FIRMessagingClient* _client;
	FIRMessagingRmqManager* _rmq2Manager;
	FIRMessagingSyncMessageManager* _syncMessageManager;
	id<FIRMessagingDataMessageManagerDelegate> _delegate;
	FIRMessagingDelayedMessageQueue* _delayedMessagesQueue;
	NSString* _deviceAuthID;
	NSString* _secretToken;

}

@property (assign,nonatomic,__weak) FIRMessagingClient * client;                                      //@synthesize client=_client - In the implementation block
@property (assign,nonatomic,__weak) FIRMessagingRmqManager * rmq2Manager;                             //@synthesize rmq2Manager=_rmq2Manager - In the implementation block
@property (assign,nonatomic,__weak) FIRMessagingSyncMessageManager * syncMessageManager;              //@synthesize syncMessageManager=_syncMessageManager - In the implementation block
@property (assign,nonatomic,__weak) id<FIRMessagingDataMessageManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) FIRMessagingDelayedMessageQueue * delayedMessagesQueue;                  //@synthesize delayedMessagesQueue=_delayedMessagesQueue - In the implementation block
@property (assign,nonatomic) int ttl;                                                                 //@synthesize ttl=_ttl - In the implementation block
@property (nonatomic,copy) NSString * deviceAuthID;                                                   //@synthesize deviceAuthID=_deviceAuthID - In the implementation block
@property (nonatomic,copy) NSString * secretToken;                                                    //@synthesize secretToken=_secretToken - In the implementation block
@property (assign,nonatomic) int maxAppDataSize;                                                      //@synthesize maxAppDataSize=_maxAppDataSize - In the implementation block
@property (assign,nonatomic) char upstreamForceReconnect;                                             //@synthesize upstreamForceReconnect=_upstreamForceReconnect - In the implementation block
-(NSString *)secretToken;
-(void)setSecretToken:(NSString *)arg1 ;
-(FIRMessagingRmqManager *)rmq2Manager;
-(FIRMessagingSyncMessageManager *)syncMessageManager;
-(id)initWithDelegate:(id)arg1 client:(id)arg2 rmq2Manager:(id)arg3 syncMessageManager:(id)arg4 ;
-(void)refreshDelayedMessages;
-(void)setRmq2Manager:(FIRMessagingRmqManager *)arg1 ;
-(void)setSyncMessageManager:(FIRMessagingSyncMessageManager *)arg1 ;
-(void)sendDataMessageStanza:(id)arg1 ;
-(NSString *)deviceAuthID;
-(void)resendMessagesWithConnection:(id)arg1 ;
-(void)setDeviceAuthID:(NSString *)arg1 ;
-(void)sendDelayedMessages:(id)arg1 ;
-(void)setDelayedMessagesQueue:(FIRMessagingDelayedMessageQueue *)arg1 ;
-(void)handleMCSDataMessage:(id)arg1 ;
-(id)parseDataMessage:(id)arg1 ;
-(id)filterInternalFIRMessagingKeysFromMessage:(id)arg1 ;
-(id)categoryForUpstreamMessages;
-(int)delayForMessage:(id)arg1 ;
-(void)willSendDataMessageFail:(id)arg1 withMessageId:(id)arg2 error:(unsigned long long)arg3 ;
-(int)addData:(id)arg1 toStanza:(id)arg2 ;
-(void)willSendDataMessageSuccess:(id)arg1 withMessageId:(id)arg2 ;
-(BOOL)delayMessage:(id)arg1 ;
-(FIRMessagingDelayedMessageQueue *)delayedMessagesQueue;
-(BOOL)tryToSendDataMessageStanza:(id)arg1 ;
-(void)addParamWithKey:(id)arg1 value:(id)arg2 toStanza:(id)arg3 ;
-(BOOL)handleExpirationForDataMessage:(id)arg1 ;
-(char)upstreamForceReconnect;
-(void)setDeviceAuthID:(id)arg1 secretToken:(id)arg2 ;
-(id)processPacket:(id)arg1 ;
-(void)didReceiveParsedMessage:(id)arg1 ;
-(void)didSendDataMessageStanza:(id)arg1 ;
-(int)maxAppDataSize;
-(void)setMaxAppDataSize:(int)arg1 ;
-(void)setUpstreamForceReconnect:(char)arg1 ;
-(void)setDelegate:(id<FIRMessagingDataMessageManagerDelegate>)arg1 ;
-(id<FIRMessagingDataMessageManagerDelegate>)delegate;
-(int)ttl;
-(void)setTtl:(int)arg1 ;
-(void)setClient:(FIRMessagingClient *)arg1 ;
-(FIRMessagingClient *)client;
@end

