/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRMessagingPubSubRegistrar, FIRMessagingCheckinService, NSString;

@interface FIRMessagingRegistrar : NSObject {

	BOOL _stopAllSubscriptions;
	FIRMessagingPubSubRegistrar* _pubsubRegistrar;
	FIRMessagingCheckinService* _checkinService;

}

@property (assign,nonatomic) BOOL stopAllSubscriptions;                                  //@synthesize stopAllSubscriptions=_stopAllSubscriptions - In the implementation block
@property (nonatomic,retain) FIRMessagingCheckinService * checkinService;                //@synthesize checkinService=_checkinService - In the implementation block
@property (nonatomic,retain) FIRMessagingPubSubRegistrar * pubsubRegistrar;              //@synthesize pubsubRegistrar=_pubsubRegistrar - In the implementation block
@property (nonatomic,readonly) NSString * deviceAuthID; 
@property (nonatomic,readonly) NSString * secretToken; 
-(BOOL)hasValidCheckinInfo;
-(FIRMessagingCheckinService *)checkinService;
-(NSString *)secretToken;
-(void)setCheckinService:(FIRMessagingCheckinService *)arg1 ;
-(NSString *)deviceAuthID;
-(void)updateSubscriptionToTopic:(id)arg1 withToken:(id)arg2 options:(id)arg3 shouldDelete:(BOOL)arg4 handler:(/*^block*/id)arg5 ;
-(BOOL)tryToLoadValidCheckinInfo;
-(void)doUpdateSubscriptionForTopic:(id)arg1 token:(id)arg2 options:(id)arg3 shouldDelete:(BOOL)arg4 completion:(/*^block*/id)arg5 ;
-(void)setStopAllSubscriptions:(BOOL)arg1 ;
-(FIRMessagingPubSubRegistrar *)pubsubRegistrar;
-(void)setPubsubRegistrar:(FIRMessagingPubSubRegistrar *)arg1 ;
-(BOOL)stopAllSubscriptions;
-(id)init;
-(void)cancelAllRequests;
@end

