/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FIRInstanceIDCheckinPreferences, NSString;

@interface FIRMessagingCheckinService : NSObject {

	FIRInstanceIDCheckinPreferences* _checkinPreferences;

}

@property (nonatomic,retain) FIRInstanceIDCheckinPreferences * checkinPreferences;              //@synthesize checkinPreferences=_checkinPreferences - In the implementation block
@property (nonatomic,readonly) NSString * deviceAuthID; 
@property (nonatomic,readonly) NSString * secretToken; 
@property (nonatomic,readonly) NSString * versionInfo; 
@property (nonatomic,readonly) BOOL hasValidCheckinInfo; 
@property (nonatomic,readonly) long long lastCheckinTimestampMillis; 
-(BOOL)hasValidCheckinInfo;
-(FIRInstanceIDCheckinPreferences *)checkinPreferences;
-(NSString *)secretToken;
-(long long)lastCheckinTimestampMillis;
-(void)setCheckinPreferences:(FIRInstanceIDCheckinPreferences *)arg1 ;
-(BOOL)tryToLoadPrefetchedCheckinPreferences;
-(NSString *)deviceAuthID;
-(id)digest;
-(NSString *)versionInfo;
@end

