/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/FIRReachabilityDelegate.h>
#import <Super Mario Run/FIRNetworkLoggerDelegate.h>

@protocol FIRNetworkReachabilityDelegate, FIRNetworkLoggerDelegate;
@class FIRReachabilityChecker, FIRMutableDictionary, NSString;

@interface FIRNetwork : NSObject <FIRReachabilityDelegate, FIRNetworkLoggerDelegate> {

	FIRReachabilityChecker* _reachability;
	FIRMutableDictionary* _requests;
	BOOL _networkConnected;
	BOOL _isDebugModeEnabled;
	id<FIRNetworkReachabilityDelegate> _reachabilityDelegate;
	id<FIRNetworkLoggerDelegate> _loggerDelegate;
	double _timeoutInterval;

}

@property (getter=isNetworkConnected,nonatomic,readonly) BOOL networkConnected;                           //@synthesize networkConnected=_networkConnected - In the implementation block
@property (getter=hasUploadInProgress,nonatomic,readonly) BOOL uploadInProgress; 
@property (assign,nonatomic,__weak) id<FIRNetworkReachabilityDelegate> reachabilityDelegate;              //@synthesize reachabilityDelegate=_reachabilityDelegate - In the implementation block
@property (assign,nonatomic,__weak) id<FIRNetworkLoggerDelegate> loggerDelegate;                          //@synthesize loggerDelegate=_loggerDelegate - In the implementation block
@property (assign,nonatomic) BOOL isDebugModeEnabled;                                                     //@synthesize isDebugModeEnabled=_isDebugModeEnabled - In the implementation block
@property (assign,nonatomic) double timeoutInterval;                                                      //@synthesize timeoutInterval=_timeoutInterval - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)handleEventsForBackgroundURLSessionID:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)setLoggerDelegate:(id<FIRNetworkLoggerDelegate>)arg1 ;
-(void)setReachabilityDelegate:(id<FIRNetworkReachabilityDelegate>)arg1 ;
-(id)postURL:(id)arg1 payload:(id)arg2 queue:(id)arg3 usingBackgroundSession:(BOOL)arg4 completionHandler:(/*^block*/id)arg5 ;
-(BOOL)hasUploadInProgress;
-(id)getURL:(id)arg1 headers:(id)arg2 queue:(id)arg3 usingBackgroundSession:(BOOL)arg4 completionHandler:(/*^block*/id)arg5 ;
-(void)firNetwork_logWithLevel:(long long)arg1 message:(id)arg2 contexts:(id)arg3 ;
-(void)firNetwork_logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3 ;
-(void)firNetwork_logWithLevel:(long long)arg1 message:(id)arg2 ;
-(void)setIsDebugModeEnabled:(BOOL)arg1 ;
-(void)handleErrorWithCode:(long long)arg1 queue:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)reachability:(id)arg1 statusChanged:(int)arg2 ;
-(id<FIRNetworkReachabilityDelegate>)reachabilityDelegate;
-(id<FIRNetworkLoggerDelegate>)loggerDelegate;
-(void)dealloc;
-(id)init;
-(BOOL)isDebugModeEnabled;
-(BOOL)isNetworkConnected;
-(void)setTimeoutInterval:(double)arg1 ;
-(double)timeoutInterval;
@end

