/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSURLSessionDelegate.h>
#import <libobjc.A.dylib/NSURLSessionTaskDelegate.h>
#import <Super Mario Run/NSURLSessionDownloadDelegate.h>

@protocol FIRNetworkLoggerDelegate;
@class NSString, NSURLSessionConfiguration, NSURL, NSData, NSURLRequest;

@interface FIRNetworkURLSession : NSObject <NSURLSessionDelegate, NSURLSessionTaskDelegate, NSURLSessionDownloadDelegate> {

	/*^block*/id _completionHandler;
	NSString* _sessionID;
	NSURLSessionConfiguration* _sessionConfig;
	NSURL* _networkDirectoryURL;
	NSData* _downloadedData;
	NSURL* _uploadingFileURL;
	NSURLRequest* _request;
	BOOL _backgroundNetworkEnabled;
	id<FIRNetworkLoggerDelegate> _loggerDelegate;

}

@property (assign,getter=isBackgroundNetworkEnabled,nonatomic) BOOL backgroundNetworkEnabled;              //@synthesize backgroundNetworkEnabled=_backgroundNetworkEnabled - In the implementation block
@property (assign,nonatomic,__weak) id<FIRNetworkLoggerDelegate> loggerDelegate;                           //@synthesize loggerDelegate=_loggerDelegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)handleEventsForBackgroundURLSessionID:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
+(id)fetcherWithSessionIdentifier:(id)arg1 ;
+(id)sessionIDToFetcherMap;
+(id)sessionIDToSystemCompletionHandlerDictionary;
-(void)setLoggerDelegate:(id<FIRNetworkLoggerDelegate>)arg1 ;
-(id)initWithNetworkLoggerDelegate:(id)arg1 ;
-(void)setBackgroundNetworkEnabled:(BOOL)arg1 ;
-(id)sessionIDFromAsyncPOSTRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)sessionIDFromAsyncGETRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id<FIRNetworkLoggerDelegate>)loggerDelegate;
-(void)addSystemCompletionHandler:(/*^block*/id)arg1 forSession:(id)arg2 ;
-(id)temporaryFilePathWithSessionID:(id)arg1 ;
-(void)maybeRemoveTempFilesAtURL:(id)arg1 expiringTime:(double)arg2 ;
-(BOOL)ensureTemporaryDirectoryExists;
-(void)excludeFromBackupForURL:(id)arg1 ;
-(id)backgroundSessionConfigWithSessionID:(id)arg1 ;
-(void)populateSessionConfig:(id)arg1 withRequest:(id)arg2 ;
-(void)callCompletionHandler:(/*^block*/id)arg1 withResponse:(id)arg2 data:(id)arg3 error:(id)arg4 ;
-(void)callSystemCompletionHandler:(id)arg1 ;
-(void)removeTempItemAtURL:(id)arg1 ;
-(BOOL)isBackgroundNetworkEnabled;
-(void)setSessionID:(id)arg1 ;
-(void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(/*^block*/id)arg5 ;
-(void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3 ;
-(void)URLSessionDidFinishEventsForBackgroundURLSession:(id)arg1 ;
-(void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3 ;
@end

