/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDictionary, NSString;

@interface FIROptions : NSObject <NSCopying> {

	NSDictionary* _analyticsOptionsDictionary;
	long long _createAnalyticsOptionsDictionaryOnce;
	BOOL _usingOptionsFromDefaultPlist;
	NSString* _deepLinkURLScheme;
	NSDictionary* _optionsDictionary;

}

@property (nonatomic,retain) NSDictionary * optionsDictionary;                         //@synthesize optionsDictionary=_optionsDictionary - In the implementation block
@property (nonatomic,readonly) NSDictionary * analyticsOptionsDictionary; 
@property (nonatomic,readonly) BOOL isAnalyticsCollectionEnabled; 
@property (nonatomic,readonly) BOOL isAnalyticsCollectionDeactivated; 
@property (nonatomic,copy,readonly) NSString * libraryVersionID; 
@property (assign,nonatomic) BOOL usingOptionsFromDefaultPlist;                        //@synthesize usingOptionsFromDefaultPlist=_usingOptionsFromDefaultPlist - In the implementation block
@property (nonatomic,readonly) BOOL isMeasurementEnabled; 
@property (nonatomic,readonly) BOOL isAnalyticsEnabled; 
@property (nonatomic,readonly) BOOL isSignInEnabled; 
@property (nonatomic,copy,readonly) NSString * APIKey; 
@property (nonatomic,copy,readonly) NSString * clientID; 
@property (nonatomic,copy,readonly) NSString * trackingID; 
@property (nonatomic,copy,readonly) NSString * GCMSenderID; 
@property (nonatomic,copy,readonly) NSString * androidClientID; 
@property (nonatomic,copy,readonly) NSString * googleAppID; 
@property (nonatomic,copy,readonly) NSString * databaseURL; 
@property (nonatomic,copy) NSString * deepLinkURLScheme;                               //@synthesize deepLinkURLScheme=_deepLinkURLScheme - In the implementation block
@property (nonatomic,copy,readonly) NSString * storageBucket; 
+(id)defaultOptionsDictionary;
+(id)plistFilePathWithName:(id)arg1 ;
+(void)resetDefaultOptions;
+(id)defaultOptions;
-(NSString *)GCMSenderID;
-(NSString *)googleAppID;
-(BOOL)isAnalyticsCollectionEnabled;
-(BOOL)isAnalyticsCollectionDeactivated;
-(id)initInternalWithOptionsDictionary:(id)arg1 ;
-(void)setOptionsDictionary:(NSDictionary *)arg1 ;
-(NSString *)deepLinkURLScheme;
-(void)setDeepLinkURLScheme:(NSString *)arg1 ;
-(NSDictionary *)analyticsOptionsDictionary;
-(BOOL)isMeasurementEnabled;
-(id)initWithGoogleAppID:(id)arg1 bundleID:(id)arg2 GCMSenderID:(id)arg3 APIKey:(id)arg4 clientID:(id)arg5 trackingID:(id)arg6 androidClientID:(id)arg7 databaseURL:(id)arg8 storageBucket:(id)arg9 deepLinkURLScheme:(id)arg10 ;
-(NSString *)APIKey;
-(NSString *)androidClientID;
-(NSString *)libraryVersionID;
-(NSString *)storageBucket;
-(BOOL)isAnalyticsEnabled;
-(BOOL)isSignInEnabled;
-(BOOL)usingOptionsFromDefaultPlist;
-(void)setUsingOptionsFromDefaultPlist:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithContentsOfFile:(id)arg1 ;
-(NSDictionary *)optionsDictionary;
-(NSString *)clientID;
-(NSString *)databaseURL;
-(NSString *)trackingID;
@end

