/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Super Mario Run/Super Mario Run-Structs.h>
@class NSString;

@interface GIPReachability : NSObject {

	NSString* hostName_;
	SCNetworkReachabilityRef reachability_;
	unsigned reachabilityFlags_;
	BOOL monitoring_;
	BOOL hasPostedNotification_;

}

@property (nonatomic,copy) NSString * hostName; 
@property (assign,nonatomic) BOOL monitoring; 
+(BOOL)wasPreviouslyReachable:(id)arg1 ;
-(id)initWithHostName:(id)arg1 ;
-(BOOL)isCellularNetwork;
-(BOOL)isFlagEnabled:(unsigned)arg1 ;
-(void)callbackWithFlags:(unsigned)arg1 ;
-(BOOL)isConnectionOnTraffic;
-(BOOL)isConnectionOnDemand;
-(BOOL)isInterventionRequired;
-(NSString *)hostName;
-(BOOL)isDirect;
-(void)dealloc;
-(id)init;
-(void)stop;
-(void)start;
-(void)setMonitoring:(BOOL)arg1 ;
-(BOOL)monitoring;
-(BOOL)isConnectionRequired;
-(void)startWithCompletionHandler:(/*^block*/id)arg1 ;
-(BOOL)isReachable;
-(void)setHostName:(NSString *)arg1 ;
-(id)initWithReachability:(SCNetworkReachabilityRef)arg1 ;
@end

