/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, GSDK_PBMutableArray, GSDK_PBFileOptions, GSDK_PBSourceCodeInfo;

@interface GSDK_PBFileDescriptorProto : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasName; 
@property (nonatomic,retain) NSString * name; 
@property (assign,nonatomic) BOOL hasPackage; 
@property (nonatomic,retain) NSString * package; 
@property (assign,nonatomic) BOOL hasDependencyArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * dependencyArray; 
@property (assign,nonatomic) BOOL hasPublicDependencyArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * publicDependencyArray; 
@property (assign,nonatomic) BOOL hasWeakDependencyArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * weakDependencyArray; 
@property (assign,nonatomic) BOOL hasMessageTypeArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * messageTypeArray; 
@property (assign,nonatomic) BOOL hasEnumTypeArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * enumTypeArray; 
@property (assign,nonatomic) BOOL hasServiceArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * serviceArray; 
@property (assign,nonatomic) BOOL hasExtensionArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * extensionArray; 
@property (assign,nonatomic) BOOL hasOptions; 
@property (nonatomic,retain) GSDK_PBFileOptions * options; 
@property (assign,nonatomic) BOOL hasSourceCodeInfo; 
@property (nonatomic,retain) GSDK_PBSourceCodeInfo * sourceCodeInfo; 
@property (assign,nonatomic) BOOL hasSyntax; 
@property (nonatomic,retain) NSString * syntax; 
+(id)descriptor;
@end

