/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class GSDK_PBMutableArray, GSDK_PBArray;

@interface GSDK_PBField : NSObject {

	int number_;
	GSDK_PBMutableArray* mutableVarintList_;
	GSDK_PBMutableArray* mutableFixed32List_;
	GSDK_PBMutableArray* mutableFixed64List_;
	GSDK_PBMutableArray* mutableLengthDelimitedList_;
	GSDK_PBMutableArray* mutableGroupList_;

}

@property (nonatomic,retain,readonly) GSDK_PBArray * varintList; 
@property (nonatomic,retain,readonly) GSDK_PBArray * fixed32List; 
@property (nonatomic,retain,readonly) GSDK_PBArray * fixed64List; 
@property (nonatomic,retain,readonly) GSDK_PBArray * lengthDelimitedList; 
@property (nonatomic,retain,readonly) GSDK_PBArray * groupList; 
@property (nonatomic,readonly) int number; 
-(unsigned long long)serializedSize;
-(void)writeToOutput:(id)arg1 ;
-(void)writeAsMessageSetExtensionToOutput:(id)arg1 ;
-(unsigned long long)serializedSizeAsMessageSetExtension;
-(GSDK_PBArray *)varintList;
-(GSDK_PBArray *)fixed32List;
-(GSDK_PBArray *)fixed64List;
-(GSDK_PBArray *)lengthDelimitedList;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(GSDK_PBArray *)groupList;
-(int)number;
@end

