/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSMutableCopying.h>

@interface GSDK_PBUnknownFieldSet : NSObject <NSCopying, NSMutableCopying> {

	CFDictionaryRef fields_;

}
+(BOOL)isFieldTag:(int)arg1 ;
-(unsigned long long)serializedSize;
-(void)mergeFromCodedInputStream:(id)arg1 ;
-(void)writeToCodedOutputStream:(id)arg1 ;
-(id)initWithFields:(CFDictionaryRef)arg1 ;
-(id)getFieldBuilder:(int)arg1 create:(BOOL)arg2 ;
-(BOOL)mergeFieldFrom:(int)arg1 input:(id)arg2 ;
-(BOOL)hasField:(int)arg1 ;
-(id)getField:(int)arg1 ;
-(unsigned long long)countOfFields;
-(void)writeAsMessageSetTo:(id)arg1 ;
-(unsigned long long)serializedSizeAsMessageSet;
-(void)mergeField:(id)arg1 ;
-(void)mergeUnknownFields:(id)arg1 ;
-(void)mergeFromData:(id)arg1 ;
-(void)mergeVarintField:(int)arg1 value:(int)arg2 ;
-(void)mergeMessageSetMessage:(int)arg1 data:(id)arg2 ;
-(id)sortedFields;
-(void)getTags:(int*)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)data;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)addField:(id)arg1 ;
@end

