/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBField.h>

@interface GSDK_PBMutableField : GSDK_PBField
-(void)mergeFromField:(id)arg1 ;
-(void)addVarint:(unsigned long long)arg1 ;
-(void)addFixed32:(unsigned)arg1 ;
-(void)addFixed64:(unsigned long long)arg1 ;
-(void)addLengthDelimited:(id)arg1 ;
-(void)addGroup:(id)arg1 ;
-(id)initWithNumber:(int)arg1 ;
@end

