/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <Super Mario Run/GSDK_PBRootObject.h>
#import <Super Mario Run/PBMutableArrayDelegate.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSMutableCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@protocol OS_dispatch_semaphore;
@class GSDK_PBUnknownFieldSet, NSMutableDictionary, GSDK_PBFieldDescriptor, GSDK_PBExtensionField, NSObject, NSString;

@interface GSDK_PBGeneratedMessage : GSDK_PBRootObject <PBMutableArrayDelegate, NSCopying, NSMutableCopying, NSSecureCoding> {

	GSDK_PBUnknownFieldSet* unknownFields_;
	NSMutableDictionary* extensionMap_;
	NSMutableDictionary* autocreatedExtensionMap_;
	GSDK_PBGeneratedMessage* autocreator_;
	GSDK_PBFieldDescriptor* autocreatorField_;
	GSDK_PBExtensionField* autocreatorExtension_;
	PBGeneratedMessage_StorageRef messageStorage_;
	long long readOnlySemaphoreCreationOnce_;
	NSObject*<OS_dispatch_semaphore> readOnlySemaphore_;

}

@property (nonatomic,retain) GSDK_PBUnknownFieldSet * unknownFields; 
@property (getter=isInitialized,nonatomic,readonly) BOOL initialized; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)parseFromData:(id)arg1 ;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2 error:(id*)arg3 ;
+(id)newMessageWithAutocreator:(id)arg1 extension:(id)arg2 ;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2 ;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 ;
+(id)parseDelimitedFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 ;
+(id)parseFromData:(id)arg1 error:(id*)arg2 ;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 error:(id*)arg3 ;
+(id)parseDelimitedFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 error:(id*)arg3 ;
+(id)newMessageWithAutocreator:(id)arg1 field:(id)arg2 ;
+(BOOL)accessInstanceVariablesDirectly;
+(BOOL)resolveInstanceMethod:(SEL)arg1 ;
+(id)alloc;
+(id)allocWithZone:(NSZone*)arg1 ;
+(BOOL)supportsSecureCoding;
+(void)initialize;
+(id)message;
+(id)descriptor;
-(unsigned long long)serializedSize;
-(void)pbMutableArray:(id)arg1 willAddElements:(unsigned long long)arg2 ;
-(void)writeToCodedOutputStream:(id)arg1 ;
-(void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 ;
-(void)addExtension:(id)arg1 value:(id)arg2 ;
-(id)getExistingExtension:(id)arg1 ;
-(void)setExtension:(id)arg1 value:(id)arg2 ;
-(void)internalClear;
-(void)copyFieldsInto:(id)arg1 zone:(NSZone*)arg2 ;
-(BOOL)isInitialized:(id)arg1 ;
-(void)writeDelimitedToCodedOutputStream:(id)arg1 ;
-(void)writeExtensionsToCodedOutputStream:(id)arg1 range:(id)arg2 ;
-(void)writeField:(id)arg1 toCodedOutputStream:(id)arg2 ;
-(void)clearExtension:(id)arg1 ;
-(void)mergeFromData:(id)arg1 extensionRegistry:(id)arg2 ;
-(void)mergeDelimitedFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 ;
-(void)setUnknownFields:(GSDK_PBUnknownFieldSet *)arg1 ;
-(id)mutableUnknownFields;
-(void)parseMessageSet:(id)arg1 extensionRegistry:(id)arg2 ;
-(BOOL)parseUnknownField:(id)arg1 extensionRegistry:(id)arg2 tag:(unsigned)arg3 ;
-(unsigned long long)extensionsSerializedSize;
-(id)delimitedData;
-(void)writeToOutputStream:(id)arg1 ;
-(void)writeDelimitedToOutputStream:(id)arg1 ;
-(BOOL)hasExtension:(id)arg1 ;
-(id)extensionsCurrentlySet;
-(void)setExtension:(id)arg1 index:(unsigned long long)arg2 value:(id)arg3 ;
-(void)mergeUnknownFields:(id)arg1 ;
-(BOOL)wasAutocreatedBy:(id)arg1 ;
-(void)clearAutocreator;
-(id)sortedExtensionsInUse;
-(id)getExtension:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)data;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)clear;
-(id)descriptor;
-(void)mergeFrom:(id)arg1 ;
-(GSDK_PBUnknownFieldSet *)unknownFields;
-(BOOL)isInitialized;
@end

