/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, GSDK_PBFieldOptions;

@interface GSDK_PBFieldDescriptorProto : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasName; 
@property (nonatomic,retain) NSString * name; 
@property (assign,nonatomic) BOOL hasNumber; 
@property (assign,nonatomic) int number; 
@property (assign,nonatomic) BOOL hasLabel; 
@property (assign,nonatomic) int label; 
@property (assign,nonatomic) BOOL hasType; 
@property (assign,nonatomic) int type; 
@property (assign,nonatomic) BOOL hasTypeName; 
@property (nonatomic,retain) NSString * typeName; 
@property (assign,nonatomic) BOOL hasExtendee; 
@property (nonatomic,retain) NSString * extendee; 
@property (assign,nonatomic) BOOL hasDefaultValue; 
@property (nonatomic,retain) NSString * defaultValue; 
@property (assign,nonatomic) BOOL hasOneofIndex; 
@property (assign,nonatomic) int oneofIndex; 
@property (assign,nonatomic) BOOL hasJsonName; 
@property (nonatomic,retain) NSString * jsonName; 
@property (assign,nonatomic) BOOL hasOptions; 
@property (nonatomic,retain) GSDK_PBFieldOptions * options; 
+(id)descriptor;
@end

