/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, GSDK_PBMutableArray, GSDK_PBMessageOptions;

@interface GSDK_PBDescriptorProto : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasName; 
@property (nonatomic,retain) NSString * name; 
@property (assign,nonatomic) BOOL hasFieldArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * fieldArray; 
@property (assign,nonatomic) BOOL hasExtensionArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * extensionArray; 
@property (assign,nonatomic) BOOL hasNestedTypeArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * nestedTypeArray; 
@property (assign,nonatomic) BOOL hasEnumTypeArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * enumTypeArray; 
@property (assign,nonatomic) BOOL hasExtensionRangeArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * extensionRangeArray; 
@property (assign,nonatomic) BOOL hasOneofDeclArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * oneofDeclArray; 
@property (assign,nonatomic) BOOL hasOptions; 
@property (nonatomic,retain) GSDK_PBMessageOptions * options; 
@property (assign,nonatomic) BOOL hasReservedRangeArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * reservedRangeArray; 
@property (assign,nonatomic) BOOL hasReservedNameArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * reservedNameArray; 
+(id)descriptor;
@end

