/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class GSDK_PBExtensionDescriptor, GSDK_PBDescriptor, NSString;

@interface GSDK_PBExtensionField : NSObject <NSCopying> {

	PBExtensionDescription* description_;
	SCD_Union_GS26 defaultPBValue_;
	Class messageOrGroupClass_;
	GSDK_PBExtensionDescriptor* descriptor_;
	GSDK_PBDescriptor* containingType_;

}

@property (nonatomic,readonly) int fieldNumber; 
@property (nonatomic,readonly) int wireType; 
@property (nonatomic,readonly) BOOL isRepeated; 
@property (nonatomic,readonly) GSDK_PBDescriptor * containingType; 
@property (nonatomic,readonly) Class containingMessageClass; 
@property (nonatomic,readonly) NSString * singletonName; 
@property (nonatomic,readonly) id defaultValue; 
@property (nonatomic,readonly) GSDK_PBExtensionDescriptor * descriptor; 
-(BOOL)isRepeated;
-(NSString *)singletonName;
-(int)fieldNumber;
-(unsigned long long)computePBSerializedSizeNoTag:(/*function pointer*/void*)arg1 ;
-(void)writePBValue:(/*function pointer*/void*)arg1 noTagToCodedOutputStream:(id)arg2 ;
-(void)writePBValue:(/*function pointer*/void*)arg1 includingTagToCodedOutputStream:(id)arg2 ;
-(void)writePBValues:(id)arg1 includingTagsToCodedOutputStream:(id)arg2 ;
-(unsigned long long)computePBSerializedSizeIncludingTag:(/*function pointer*/void*)arg1 ;
-(unsigned long long)computePBSerializedSizesIncludingTags:(id)arg1 ;
-(GSDK_PBDescriptor *)containingType;
-(id)readSingleValueFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 existingValue:(id)arg3 ;
-(Class)containingMessageClass;
-(int)wireType;
-(void)writeValue:(id)arg1 includingTagToCodedOutputStream:(id)arg2 ;
-(unsigned long long)computeSerializedSizeIncludingTag:(id)arg1 ;
-(void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 builder:(id)arg3 ;
-(long long)compareByFieldNumber:(id)arg1 ;
-(id)initWithDescription:(PBExtensionDescription*)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(GSDK_PBExtensionDescriptor *)descriptor;
-(id)defaultValue;
@end

