/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class GSDK_PBMutableArray;

@interface GSDK_PBFieldOptions : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasCtype; 
@property (assign,nonatomic) int ctype; 
@property (assign,nonatomic) BOOL hasPacked; 
@property (assign,nonatomic) BOOL packed; 
@property (assign,nonatomic) BOOL hasJtype; 
@property (assign,nonatomic) int jtype; 
@property (assign,nonatomic) BOOL hasJstype; 
@property (assign,nonatomic) int jstype; 
@property (assign,nonatomic) BOOL hasLazy; 
@property (assign,nonatomic) BOOL lazy; 
@property (assign,nonatomic) BOOL hasDeprecated; 
@property (assign,nonatomic) BOOL deprecated; 
@property (assign,nonatomic) BOOL hasWeak; 
@property (assign,nonatomic) BOOL weak; 
@property (assign,nonatomic) BOOL hasUpgradedOptionArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * upgradedOptionArray; 
@property (assign,nonatomic) BOOL hasDeprecatedRawMessage; 
@property (assign,nonatomic) BOOL deprecatedRawMessage; 
@property (assign,nonatomic) BOOL hasEnforceUtf8; 
@property (assign,nonatomic) BOOL enforceUtf8; 
@property (assign,nonatomic) BOOL hasUninterpretedOptionArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * uninterpretedOptionArray; 
+(id)descriptor;
@end

