/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class NSString, GSDK_PBMethodOptions;

@interface GSDK_PBMethodDescriptorProto : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasName; 
@property (nonatomic,retain) NSString * name; 
@property (assign,nonatomic) BOOL hasInputType; 
@property (nonatomic,retain) NSString * inputType; 
@property (assign,nonatomic) BOOL hasOutputType; 
@property (nonatomic,retain) NSString * outputType; 
@property (assign,nonatomic) BOOL hasOptions; 
@property (nonatomic,retain) GSDK_PBMethodOptions * options; 
@property (assign,nonatomic) BOOL hasClientStreaming; 
@property (assign,nonatomic) BOOL clientStreaming; 
@property (assign,nonatomic) BOOL hasServerStreaming; 
@property (assign,nonatomic) BOOL serverStreaming; 
+(id)descriptor;
@end

