/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class GSDK_PBArray, NSString;

@interface GSDK_PBDescriptor : NSObject <NSCopying> {

	GSDK_PBArray* fields_;
	Class messageClass_;
	GSDK_PBArray* enums_;
	GSDK_PBArray* extensions_;
	unsigned long long storageSize_;
	BOOL wireFormat_;
	GSDK_PBArray* extensionRanges_;

}

@property (nonatomic,retain,readonly) NSString * name; 
@property (nonatomic,retain,readonly) GSDK_PBArray * fields; 
@property (nonatomic,retain,readonly) GSDK_PBArray * enums; 
@property (nonatomic,retain,readonly) GSDK_PBArray * extensions; 
@property (nonatomic,retain,readonly) GSDK_PBArray * extensionRanges; 
@property (nonatomic,readonly) unsigned long long storageSize; 
@property (getter=isWireFormat,nonatomic,readonly) BOOL wireFormat; 
@property (nonatomic,readonly) Class messageClass; 
+(id)allocDescriptorForClass:(Class)arg1 rootClass:(Class)arg2 fields:(PBMessageFieldDescription*)arg3 fieldCount:(unsigned long long)arg4 enums:(PBMessageEnumDescription*)arg5 enumCount:(unsigned long long)arg6 ranges:(PBMessageExtensionRangeDescription*)arg7 rangeCount:(unsigned long long)arg8 storageSize:(unsigned long long)arg9 wireFormat:(BOOL)arg10 ;
+(id)allocDescriptorForClass:(Class)arg1 rootClass:(Class)arg2 fields:(PBMessageFieldDescription*)arg3 fieldCount:(unsigned long long)arg4 enums:(PBMessageEnumDescription*)arg5 enumCount:(unsigned long long)arg6 ranges:(PBMessageExtensionRangeDescription*)arg7 rangeCount:(unsigned long long)arg8 storageSize:(unsigned long long)arg9 wireFormat:(BOOL)arg10 extraTextFormatInfo:(const char*)arg11 ;
-(id)initWithClass:(Class)arg1 fields:(id)arg2 enums:(id)arg3 extensions:(id)arg4 extensionRanges:(id)arg5 storageSize:(unsigned long long)arg6 wireFormat:(BOOL)arg7 ;
-(id)fieldWithNumber:(unsigned)arg1 ;
-(id)fieldWithName:(id)arg1 ;
-(id)enumWithName:(id)arg1 ;
-(id)extensionWithNumber:(unsigned)arg1 ;
-(id)extensionWithName:(id)arg1 ;
-(GSDK_PBArray *)enums;
-(GSDK_PBArray *)extensionRanges;
-(unsigned long long)storageSize;
-(BOOL)isWireFormat;
-(void)dealloc;
-(NSString *)name;
-(id)copyWithZone:(NSZone*)arg1 ;
-(GSDK_PBArray *)extensions;
-(GSDK_PBArray *)fields;
-(Class)messageClass;
@end

