/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class GSDK_PBMutableArray;

@interface GSDK_PBMessageOptions : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasExperimentalJavaMessageInterfaceArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * experimentalJavaMessageInterfaceArray; 
@property (assign,nonatomic) BOOL hasExperimentalJavaBuilderInterfaceArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * experimentalJavaBuilderInterfaceArray; 
@property (assign,nonatomic) BOOL hasExperimentalJavaInterfaceExtendsArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * experimentalJavaInterfaceExtendsArray; 
@property (assign,nonatomic) BOOL hasJavaliteSerializable; 
@property (assign,nonatomic) BOOL javaliteSerializable; 
@property (assign,nonatomic) BOOL hasMessageSetWireFormat; 
@property (assign,nonatomic) BOOL messageSetWireFormat; 
@property (assign,nonatomic) BOOL hasNoStandardDescriptorAccessor; 
@property (assign,nonatomic) BOOL noStandardDescriptorAccessor; 
@property (assign,nonatomic) BOOL hasDeprecated; 
@property (assign,nonatomic) BOOL deprecated; 
@property (assign,nonatomic) BOOL hasMapEntry; 
@property (assign,nonatomic) BOOL mapEntry; 
@property (assign,nonatomic) BOOL hasUninterpretedOptionArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * uninterpretedOptionArray; 
+(id)descriptor;
@end

