/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/GSDK_PBGeneratedMessage.h>

@class GSDK_PBMutableArray, NSString, NSData;

@interface GSDK_PBUninterpretedOption : GSDK_PBGeneratedMessage

@property (assign,nonatomic) BOOL hasNameArray; 
@property (nonatomic,retain) GSDK_PBMutableArray * nameArray; 
@property (assign,nonatomic) BOOL hasIdentifierValue; 
@property (nonatomic,retain) NSString * identifierValue; 
@property (assign,nonatomic) BOOL hasPositiveIntValue; 
@property (assign,nonatomic) unsigned long long positiveIntValue; 
@property (assign,nonatomic) BOOL hasNegativeIntValue; 
@property (assign,nonatomic) long long negativeIntValue; 
@property (assign,nonatomic) BOOL hasDoubleValue; 
@property (assign,nonatomic) double doubleValue; 
@property (assign,nonatomic) BOOL hasStringValue; 
@property (nonatomic,retain) NSData * stringValue; 
@property (assign,nonatomic) BOOL hasAggregateValue; 
@property (nonatomic,retain) NSString * aggregateValue; 
+(id)descriptor;
@end

