/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSString;

@interface GTMURLBuilder : NSObject {

	NSMutableDictionary* params_;
	NSString* baseURLString_;

}

@property (nonatomic,readonly) NSString * baseURLString; 
+(id)builderWithString:(id)arg1 ;
+(id)builderWithURL:(id)arg1 ;
-(NSString *)baseURLString;
-(void)setIntegerValue:(long long)arg1 forParameter:(id)arg2 ;
-(long long)integerValueForParameter:(id)arg1 ;
-(void)removeParameter:(id)arg1 ;
-(id)valueForParameter:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithString:(id)arg1 ;
-(id)URL;
-(id)parameters;
-(void)setParameters:(id)arg1 ;
-(id)URLString;
-(void)setValue:(id)arg1 forParameter:(id)arg2 ;
@end

