/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface NPFError : NSObject {

	int _errorType;
	long long _errorCode;
	NSString* _errorMessage;

}

@property (assign,nonatomic) int errorType;                      //@synthesize errorType=_errorType - In the implementation block
@property (assign,nonatomic) long long errorCode;                //@synthesize errorCode=_errorCode - In the implementation block
@property (nonatomic,copy) NSString * errorMessage;              //@synthesize errorMessage=_errorMessage - In the implementation block
-(void)setErrorType:(int)arg1 ;
-(void)setErrorCode:(long long)arg1 ;
-(long long)errorCode;
-(int)errorType;
-(void)setErrorMessage:(NSString *)arg1 ;
-(NSString *)errorMessage;
@end

