/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface NPFImageData : NSObject {

	NSString* _imageId;
	NSString* _url;
	NSString* _format;
	long long _width;
	long long _height;
	long long _createdAt;

}

@property (nonatomic,copy) NSString * imageId;                 //@synthesize imageId=_imageId - In the implementation block
@property (nonatomic,copy) NSString * url;                     //@synthesize url=_url - In the implementation block
@property (nonatomic,copy) NSString * format;                  //@synthesize format=_format - In the implementation block
@property (assign,nonatomic) long long width;                  //@synthesize width=_width - In the implementation block
@property (assign,nonatomic) long long height;                 //@synthesize height=_height - In the implementation block
@property (assign,nonatomic) long long createdAt;              //@synthesize createdAt=_createdAt - In the implementation block
+(void)storeImageData:(id)arg1 withCallback:(/*^block*/id)arg2 ;
-(NSString *)imageId;
-(void)setImageId:(NSString *)arg1 ;
-(NSString *)url;
-(long long)width;
-(void)setUrl:(NSString *)arg1 ;
-(long long)height;
-(void)setWidth:(long long)arg1 ;
-(void)setHeight:(long long)arg1 ;
-(long long)createdAt;
-(NSString *)format;
-(void)setFormat:(NSString *)arg1 ;
-(void)setCreatedAt:(long long)arg1 ;
@end

