/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <Super Mario Run/SFSafariViewControllerDelegate.h>

@class NSString, NPFMii, NSArray, NSDictionary, SFSafariViewController;

@interface NPFNintendoAccount : NSObject <SFSafariViewControllerDelegate> {

	BOOL _isExecuting;
	int _type;
	int _gender;
	NSString* _nintendoAccountId;
	NSString* _nickname;
	NSString* _language;
	NSString* _country;
	NSString* _region;
	NSString* _timezone;
	long long _birthdayYear;
	long long _birthdayMonth;
	long long _birthdayDay;
	NSString* _nintendoNetworkId;
	NPFMii* _mii;
	NSString* _idToken;
	NSString* _accessToken;
	NSString* _sessionToken;
	NSArray* _requestScope;
	NSDictionary* _profileSource;
	/*^block*/id _callback;
	NSString* _state;
	NSString* _verifier;
	SFSafariViewController* _loginViewController;

}

@property (nonatomic,retain) NSString * nintendoAccountId;                              //@synthesize nintendoAccountId=_nintendoAccountId - In the implementation block
@property (assign,nonatomic) int type;                                                  //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSString * nickname;                                       //@synthesize nickname=_nickname - In the implementation block
@property (assign,nonatomic) int gender;                                                //@synthesize gender=_gender - In the implementation block
@property (nonatomic,retain) NSString * language;                                       //@synthesize language=_language - In the implementation block
@property (nonatomic,retain) NSString * country;                                        //@synthesize country=_country - In the implementation block
@property (nonatomic,retain) NSString * region;                                         //@synthesize region=_region - In the implementation block
@property (nonatomic,retain) NSString * timezone;                                       //@synthesize timezone=_timezone - In the implementation block
@property (assign,nonatomic) long long birthdayYear;                                    //@synthesize birthdayYear=_birthdayYear - In the implementation block
@property (assign,nonatomic) long long birthdayMonth;                                   //@synthesize birthdayMonth=_birthdayMonth - In the implementation block
@property (assign,nonatomic) long long birthdayDay;                                     //@synthesize birthdayDay=_birthdayDay - In the implementation block
@property (nonatomic,retain) NSString * nintendoNetworkId;                              //@synthesize nintendoNetworkId=_nintendoNetworkId - In the implementation block
@property (nonatomic,retain) NPFMii * mii;                                              //@synthesize mii=_mii - In the implementation block
@property (nonatomic,retain) NSString * idToken;                                        //@synthesize idToken=_idToken - In the implementation block
@property (nonatomic,retain) NSString * accessToken;                                    //@synthesize accessToken=_accessToken - In the implementation block
@property (nonatomic,retain) NSString * sessionToken;                                   //@synthesize sessionToken=_sessionToken - In the implementation block
@property (nonatomic,retain) NSArray * requestScope;                                    //@synthesize requestScope=_requestScope - In the implementation block
@property (nonatomic,retain) NSDictionary * profileSource;                              //@synthesize profileSource=_profileSource - In the implementation block
@property (nonatomic,copy) id callback;                                                 //@synthesize callback=_callback - In the implementation block
@property (assign,nonatomic) BOOL isExecuting;                                          //@synthesize isExecuting=_isExecuting - In the implementation block
@property (nonatomic,retain) NSString * state;                                          //@synthesize state=_state - In the implementation block
@property (nonatomic,retain) NSString * verifier;                                       //@synthesize verifier=_verifier - In the implementation block
@property (nonatomic,retain) SFSafariViewController * loginViewController;              //@synthesize loginViewController=_loginViewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)getRandomString:(int)arg1 ;
+(id)getQueryParameterForAuth:(id)arg1 withProfileSource:(id)arg2 andState:(id)arg3 andVerifier:(id)arg4 andIdToken:(id)arg5 ;
+(id)getURLDecodeString:(id)arg1 ;
+(void)executeTokenEndpoint:(BOOL)arg1 withSessionToken:(id)arg2 andCallback:(/*^block*/id)arg3 ;
+(id)makeTokenCodeChallenge:(id)arg1 ;
+(id)allocWithZone:(NSZone*)arg1 ;
+(id)sharedManager;
-(SFSafariViewController *)loginViewController;
-(void)getSessionToken:(id)arg1 ;
-(NSString *)idToken;
-(NSString *)nintendoAccountId;
-(void)saveSessionToken;
-(void)authorizeByNintendoAccount:(id)arg1 andProfileSource:(id)arg2 andIdToken:(id)arg3 andCallback:(/*^block*/id)arg4 ;
-(void)resetNintendoAccount;
-(void)setIdToken:(NSString *)arg1 ;
-(void)setBirthdayYear:(long long)arg1 ;
-(void)setBirthdayMonth:(long long)arg1 ;
-(void)setBirthdayDay:(long long)arg1 ;
-(long long)birthdayYear;
-(long long)birthdayMonth;
-(long long)birthdayDay;
-(void)setProfileSource:(NSDictionary *)arg1 ;
-(void)setRequestScope:(NSArray *)arg1 ;
-(void)getSessionTokenCode:(id)arg1 ;
-(void)setVerifier:(NSString *)arg1 ;
-(NSArray *)requestScope;
-(NSDictionary *)profileSource;
-(NSString *)verifier;
-(void)setLoginViewController:(SFSafariViewController *)arg1 ;
-(void)finish:(id)arg1 withNPFError:(id)arg2 ;
-(void)setNintendoAccountId:(NSString *)arg1 ;
-(void)setNintendoNetworkId:(NSString *)arg1 ;
-(void)setMii:(NPFMii *)arg1 ;
-(void)sendPurchaseEmailToParent:(id)arg1 ;
-(NSString *)nintendoNetworkId;
-(NPFMii *)mii;
-(NSString *)sessionToken;
-(void)setSessionToken:(NSString *)arg1 ;
-(id)init;
-(NSString *)state;
-(void)setState:(NSString *)arg1 ;
-(void)setType:(int)arg1 ;
-(int)type;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setRegion:(NSString *)arg1 ;
-(NSString *)region;
-(NSString *)language;
-(void)setLanguage:(NSString *)arg1 ;
-(BOOL)isExecuting;
-(void)setTimezone:(NSString *)arg1 ;
-(NSString *)timezone;
-(id)callback;
-(void)setCallback:(id)arg1 ;
-(void)setCountry:(NSString *)arg1 ;
-(NSString *)country;
-(int)gender;
-(void)setGender:(int)arg1 ;
-(void)setAccessToken:(NSString *)arg1 ;
-(NSString *)nickname;
-(void)setNickname:(NSString *)arg1 ;
-(void)safariViewControllerDidFinish:(id)arg1 ;
-(void)setIsExecuting:(BOOL)arg1 ;
-(NSString *)accessToken;
@end

