/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NPFMii;

@interface NPFOtherUser : NSObject {

	NSString* _userId;
	NSString* _nickname;
	NSString* _nintendoAccountNickname;
	NPFMii* _nintendoAccountMii;

}

@property (nonatomic,copy) NSString * userId;                               //@synthesize userId=_userId - In the implementation block
@property (nonatomic,copy) NSString * nickname;                             //@synthesize nickname=_nickname - In the implementation block
@property (nonatomic,copy) NSString * nintendoAccountNickname;              //@synthesize nintendoAccountNickname=_nintendoAccountNickname - In the implementation block
@property (nonatomic,retain) NPFMii * nintendoAccountMii;                   //@synthesize nintendoAccountMii=_nintendoAccountMii - In the implementation block
+(void)getAsList:(id)arg1 withCallback:(/*^block*/id)arg2 ;
-(NSString *)nintendoAccountNickname;
-(NPFMii *)nintendoAccountMii;
-(void)setNintendoAccountNickname:(NSString *)arg1 ;
-(void)setNintendoAccountMii:(NPFMii *)arg1 ;
-(NSString *)nickname;
-(void)setNickname:(NSString *)arg1 ;
-(void)setUserId:(NSString *)arg1 ;
-(NSString *)userId;
@end

