/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface NPFPointWallet : NSObject {

	NSString* _pointKey;
	long long _totalAmount;

}

@property (nonatomic,copy) NSString * pointKey;                  //@synthesize pointKey=_pointKey - In the implementation block
@property (assign,nonatomic) long long totalAmount;              //@synthesize totalAmount=_totalAmount - In the implementation block
+(void)getUserPointWallet:(/*^block*/id)arg1 ;
+(id)getTermPointURL;
-(void)setPointKey:(NSString *)arg1 ;
-(void)setTotalAmount:(long long)arg1 ;
-(NSString *)pointKey;
-(long long)totalAmount;
@end

