/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Super Mario Run/Super Mario Run-Structs.h>
@class NSString;

@interface NPFPushNotificationChannel : NSObject {

	NSString* _deviceToken;
	NSString* _tempDeviceToken;

}

@property (nonatomic,retain) NSString * deviceToken;                  //@synthesize deviceToken=_deviceToken - In the implementation block
@property (nonatomic,retain) NSString * tempDeviceToken;              //@synthesize tempDeviceToken=_tempDeviceToken - In the implementation block
+(id)allocWithZone:(NSZone*)arg1 ;
+(id)sharedManager;
-(void)setDeviceToken:(NSString *)arg1 ;
-(void)registerDeviceToken:(id)arg1 ;
-(void)sendDeviceToken;
-(NSString *)deviceToken;
-(void)setTempDeviceToken:(NSString *)arg1 ;
-(NSString *)tempDeviceToken;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)timeZoneOffset;
@end

