/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface NPFReportType : NSObject {

	NSString* _reportTypeId;
	NSString* _reportTypeName;
	NSString* _language;

}

@property (nonatomic,copy) NSString * reportTypeId;                //@synthesize reportTypeId=_reportTypeId - In the implementation block
@property (nonatomic,copy) NSString * reportTypeName;              //@synthesize reportTypeName=_reportTypeName - In the implementation block
@property (nonatomic,copy) NSString * language;                    //@synthesize language=_language - In the implementation block
+(void)getAsList:(id)arg1 withCallback:(/*^block*/id)arg2 ;
-(void)setReportTypeId:(NSString *)arg1 ;
-(void)setReportTypeName:(NSString *)arg1 ;
-(NSString *)reportTypeId;
-(NSString *)reportTypeName;
-(NSString *)language;
-(void)setLanguage:(NSString *)arg1 ;
@end

