/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NPFEventHandler;
#import <Super Mario Run/Super Mario Run-Structs.h>
@class NSObject, NSTimer;

@interface NPFSDK : NSObject {

	BOOL _paused;
	BOOL _isNintendoAuthCancel;
	BOOL _initCompleted;
	BOOL _immediateLogin;
	NSObject*<NPFEventHandler> _eventHandler;
	NSTimer* _updateTimer;
	long long _pausedTimestamp;
	long long _startedTimestamp;
	long long _pausedDuration;

}

@property (nonatomic,retain) NSObject*<NPFEventHandler> eventHandler;              //@synthesize eventHandler=_eventHandler - In the implementation block
@property (nonatomic,retain) NSTimer * updateTimer;                                //@synthesize updateTimer=_updateTimer - In the implementation block
@property (assign,nonatomic) long long pausedTimestamp;                            //@synthesize pausedTimestamp=_pausedTimestamp - In the implementation block
@property (assign,nonatomic) long long startedTimestamp;                           //@synthesize startedTimestamp=_startedTimestamp - In the implementation block
@property (assign,nonatomic) long long pausedDuration;                             //@synthesize pausedDuration=_pausedDuration - In the implementation block
@property (assign,nonatomic) BOOL paused;                                          //@synthesize paused=_paused - In the implementation block
@property (assign,nonatomic) BOOL isNintendoAuthCancel;                            //@synthesize isNintendoAuthCancel=_isNintendoAuthCancel - In the implementation block
@property (assign,nonatomic) BOOL initCompleted;                                   //@synthesize initCompleted=_initCompleted - In the implementation block
@property (assign,nonatomic) BOOL immediateLogin;                                  //@synthesize immediateLogin=_immediateLogin - In the implementation block
+(BOOL)handleUrl:(id)arg1 ;
+(void)registerDeviceToken:(id)arg1 ;
+(void)init:(id)arg1 withOptions:(id)arg2 andImmediateLogin:(BOOL)arg3 ;
+(void)retryBaaSAuth:(/*^block*/id)arg1 ;
+(void)resetTimestamp;
+(void)sendSessionEvent:(id)arg1 withDuration:(long long)arg2 ;
+(id)getCurrentBaaSUser;
+(BOOL)isSandbox;
+(id)getLanguage;
+(void)init:(id)arg1 withOptions:(id)arg2 ;
+(void)retryBaaSAuth:(id)arg1 withDevicePassword:(id)arg2 andCallback:(/*^block*/id)arg3 ;
+(id)getDeviceToken;
+(void)authorizeByNintendoAccount:(id)arg1 andProfileSource:(id)arg2 andCallback:(/*^block*/id)arg3 ;
+(id)getNintendoAccountFAQURL;
+(id)getSDKVersion;
+(void)resetDeviceAccount;
+(id)allocWithZone:(NSZone*)arg1 ;
+(void)setLanguage:(id)arg1 ;
+(id)sharedManager;
-(void)applicationDidBecomeActiveNotification:(id)arg1 ;
-(void)applicationWillResignActiveNotification:(id)arg1 ;
-(void)setImmediateLogin:(BOOL)arg1 ;
-(BOOL)initCompleted;
-(BOOL)immediateLogin;
-(long long)pausedTimestamp;
-(long long)pausedDuration;
-(void)setPausedDuration:(long long)arg1 ;
-(long long)startedTimestamp;
-(void)timerUpdate:(id)arg1 ;
-(void)setPausedTimestamp:(long long)arg1 ;
-(void)setIsNintendoAuthCancel:(BOOL)arg1 ;
-(BOOL)isNintendoAuthCancel;
-(void)setInitCompleted:(BOOL)arg1 ;
-(void)setStartedTimestamp:(long long)arg1 ;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setPaused:(BOOL)arg1 ;
-(NSTimer *)updateTimer;
-(void)setUpdateTimer:(NSTimer *)arg1 ;
-(BOOL)paused;
-(void)setEventHandler:(NSObject*<NPFEventHandler>)arg1 ;
-(NSObject*<NPFEventHandler>)eventHandler;
@end

