/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSURLConnectionDataDelegate.h>

@class NSString, NSDictionary, NSData, NSMutableData;

@interface NPFSDKHttpClient : NSObject <NSURLConnectionDataDelegate> {

	BOOL _retry;
	NSString* _method;
	NSString* _scheme;
	NSString* _host;
	NSString* _path;
	NSDictionary* _headers;
	NSDictionary* _queryParam;
	NSString* _contentType;
	NSData* _data;
	/*^block*/id _callback;
	long long _statusCode;
	NSDictionary* _responseHeaders;
	NSMutableData* _receivedData;

}

@property (retain) NSString * method;                               //@synthesize method=_method - In the implementation block
@property (retain) NSString * scheme;                               //@synthesize scheme=_scheme - In the implementation block
@property (retain) NSString * host;                                 //@synthesize host=_host - In the implementation block
@property (retain) NSString * path;                                 //@synthesize path=_path - In the implementation block
@property (retain) NSDictionary * headers;                          //@synthesize headers=_headers - In the implementation block
@property (retain) NSDictionary * queryParam;                       //@synthesize queryParam=_queryParam - In the implementation block
@property (retain) NSString * contentType;                          //@synthesize contentType=_contentType - In the implementation block
@property (retain) NSData * data;                                   //@synthesize data=_data - In the implementation block
@property (nonatomic,copy) id callback;                             //@synthesize callback=_callback - In the implementation block
@property (assign) BOOL retry;                                      //@synthesize retry=_retry - In the implementation block
@property (assign) long long statusCode;                            //@synthesize statusCode=_statusCode - In the implementation block
@property (retain) NSDictionary * responseHeaders;                  //@synthesize responseHeaders=_responseHeaders - In the implementation block
@property (retain) NSMutableData * receivedData;                    //@synthesize receivedData=_receivedData - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)makeAcceptLanguageHeader;
-(void)execute:(id)arg1 withScheme:(id)arg2 andHost:(id)arg3 andPath:(id)arg4 andHeaders:(id)arg5 andQueryParam:(id)arg6 andContentType:(id)arg7 andData:(id)arg8 andCallback:(/*^block*/id)arg9 andRetry:(BOOL)arg10 ;
-(void)setQueryParam:(NSDictionary *)arg1 ;
-(void)updateAccessToken;
-(NSDictionary *)queryParam;
-(void)setContentType:(NSString *)arg1 ;
-(NSString *)scheme;
-(NSString *)path;
-(NSData *)data;
-(void)setData:(NSData *)arg1 ;
-(NSString *)contentType;
-(NSString *)host;
-(void)setPath:(NSString *)arg1 ;
-(long long)statusCode;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(NSString *)method;
-(void)setScheme:(NSString *)arg1 ;
-(id)callback;
-(void)setCallback:(id)arg1 ;
-(void)setHost:(NSString *)arg1 ;
-(void)setStatusCode:(long long)arg1 ;
-(BOOL)retry;
-(void)setHeaders:(NSDictionary *)arg1 ;
-(NSDictionary *)headers;
-(NSMutableData *)receivedData;
-(void)setReceivedData:(NSMutableData *)arg1 ;
-(void)sendRequest;
-(void)setResponseHeaders:(NSDictionary *)arg1 ;
-(NSDictionary *)responseHeaders;
-(void)setRetry:(BOOL)arg1 ;
-(void)setMethod:(NSString *)arg1 ;
@end

