/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface NPFVirtualCurrencyWallet : NSObject {

	NSString* _virtualCurrencyName;
	long long _totalBalance;
	long long _freeBalance;
	NSDictionary* _paidBalance;

}

@property (nonatomic,copy) NSString * virtualCurrencyName;              //@synthesize virtualCurrencyName=_virtualCurrencyName - In the implementation block
@property (assign,nonatomic) long long totalBalance;                    //@synthesize totalBalance=_totalBalance - In the implementation block
@property (assign,nonatomic) long long freeBalance;                     //@synthesize freeBalance=_freeBalance - In the implementation block
@property (nonatomic,copy) NSDictionary * paidBalance;                  //@synthesize paidBalance=_paidBalance - In the implementation block
+(void)getAll:(/*^block*/id)arg1 ;
-(void)setVirtualCurrencyName:(NSString *)arg1 ;
-(NSString *)virtualCurrencyName;
-(void)setTotalBalance:(long long)arg1 ;
-(void)setFreeBalance:(long long)arg1 ;
-(void)setPaidBalance:(NSDictionary *)arg1 ;
-(long long)totalBalance;
-(long long)freeBalance;
-(NSDictionary *)paidBalance;
@end

