/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDecimalNumber;

@interface NPFVirtualCurrencyPurchasedSummary : NSObject {

	NSString* _virtualCurrencyName;
	NSDecimalNumber* _lifeTimePurchasedUSD;
	long long _lifeTimePurchasedAmount;
	NSDecimalNumber* _thisDayPurchasedUSD;
	long long _thisDayPurchasedAmount;
	NSDecimalNumber* _thisMonthPurchasedUSD;
	long long _thisMonthPurchasedAmount;

}

@property (nonatomic,copy) NSString * virtualCurrencyName;                         //@synthesize virtualCurrencyName=_virtualCurrencyName - In the implementation block
@property (assign,nonatomic) NSDecimalNumber * lifeTimePurchasedUSD;               //@synthesize lifeTimePurchasedUSD=_lifeTimePurchasedUSD - In the implementation block
@property (assign,nonatomic) long long lifeTimePurchasedAmount;                    //@synthesize lifeTimePurchasedAmount=_lifeTimePurchasedAmount - In the implementation block
@property (assign,nonatomic) NSDecimalNumber * thisDayPurchasedUSD;                //@synthesize thisDayPurchasedUSD=_thisDayPurchasedUSD - In the implementation block
@property (assign,nonatomic) long long thisDayPurchasedAmount;                     //@synthesize thisDayPurchasedAmount=_thisDayPurchasedAmount - In the implementation block
@property (assign,nonatomic) NSDecimalNumber * thisMonthPurchasedUSD;              //@synthesize thisMonthPurchasedUSD=_thisMonthPurchasedUSD - In the implementation block
@property (assign,nonatomic) long long thisMonthPurchasedAmount;                   //@synthesize thisMonthPurchasedAmount=_thisMonthPurchasedAmount - In the implementation block
+(void)getAll:(long long)arg1 withCallback:(/*^block*/id)arg2 ;
-(void)setVirtualCurrencyName:(NSString *)arg1 ;
-(void)setLifeTimePurchasedUSD:(NSDecimalNumber *)arg1 ;
-(void)setLifeTimePurchasedAmount:(long long)arg1 ;
-(void)setThisDayPurchasedUSD:(NSDecimalNumber *)arg1 ;
-(void)setThisDayPurchasedAmount:(long long)arg1 ;
-(void)setThisMonthPurchasedUSD:(NSDecimalNumber *)arg1 ;
-(void)setThisMonthPurchasedAmount:(long long)arg1 ;
-(NSString *)virtualCurrencyName;
-(NSDecimalNumber *)lifeTimePurchasedUSD;
-(long long)lifeTimePurchasedAmount;
-(NSDecimalNumber *)thisDayPurchasedUSD;
-(long long)thisDayPurchasedAmount;
-(NSDecimalNumber *)thisMonthPurchasedUSD;
-(long long)thisMonthPurchasedAmount;
@end

