/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PlayerWrapper : NSObject
+(void)loadUserPhotoAsyncAndTriggerCallbackWhenNeeded:(id)arg1 withCondition:(BOOL)arg2 index:(int)arg3 totalSize:(int)arg4 ;
+(void)processUsers:(id)arg1 withCondition:(BOOL)arg2 friendCallback:(/*^block*/id)arg3 ;
+(void)loadUserIds:(id)arg1 withCondition:(BOOL)arg2 ;
+(void)processNonFriendUsersUsingNewAPI:(id)arg1 withFriends:(id)arg2 ;
+(void)loadFriends;
@end

