/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <Super Mario Run/RenderPluginDelegate.h>

@protocol RenderPluginDelegate <LifeCycleListener,NSObject>
@optional
-(void)onFrameResolved;
-(void)onBeforeMainDisplaySurfaceRecreate:(RenderingSurfaceParamsRef)arg1;
-(void)onAfterMainDisplaySurfaceRecreate;

@required
-(void)mainDisplayInited:(UnityDisplaySurfaceBase*)arg1;

@end


@class NSString;

@interface RenderPluginDelegate : NSObject <RenderPluginDelegate> {

	UnityDisplaySurfaceBase* mainDisplaySurface;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)mainDisplayInited:(UnityDisplaySurfaceBase*)arg1 ;
@end

