/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:33 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSOutputStream, NSData, NSString, GSDK_PBGeneratedMessage, GSDK_PBArray, GSDK_PBEnumDescriptor;

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct {
	char* field1;
	char* field2;
	long long field3;
	long long field4;
	long long field5;
	BOOL field6;
	BOOL field7;
} SCD_Struct_Ke3;

typedef struct opaqueCMSampleBuffer* opaqueCMSampleBufferRef;

typedef struct CMVideoSampling {
	void cvTextureCache;
	void cvTextureCacheTexture;
	void cvImageBuffer;
} CMVideoSampling;

typedef struct {
	long long value;
	int timescale;
	unsigned flags;
	long long epoch;
} SCD_Struct_Vi6;

typedef struct RenderingSurfaceParams* RenderingSurfaceParamsRef;

typedef struct _darwin_sigaltstack {
	void ss_sp;
	unsigned long long ss_size;
	int ss_flags;
} darwin_sigaltstack;

typedef struct __CFUUID* CFUUIDRef;

typedef struct timeval {
	long long tv_sec;
	int tv_usec;
} timeval;

typedef struct PLCrashHostInfoVersion {
	unsigned long long major;
	unsigned long long minor;
	unsigned long long revision;
} PLCrashHostInfoVersion;

typedef struct {
	unsigned long long field1;
	id field2;
	unsigned long long field3;
	unsigned long long field4[5];
} SCD_Struct_Un12;

typedef struct plcrash_mach_exception_port_set {
	unsigned count;
	unsigned masks[14];
	unsigned ports[14];
	int behaviors[14];
	int flavors[14];
} plcrash_mach_exception_port_set;

typedef struct OpaqueAUGraph* OpaqueAUGraphRef;

typedef struct OpaqueAudioComponentInstance* OpaqueAudioComponentInstanceRef;

typedef struct AudioStreamBasicDescription {
	double mSampleRate;
	unsigned mFormatID;
	unsigned mFormatFlags;
	unsigned mBytesPerPacket;
	unsigned mFramesPerPacket;
	unsigned mBytesPerFrame;
	unsigned mChannelsPerFrame;
	unsigned mBitsPerChannel;
	unsigned mReserved;
} AudioStreamBasicDescription;

typedef struct _NSZone* NSZoneRef;

typedef struct UIEdgeInsets {
	double top;
	double left;
	double bottom;
	double right;
} UIEdgeInsets;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct __SecKey* SecKeyRef;

typedef struct sqlite3* sqlite3Ref;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

typedef struct __asl_object_s* asl_object_sRef;

typedef struct PBInputBufferState {
	char* bytes;
	unsigned long long bufferSize;
	unsigned long long bufferPos;
	unsigned long long currentLimit;
} PBInputBufferState;

typedef struct PBOutputBufferState {
	char* bytes;
	unsigned long long size;
	unsigned long long position;
	NSOutputStream* output;
} PBOutputBufferState;

typedef union {
	BOOL valueBool;
	unsigned valueFixed32;
	int valueSFixed32;
	float valueFloat;
	unsigned long long valueFixed64;
	long long valueSFixed64;
	double valueDouble;
	int valueInt32;
	long long valueInt64;
	int valueSInt32;
	long long valueSInt64;
	unsigned valueUInt32;
	unsigned long long valueUInt64;
	NSData* valueData;
	NSString* valueString;
	GSDK_PBGeneratedMessage* valueMessage;
	GSDK_PBGeneratedMessage* valueGroup;
	int valueEnum;
	GSDK_PBArray* valueArray;
	id valueObject;
} SCD_Union_GS26;

typedef union {
	GSDK_PBEnumDescriptor* enumDescriptor_;
	/*function pointer*/void* enumVerifier_;
} SCD_Union_GS27;

typedef struct PBGeneratedMessage_Storage* PBGeneratedMessage_StorageRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct {
	void bytes;
	unsigned long long bufferSize;
	unsigned long long bufferPos;
} SCD_Struct_FI30;

typedef struct CGPath* CGPathRef;

typedef struct __SecRandom* SecRandomRef;

typedef struct {
	long long field1;
	long long field2;
	long long field3;
} SCD_Struct_FB33;

