/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UnityPLCrashReportProcessorInfo, NSString;

@interface UnityPLCrashReportBinaryImageInfo : NSObject {

	UnityPLCrashReportProcessorInfo* _processorInfo;
	unsigned long long _baseAddress;
	unsigned long long _imageSize;
	NSString* _imageName;
	BOOL _hasImageUUID;
	NSString* _imageUUID;

}

@property (nonatomic,readonly) UnityPLCrashReportProcessorInfo * codeType;              //@synthesize processorInfo=_processorInfo - In the implementation block
@property (nonatomic,readonly) unsigned long long imageBaseAddress;                     //@synthesize baseAddress=_baseAddress - In the implementation block
@property (nonatomic,readonly) unsigned long long imageSize;                            //@synthesize imageSize=_imageSize - In the implementation block
@property (nonatomic,readonly) NSString * imageName;                                    //@synthesize imageName=_imageName - In the implementation block
@property (nonatomic,readonly) BOOL hasImageUUID;                                       //@synthesize hasImageUUID=_hasImageUUID - In the implementation block
@property (nonatomic,readonly) NSString * imageUUID;                                    //@synthesize imageUUID=_imageUUID - In the implementation block
-(id)initWithCodeType:(id)arg1 baseAddress:(unsigned long long)arg2 size:(unsigned long long)arg3 name:(id)arg4 uuid:(id)arg5 ;
-(BOOL)hasImageUUID;
-(unsigned long long)imageBaseAddress;
-(UnityPLCrashReportProcessorInfo *)codeType;
-(void)dealloc;
-(unsigned long long)imageSize;
-(NSString *)imageName;
-(NSString *)imageUUID;
@end

