/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDate;

@interface UnityPLCrashReportSystemInfo : NSObject {

	int _operatingSystem;
	NSString* _osVersion;
	NSString* _osBuild;
	int _architecture;
	NSDate* _timestamp;

}

@property (nonatomic,readonly) int operatingSystem;                            //@synthesize operatingSystem=_operatingSystem - In the implementation block
@property (nonatomic,readonly) NSString * operatingSystemVersion;              //@synthesize osVersion=_osVersion - In the implementation block
@property (nonatomic,readonly) NSString * operatingSystemBuild;                //@synthesize osBuild=_osBuild - In the implementation block
@property (nonatomic,readonly) int architecture;                               //@synthesize architecture=_architecture - In the implementation block
@property (nonatomic,readonly) NSDate * timestamp;                             //@synthesize timestamp=_timestamp - In the implementation block
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 operatingSystemBuild:(id)arg3 architecture:(int)arg4 timestamp:(id)arg5 ;
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 architecture:(int)arg3 timestamp:(id)arg4 ;
-(NSString *)operatingSystemBuild;
-(int)operatingSystem;
-(NSString *)operatingSystemVersion;
-(void)dealloc;
-(NSDate *)timestamp;
-(int)architecture;
@end

