/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <Super Mario Run/UnityRenderingView.h>

@interface UnityView : UnityRenderingView {

	CGSize _surfaceSize;
	int _curOrientation;
	BOOL _recreateView;

}

@property (nonatomic,readonly) int contentOrientation;              //@synthesize curOrientation=_curOrientation - In the implementation block
-(void)recreateGLESSurfaceIfNeeded;
-(void)recreateGLESSurface;
-(int)contentOrientation;
-(void)onUpdateSurfaceSize:(CGSize)arg1 ;
-(void)initImpl:(CGRect)arg1 scaleFactor:(double)arg2 ;
-(id)initWithFrame:(CGRect)arg1 scaleFactor:(double)arg2 ;
-(id)initFromMainScreen;
-(void)willRotateToOrientation:(long long)arg1 fromOrientation:(long long)arg2 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)didRotate;
@end

