/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Super Mario Run/Super Mario Run-Structs.h>
#import <libobjc.A.dylib/ADBannerViewDelegate.h>
#import <Super Mario Run/UnityViewControllerListener.h>

@class ADBannerView, NSString;

@interface UnityADBanner : NSObject <ADBannerViewDelegate, UnityViewControllerListener> {

	ADBannerView* _view;
	CGPoint _userLayoutCenter;
	int _bannerLayout;
	BOOL _showingBanner;

}

@property (nonatomic,copy,readonly) ADBannerView * view;              //@synthesize view=_view - In the implementation block
@property (nonatomic,readonly) BOOL adVisible;                        //@synthesize showingBanner=_showingBanner - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)interfaceWillChangeOrientation:(id)arg1 ;
-(void)interfaceDidChangeOrientation:(id)arg1 ;
-(void)layoutBannerImpl;
-(float)layoutXImpl:(id)arg1 ;
-(float)layoutYImpl:(id)arg1 ;
-(void)initImpl:(id)arg1 layout:(int)arg2 type:(int)arg3 ;
-(id)initWithParent:(id)arg1 layout:(int)arg2 type:(int)arg3 ;
-(id)initWithParent:(id)arg1 layout:(int)arg2 ;
-(void)layoutBanner:(int)arg1 ;
-(void)positionForUserLayout:(CGPoint)arg1 ;
-(void)showBanner:(BOOL)arg1 ;
-(BOOL)adVisible;
-(void)dealloc;
-(ADBannerView *)view;
-(void)bannerViewDidLoadAd:(id)arg1 ;
-(void)bannerView:(id)arg1 didFailToReceiveAdWithError:(id)arg2 ;
-(BOOL)bannerViewActionShouldBegin:(id)arg1 willLeaveApplication:(BOOL)arg2 ;
-(void)bannerViewActionDidFinish:(id)arg1 ;
@end

