/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface UnityPLCrashReportRegisterInfo : NSObject {

	NSString* _registerName;
	unsigned long long _registerValue;

}

@property (nonatomic,readonly) NSString * registerName;                       //@synthesize registerName=_registerName - In the implementation block
@property (nonatomic,readonly) unsigned long long registerValue;              //@synthesize registerValue=_registerValue - In the implementation block
-(id)initWithRegisterName:(id)arg1 registerValue:(unsigned long long)arg2 ;
-(NSString *)registerName;
-(unsigned long long)registerValue;
-(void)dealloc;
@end

