/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Super Mario Run/Super Mario Run-Structs.h>
@class NSString;

@interface UnityPLCrashProcessInfo : NSObject {

	int _processID;
	NSString* _processName;
	int _parentProcessID;
	timeval _startTime;
	BOOL _traced;

}

@property (nonatomic,readonly) int processID;                            //@synthesize processID=_processID - In the implementation block
@property (nonatomic,readonly) NSString * processName;                   //@synthesize processName=_processName - In the implementation block
@property (nonatomic,readonly) int parentProcessID;                      //@synthesize parentProcessID=_parentProcessID - In the implementation block
@property (nonatomic,readonly) timeval startTime;                        //@synthesize startTime=_startTime - In the implementation block
@property (getter=isTraced,nonatomic,readonly) BOOL traced;              //@synthesize traced=_traced - In the implementation block
+(id)currentProcessInfo;
-(int)parentProcessID;
-(id)initWithProcessID:(int)arg1 ;
-(void)dealloc;
-(NSString *)processName;
-(timeval)startTime;
-(int)processID;
-(BOOL)isTraced;
@end

