/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface UnityPLCrashReportThreadInfo : NSObject {

	long long _threadNumber;
	NSArray* _stackFrames;
	BOOL _crashed;
	NSArray* _registers;

}

@property (nonatomic,readonly) long long threadNumber;              //@synthesize threadNumber=_threadNumber - In the implementation block
@property (nonatomic,readonly) NSArray * stackFrames;               //@synthesize stackFrames=_stackFrames - In the implementation block
@property (nonatomic,readonly) BOOL crashed;                        //@synthesize crashed=_crashed - In the implementation block
@property (nonatomic,readonly) NSArray * registers;                 //@synthesize registers=_registers - In the implementation block
-(id)initWithThreadNumber:(long long)arg1 stackFrames:(id)arg2 crashed:(BOOL)arg3 registers:(id)arg4 ;
-(BOOL)crashed;
-(long long)threadNumber;
-(NSArray *)stackFrames;
-(NSArray *)registers;
-(void)dealloc;
@end

