/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface UnityPLCrashReportProcessorInfo : NSObject {

	int _typeEncoding;
	unsigned long long _type;
	unsigned long long _subtype;

}

@property (nonatomic,readonly) int typeEncoding;                        //@synthesize typeEncoding=_typeEncoding - In the implementation block
@property (nonatomic,readonly) unsigned long long type;                 //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) unsigned long long subtype;              //@synthesize subtype=_subtype - In the implementation block
-(id)initWithTypeEncoding:(int)arg1 type:(unsigned long long)arg2 subtype:(unsigned long long)arg3 ;
-(unsigned long long)type;
-(unsigned long long)subtype;
-(int)typeEncoding;
@end

