/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 16, 2016 at 1:28:32 PM Central European Standard Time
* Operating System: Version 9.3.2 (Build 13F69)
* Image Source: /var/containers/Bundle/Application/DF2FE387-EFC2-4765-9E85-C2CDC49533B4/rb_12_01_16:02:52.app/Super Mario Run
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, UnityPLCrashReportProcessorInfo;

@interface UnityPLCrashReportMachineInfo : NSObject {

	NSString* _modelName;
	UnityPLCrashReportProcessorInfo* _processorInfo;
	unsigned long long _processorCount;
	unsigned long long _logicalProcessorCount;

}

@property (nonatomic,readonly) NSString * modelName;                                         //@synthesize modelName=_modelName - In the implementation block
@property (nonatomic,readonly) UnityPLCrashReportProcessorInfo * processorInfo;              //@synthesize processorInfo=_processorInfo - In the implementation block
@property (nonatomic,readonly) unsigned long long processorCount;                            //@synthesize processorCount=_processorCount - In the implementation block
@property (nonatomic,readonly) unsigned long long logicalProcessorCount;                     //@synthesize logicalProcessorCount=_logicalProcessorCount - In the implementation block
-(id)initWithModelName:(id)arg1 processorInfo:(id)arg2 processorCount:(unsigned long long)arg3 logicalProcessorCount:(unsigned long long)arg4 ;
-(UnityPLCrashReportProcessorInfo *)processorInfo;
-(unsigned long long)logicalProcessorCount;
-(void)dealloc;
-(unsigned long long)processorCount;
-(NSString *)modelName;
@end

